### PR TITLE
delete: test ec2

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/bin/terraform plan -input=false -refresh -out \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/130/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/130/default": exit status 1
╷
│ Error: Reference to undeclared module
│ 
│   on modules/environment/production/main.tf line 30, in module "domain":
│   30:   proxy_target = module.ec2.ip
│ 
│ No module call named "ec2" is declared in module.production.
╵

```

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # module.production.module.domain.aws_route53_record.domain has changed
~ resource "aws_route53_record" "domain" {
        id              = "Z0097287UVNCC6G4O03H_test.rhea-so.com_A"
        name            = "test.rhea-so.com"
        # (6 unchanged attributes hidden)
    }

  # module.production.module.ec2.aws_instance.ec2 has changed
~ resource "aws_instance" "ec2" {
      ~ associate_public_ip_address          = false -> true
        id                                   = "i-0ee7e543fb0c57e02"
      + public_ip                            = "52.79.147.21"
        tags                                 = {
            "Name" = "test-ec2"
        }
        # (26 unchanged attributes hidden)





        # (5 unchanged blocks hidden)
    }

  # module.production.module.home-sg.aws_security_group.security-group has changed
~ resource "aws_security_group" "security-group" {
      ~ egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 22
              + ipv6_cidr_blocks = [
                  + "::/0",
                ]
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 22
            },
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = ""
              - from_port        = 22
              - ipv6_cidr_blocks = [
                  - "::0/0",
                ]
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 22
            },
        ]
        id                     = "sg-0ca28bfad29672cc3"
        name                   = "home-sg-security-group"
        tags                   = {
            "Name" = "home-sg-security-group"
        }
        # (7 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
- destroy

Terraform will perform the following actions:

  # module.production.module.domain.aws_route53_record.domain will be destroyed
  # (because aws_route53_record.domain is not in configuration)
- resource "aws_route53_record" "domain" {
      - allow_overwrite = true -> null
      - fqdn            = "test.rhea-so.com" -> null
      - id              = "Z0097287UVNCC6G4O03H_test.rhea-so.com_A" -> null
      - name            = "test.rhea-so.com" -> null
      - records         = [
          - "52.79.147.21",
        ] -> null
      - ttl             = 300 -> null
      - type            = "A" -> null
      - zone_id         = "Z0097287UVNCC6G4O03H" -> null
    }

  # module.production.module.ec2.aws_eip.eip will be destroyed
  # (because aws_eip.eip is not in configuration)
- resource "aws_eip" "eip" {
      - allocation_id        = "eipalloc-05d45002bae73dad1" -> null
      - association_id       = "eipassoc-024c6363d72ac40e0" -> null
      - domain               = "vpc" -> null
      - id                   = "eipalloc-05d45002bae73dad1" -> null
      - instance             = "i-0ee7e543fb0c57e02" -> null
      - network_border_group = "ap-northeast-2" -> null
      - network_interface    = "eni-0d611b3cf99270344" -> null
      - private_dns          = "ip-10-0-1-14.ap-northeast-2.compute.internal" -> null
      - private_ip           = "10.0.1.14" -> null
      - public_dns           = "ec2-52-79-147-21.ap-northeast-2.compute.amazonaws.com" -> null
      - public_ip            = "52.79.147.21" -> null
      - public_ipv4_pool     = "amazon" -> null
      - tags                 = {
          - "Name" = "test-eip"
        } -> null
      - tags_all             = {
          - "Name" = "test-eip"
        } -> null
      - vpc                  = true -> null
    }

  # module.production.module.ec2.aws_instance.ec2 will be destroyed
  # (because aws_instance.ec2 is not in configuration)
- resource "aws_instance" "ec2" {
      - ami                                  = "ami-0454bb2fefc7de534" -> null
      - arn                                  = "arn:aws:ec2:ap-northeast-2:264842458097:instance/i-0ee7e543fb0c57e02" -> null
      - associate_public_ip_address          = true -> null
      - availability_zone                    = "ap-northeast-2a" -> null
      - cpu_core_count                       = 1 -> null
      - cpu_threads_per_core                 = 2 -> null
      - disable_api_termination              = false -> null
      - ebs_optimized                        = false -> null
      - get_password_data                    = false -> null
      - hibernation                          = false -> null
      - id                                   = "i-0ee7e543fb0c57e02" -> null
      - instance_initiated_shutdown_behavior = "stop" -> null
      - instance_state                       = "running" -> null
      - instance_type                        = "t3.nano" -> null
      - ipv6_address_count                   = 0 -> null
      - ipv6_addresses                       = [] -> null
      - key_name                             = "Home" -> null
      - monitoring                           = false -> null
      - primary_network_interface_id         = "eni-0d611b3cf99270344" -> null
      - private_dns                          = "ip-10-0-1-14.ap-northeast-2.compute.internal" -> null
      - private_ip                           = "10.0.1.14" -> null
      - public_ip                            = "52.79.147.21" -> null
      - secondary_private_ips                = [] -> null
      - security_groups                      = [] -> null
      - source_dest_check                    = true -> null
      - subnet_id                            = "subnet-0d27582222e386668" -> null
      - tags                                 = {
          - "Name" = "test-ec2"
        } -> null
      - tags_all                             = {
          - "Name" = "test-ec2"
        } -> null
      - tenancy                              = "default" -> null
      - vpc_security_group_ids               = [
          - "sg-0ca28bfad29672cc3",
        ] -> null

      - capacity_reservation_specification {
          - capacity_reservation_preference = "open" -> null
        }

      - credit_specification {
          - cpu_credits = "unlimited" -> null
        }

      - enclave_options {
          - enabled = false -> null
        }

      - metadata_options {
          - http_endpoint               = "enabled" -> null
          - http_put_response_hop_limit = 1 -> null
          - http_tokens                 = "optional" -> null
          - instance_metadata_tags      = "disabled" -> null
        }

      - root_block_device {
          - delete_on_termination = true -> null
          - device_name           = "/dev/sda1" -> null
          - encrypted             = false -> null
          - iops                  = 100 -> null
          - tags                  = {} -> null
          - throughput            = 0 -> null
          - volume_id             = "vol-0c3bf5c56dab742a7" -> null
          - volume_size           = 8 -> null
          - volume_type           = "gp2" -> null
        }
    }

  # module.production.module.home-sg.aws_security_group.security-group will be updated in-place
~ resource "aws_security_group" "security-group" {
      ~ egress                 = [
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = ""
              - from_port        = 22
              - ipv6_cidr_blocks = [
                  - "::/0",
                ]
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 22
            },
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 22
              + ipv6_cidr_blocks = [
                  + "::0/0",
                ]
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 22
            },
        ]
        id                     = "sg-0ca28bfad29672cc3"
        name                   = "home-sg-security-group"
        tags                   = {
            "Name" = "home-sg-security-group"
        }
        # (7 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 3 to destroy.
Releasing state lock. This may take a few moments...

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 0 to add, 1 to change, 3 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
module.production.module.domain.aws_route53_record.domain: Destroying... [id=Z0097287UVNCC6G4O03H_test.rhea-so.com_A]
module.production.module.domain.aws_route53_record.domain: Still destroying... [id=Z0097287UVNCC6G4O03H_test.rhea-so.com_A, 10s elapsed]
module.production.module.domain.aws_route53_record.domain: Still destroying... [id=Z0097287UVNCC6G4O03H_test.rhea-so.com_A, 20s elapsed]
module.production.module.domain.aws_route53_record.domain: Still destroying... [id=Z0097287UVNCC6G4O03H_test.rhea-so.com_A, 30s elapsed]
module.production.module.domain.aws_route53_record.domain: Still destroying... [id=Z0097287UVNCC6G4O03H_test.rhea-so.com_A, 40s elapsed]
module.production.module.domain.aws_route53_record.domain: Destruction complete after 42s
module.production.module.ec2.aws_eip.eip: Destroying... [id=eipalloc-05d45002bae73dad1]
module.production.module.ec2.aws_eip.eip: Destruction complete after 1s
module.production.module.ec2.aws_instance.ec2: Destroying... [id=i-0ee7e543fb0c57e02]
module.production.module.ec2.aws_instance.ec2: Still destroying... [id=i-0ee7e543fb0c57e02, 10s elapsed]
module.production.module.ec2.aws_instance.ec2: Still destroying... [id=i-0ee7e543fb0c57e02, 20s elapsed]
module.production.module.ec2.aws_instance.ec2: Destruction complete after 29s
module.production.module.home-sg.aws_security_group.security-group: Modifying... [id=sg-0ca28bfad29672cc3]
module.production.module.home-sg.aws_security_group.security-group: Modifications complete after 1s [id=sg-0ca28bfad29672cc3]
Releasing state lock. This may take a few moments...

Apply complete! Resources: 0 added, 1 changed, 3 destroyed.


```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
