### PR TITLE
add: api gateway exit

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform init -input=false -upgrade" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/122/default": exit status 1
Upgrading modules...
- dev in modules/environment/dev
- production in modules/environment/production
- production.api-gateway in modules/aws/api-gateway
- production.atlantis-rhea-so in modules/aws/route53/record
- rhea-so in modules/aws/route53/zone
- staging in modules/environment/staging
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Duplicate resource "aws_api_gateway_integration" configuration
│ 
│   on modules/aws/api-gateway/main.tf line 58:
│   58: resource "aws_api_gateway_integration" "iac-api-gateway-integration" {
│ 
│ A aws_api_gateway_integration resource named "iac-api-gateway-integration"
│ was already declared at modules/aws/api-gateway/main.tf:31,1-69. Resource
│ names must be unique per type in each module.
╵


```
</details>

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # module.production.module.api-gateway.aws_api_gateway_integration.iac-api-gateway-integration has changed
~ resource "aws_api_gateway_integration" "iac-api-gateway-integration" {
      + cache_key_parameters    = []
        id                      = "agi-kb4bj3xon8-rekm5u-GET"
      + request_parameters      = {}
      + request_templates       = {}
        # (10 unchanged attributes hidden)
    }

  # module.production.module.api-gateway.aws_api_gateway_method.iac-api-gateway-method-google-enter has changed
~ resource "aws_api_gateway_method" "iac-api-gateway-method-google-enter" {
      + authorization_scopes = []
        id                   = "agm-kb4bj3xon8-rekm5u-GET"
      + request_models       = {}
      + request_parameters   = {}
        # (5 unchanged attributes hidden)
    }

  # module.production.module.api-gateway.aws_api_gateway_rest_api.iac-api-gateway has changed
~ resource "aws_api_gateway_rest_api" "iac-api-gateway" {
        id                           = "kb4bj3xon8"
        name                         = "iac-api-gateway"
      + tags                         = {}
        # (10 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
- destroy

Terraform will perform the following actions:

  # module.production.module.api-gateway.aws_api_gateway_integration.iac-api-gateway-integration will be destroyed
  # (because aws_api_gateway_integration.iac-api-gateway-integration is not in configuration)
- resource "aws_api_gateway_integration" "iac-api-gateway-integration" {
      - cache_key_parameters    = [] -> null
      - cache_namespace         = "rekm5u" -> null
      - connection_type         = "INTERNET" -> null
      - http_method             = "GET" -> null
      - id                      = "agi-kb4bj3xon8-rekm5u-GET" -> null
      - integration_http_method = "GET" -> null
      - passthrough_behavior    = "WHEN_NO_MATCH" -> null
      - request_parameters      = {} -> null
      - request_templates       = {} -> null
      - resource_id             = "rekm5u" -> null
      - rest_api_id             = "kb4bj3xon8" -> null
      - timeout_milliseconds    = 29000 -> null
      - type                    = "HTTP_PROXY" -> null
      - uri                     = "http://google.com" -> null
    }

  # module.production.module.api-gateway.aws_api_gateway_integration.iac-api-gateway-integration-google-enter will be created
+ resource "aws_api_gateway_integration" "iac-api-gateway-integration-google-enter" {
      + cache_namespace         = (known after apply)
      + connection_type         = "INTERNET"
      + http_method             = "GET"
      + id                      = (known after apply)
      + integration_http_method = "GET"
      + passthrough_behavior    = (known after apply)
      + resource_id             = "rekm5u"
      + rest_api_id             = "kb4bj3xon8"
      + timeout_milliseconds    = 29000
      + type                    = "HTTP_PROXY"
      + uri                     = "http://google.com"
    }

  # module.production.module.api-gateway.aws_api_gateway_integration.iac-api-gateway-integration-google-exit will be created
+ resource "aws_api_gateway_integration" "iac-api-gateway-integration-google-exit" {
      + cache_namespace         = (known after apply)
      + connection_type         = "INTERNET"
      + http_method             = "GET"
      + id                      = (known after apply)
      + integration_http_method = "GET"
      + passthrough_behavior    = (known after apply)
      + resource_id             = (known after apply)
      + rest_api_id             = "kb4bj3xon8"
      + timeout_milliseconds    = 29000
      + type                    = "HTTP_PROXY"
      + uri                     = "http://google.com"
    }

  # module.production.module.api-gateway.aws_api_gateway_method.iac-api-gateway-method-google-exit will be created
+ resource "aws_api_gateway_method" "iac-api-gateway-method-google-exit" {
      + api_key_required = false
      + authorization    = "NONE"
      + http_method      = "GET"
      + id               = (known after apply)
      + resource_id      = (known after apply)
      + rest_api_id      = "kb4bj3xon8"
    }

  # module.production.module.api-gateway.aws_api_gateway_resource.iac-api-gateway-resource-google-exit will be created
+ resource "aws_api_gateway_resource" "iac-api-gateway-resource-google-exit" {
      + id          = (known after apply)
      + parent_id   = "4jr77i"
      + path        = (known after apply)
      + path_part   = "exit"
      + rest_api_id = "kb4bj3xon8"
    }

Plan: 4 to add, 0 to change, 1 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 4 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
module.production.module.api-gateway.aws_api_gateway_integration.iac-api-gateway-integration: Destroying... [id=agi-kb4bj3xon8-rekm5u-GET]
module.production.module.api-gateway.aws_api_gateway_integration.iac-api-gateway-integration-google-enter: Creating...
module.production.module.api-gateway.aws_api_gateway_resource.iac-api-gateway-resource-google-exit: Creating...
module.production.module.api-gateway.aws_api_gateway_integration.iac-api-gateway-integration: Destruction complete after 0s
module.production.module.api-gateway.aws_api_gateway_integration.iac-api-gateway-integration-google-enter: Creation complete after 0s [id=agi-kb4bj3xon8-rekm5u-GET]
module.production.module.api-gateway.aws_api_gateway_resource.iac-api-gateway-resource-google-exit: Creation complete after 0s [id=tzp9x9]
module.production.module.api-gateway.aws_api_gateway_method.iac-api-gateway-method-google-exit: Creating...
module.production.module.api-gateway.aws_api_gateway_method.iac-api-gateway-method-google-exit: Creation complete after 0s [id=agm-kb4bj3xon8-tzp9x9-GET]
module.production.module.api-gateway.aws_api_gateway_integration.iac-api-gateway-integration-google-exit: Creating...
module.production.module.api-gateway.aws_api_gateway_integration.iac-api-gateway-integration-google-exit: Creation complete after 0s [id=agi-kb4bj3xon8-tzp9x9-GET]

Apply complete! Resources: 4 added, 0 changed, 1 destroyed.


```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
