### PR TITLE
fix: ecr IMMUTABLE to MUTABLE

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_ecr_repository.memo-ecr has changed
~ resource "aws_ecr_repository" "memo-ecr" {
        id                   = "memo-ecr"
        name                 = "memo-ecr"
      + tags                 = {}
        # (5 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # aws_ecr_repository.iac-ecr will be updated in-place
~ resource "aws_ecr_repository" "iac-ecr" {
        id                   = "iac-ecr"
      ~ image_tag_mutability = "IMMUTABLE" -> "MUTABLE"
        name                 = "iac-ecr"
        tags                 = {}
        # (4 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }

  # aws_ecr_repository.memo-ecr will be updated in-place
~ resource "aws_ecr_repository" "memo-ecr" {
        id                   = "memo-ecr"
      ~ image_tag_mutability = "IMMUTABLE" -> "MUTABLE"
        name                 = "memo-ecr"
        tags                 = {}
        # (4 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 0 to add, 2 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
aws_ecr_repository.iac-ecr: Modifying... [id=iac-ecr]
aws_ecr_repository.memo-ecr: Modifying... [id=memo-ecr]
aws_ecr_repository.memo-ecr: Modifications complete after 0s [id=memo-ecr]
aws_ecr_repository.iac-ecr: Modifications complete after 0s [id=iac-ecr]

Apply complete! Resources: 0 added, 2 changed, 0 destroyed.


```

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
