### PR TITLE
test: rhea-so zone_id

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `00_Environment/03_Production` workspace: `production`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.rhea-so.aws_route53_zone.domain will be created
+ resource "aws_route53_zone" "domain" {
      + arn           = (known after apply)
      + comment       = "Managed by Terraform"
      + force_destroy = true
      + id            = (known after apply)
      + name          = "rhea-so.com"
      + name_servers  = (known after apply)
      + tags_all      = (known after apply)
      + zone_id       = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+ test = (known after apply)

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production -w production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fproduction)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d 00_Environment/03_Production -w production`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `00_Environment/03_Production` workspace: `production`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production -w production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fproduction)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d 00_Environment/03_Production -w production`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by rhea-so** [comment]
atlantis unlock

**Comment by AyameNakiri** [comment]
All Atlantis locks for this PR have been unlocked and plans discarded

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `00_Environment/03_Production` workspace: `production`

**Apply Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform apply -input=false \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/92/production/00_Environment/03_Production/production.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/92/production/00_Environment/03_Production": signal: terminated
module.rhea-so.aws_route53_zone.domain: Creating...
module.rhea-so.aws_route53_zone.domain: Still creating... [10s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [20s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [30s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [40s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [50s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [1m0s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [1m10s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [1m20s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [1m30s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [1m40s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [1m50s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [2m0s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [2m10s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [2m20s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [2m30s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [2m40s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [2m50s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [3m0s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [3m10s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [3m20s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [3m30s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [3m40s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [3m50s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [4m0s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [4m10s elapsed]

Interrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...

Stopping operation...

Two interrupts received. Exiting immediately. Note that data loss may have
occurred.

╷
│ Error: operation canceled
│ 
│ 
╵

```
</details>

**Pull request closed without merging**
