### PR TITLE
fix: sg

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # aws_ecs_service.memo-ecs-service will be updated in-place
~ resource "aws_ecs_service" "memo-ecs-service" {
        id                                 = "arn:aws:ecs:ap-northeast-2:264842458097:service/memo-ecs-cluster/memo-ecs-service"
        name                               = "memo-ecs-service"
        tags                               = {}
        # (15 unchanged attributes hidden)




      ~ network_configuration {
          ~ assign_public_ip = false -> true
            # (2 unchanged attributes hidden)
        }
        # (3 unchanged blocks hidden)
    }

  # aws_security_group.memo-security-group will be updated in-place
~ resource "aws_security_group" "memo-security-group" {
        id                     = "sg-06f64f1a2a42dfc63"
      ~ ingress                = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = "HTTP"
              + from_port        = 443
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 443
            },
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = "HTTP"
              + from_port        = 8080
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 8080
            },
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/32",
                ]
              - description      = "HTTP"
              - from_port        = 8080
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 8080
            },
            # (1 unchanged element hidden)
        ]
        name                   = "memo-security-group"
        tags                   = {
            "Name" = "memo-security-group"
        }
        # (7 unchanged attributes hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 0 to add, 2 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
aws_security_group.memo-security-group: Modifying... [id=sg-06f64f1a2a42dfc63]
aws_security_group.memo-security-group: Modifications complete after 0s [id=sg-06f64f1a2a42dfc63]
aws_ecs_service.memo-ecs-service: Modifying... [id=arn:aws:ecs:ap-northeast-2:264842458097:service/memo-ecs-cluster/memo-ecs-service]
aws_ecs_service.memo-ecs-service: Modifications complete after 1s [id=arn:aws:ecs:ap-northeast-2:264842458097:service/memo-ecs-cluster/memo-ecs-service]

Apply complete! Resources: 0 added, 2 changed, 0 destroyed.


```

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
