### PR TITLE
delete: atlantis

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # module.rhea-so.aws_route53_zone.domain has changed
~ resource "aws_route53_zone" "domain" {
        id            = "Z0097287UVNCC6G4O03H"
        name          = "rhea-so.com"
      + tags          = {}
        # (6 unchanged attributes hidden)
    }

  # module.production.module.atlantis-rhea-so.aws_route53_record.domain has changed
~ resource "aws_route53_record" "domain" {
        id              = "Z0097287UVNCC6G4O03H_atlantis.rhea-so.com_A"
        name            = "atlantis.rhea-so.com"
        # (6 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # module.production.module.atlantis-rhea-so.aws_route53_record.domain will be destroyed
  # (because aws_route53_record.domain is not in configuration)
- resource "aws_route53_record" "domain" {
      - allow_overwrite = true -> null
      - fqdn            = "atlantis.rhea-so.com" -> null
      - id              = "Z0097287UVNCC6G4O03H_atlantis.rhea-so.com_A" -> null
      - name            = "atlantis.rhea-so.com" -> null
      - records         = [
          - "52.78.144.248",
        ] -> null
      - ttl             = 300 -> null
      - type            = "A" -> null
      - zone_id         = "Z0097287UVNCC6G4O03H" -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 0 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # module.rhea-so.aws_route53_zone.domain has changed
~ resource "aws_route53_zone" "domain" {
        id            = "Z0097287UVNCC6G4O03H"
        name          = "rhea-so.com"
      + tags          = {}
        # (6 unchanged attributes hidden)
    }

  # module.production.module.atlantis-rhea-so.aws_route53_record.domain has changed
~ resource "aws_route53_record" "domain" {
        id              = "Z0097287UVNCC6G4O03H_atlantis.rhea-so.com_A"
        name            = "atlantis.rhea-so.com"
        # (6 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.rhea-so.aws_route53_zone.domain will be destroyed
  # (because aws_route53_zone.domain is not in configuration)
- resource "aws_route53_zone" "domain" {
      - arn           = "arn:aws:route53:::hostedzone/Z0097287UVNCC6G4O03H" -> null
      - comment       = "Managed by Terraform" -> null
      - force_destroy = false -> null
      - id            = "Z0097287UVNCC6G4O03H" -> null
      - name          = "rhea-so.com" -> null
      - name_servers  = [
          - "ns-1102.awsdns-09.org",
          - "ns-1752.awsdns-27.co.uk",
          - "ns-43.awsdns-05.com",
          - "ns-654.awsdns-17.net",
        ] -> null
      - tags          = {} -> null
      - tags_all      = {} -> null
      - zone_id       = "Z0097287UVNCC6G4O03H" -> null
    }

  # module.production.module.atlantis-rhea-so.aws_route53_record.domain must be replaced
-/+ resource "aws_route53_record" "domain" {
      ~ fqdn            = "atlantis.rhea-so.com" -> (known after apply)
      ~ id              = "Z0097287UVNCC6G4O03H_atlantis.rhea-so.com_A" -> (known after apply)
        name            = "atlantis.rhea-so.com"
      ~ zone_id         = "Z0097287UVNCC6G4O03H" -> "module.rhea-so.zone_id" # forces replacement
        # (4 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 2 to destroy.
Releasing state lock. This may take a few moments...

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 1 to add, 0 to change, 2 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # module.rhea-so.aws_route53_zone.domain has changed
~ resource "aws_route53_zone" "domain" {
        id            = "Z0097287UVNCC6G4O03H"
        name          = "rhea-so.com"
      + tags          = {}
        # (6 unchanged attributes hidden)
    }

  # module.production.module.atlantis-rhea-so.aws_route53_record.domain has changed
~ resource "aws_route53_record" "domain" {
        id              = "Z0097287UVNCC6G4O03H_atlantis.rhea-so.com_A"
        name            = "atlantis.rhea-so.com"
        # (6 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # module.production.module.atlantis-rhea-so.aws_route53_record.domain will be destroyed
  # (because aws_route53_record.domain is not in configuration)
- resource "aws_route53_record" "domain" {
      - allow_overwrite = true -> null
      - fqdn            = "atlantis.rhea-so.com" -> null
      - id              = "Z0097287UVNCC6G4O03H_atlantis.rhea-so.com_A" -> null
      - name            = "atlantis.rhea-so.com" -> null
      - records         = [
          - "52.78.144.248",
        ] -> null
      - ttl             = 300 -> null
      - type            = "A" -> null
      - zone_id         = "Z0097287UVNCC6G4O03H" -> null
    }

  # module.production.module.production-vpc.aws_vpc.vpc will be destroyed
  # (because aws_vpc.vpc is not in configuration)
- resource "aws_vpc" "vpc" {
      - arn                              = "arn:aws:ec2:ap-northeast-2:264842458097:vpc/vpc-065f63385559fb8ee" -> null
      - assign_generated_ipv6_cidr_block = false -> null
      - cidr_block                       = "10.0.0.0/16" -> null
      - default_network_acl_id           = "acl-03486df82c02f741c" -> null
      - default_route_table_id           = "rtb-01dabacb03277fcac" -> null
      - default_security_group_id        = "sg-08b165e24ed78f7c5" -> null
      - dhcp_options_id                  = "dopt-0439dc969e8731205" -> null
      - enable_classiclink               = false -> null
      - enable_classiclink_dns_support   = false -> null
      - enable_dns_hostnames             = false -> null
      - enable_dns_support               = true -> null
      - id                               = "vpc-065f63385559fb8ee" -> null
      - instance_tenancy                 = "default" -> null
      - ipv6_netmask_length              = 0 -> null
      - main_route_table_id              = "rtb-01dabacb03277fcac" -> null
      - owner_id                         = "264842458097" -> null
      - tags                             = {
          - "Name" = "production-vpc"
        } -> null
      - tags_all                         = {
          - "Name" = "production-vpc"
        } -> null
    }

Plan: 0 to add, 0 to change, 2 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 0 to add, 0 to change, 2 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis plan

**Comment by AyameNakiri** [comment]
Ran Plan for 0 projects:

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for 0 projects:

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
