### PR TITLE
delete: exmaple

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `00_Environment/03_Production` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.atlantis-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "atlantis.rhea-so.com"
      + records         = [
          + "52.78.144.248",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

  # module.google-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "google.rhea-so.com"
      + records         = [
          + "172.217.31.174",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

  # module.rhea-so.aws_route53_zone.domain will be created
+ resource "aws_route53_zone" "domain" {
      + arn           = (known after apply)
      + comment       = "Managed by Terraform"
      + force_destroy = true
      + id            = (known after apply)
      + name          = "rhea-so.com"
      + name_servers  = (known after apply)
      + tags_all      = (known after apply)
      + zone_id       = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d 00_Environment/03_Production`
</details>
Plan: 3 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `00_Environment/03_Production` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d 00_Environment/03_Production`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
**Plan Error**
```
parsing atlantis.yaml: version: is required. If you've just upgraded Atlantis you need to rewrite your atlantis.yaml for version 3. See www.runatlantis.io/docs/upgrading-atlantis-yaml.html.
```

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `00_Environment/03_Production` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.atlantis-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "atlantis.rhea-so.com"
      + records         = [
          + "52.78.144.248",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

  # module.google-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "google.rhea-so.com"
      + records         = [
          + "172.217.31.174",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

  # module.rhea-so.aws_route53_zone.domain will be created
+ resource "aws_route53_zone" "domain" {
      + arn           = (known after apply)
      + comment       = "Managed by Terraform"
      + force_destroy = true
      + id            = (known after apply)
      + name          = "rhea-so.com"
      + name_servers  = (known after apply)
      + tags_all      = (known after apply)
      + zone_id       = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d 00_Environment/03_Production`
</details>
Plan: 3 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `00_Environment/03_Production` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d 00_Environment/03_Production`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `00_Environment/03_Production` workspace: `default`

<details><summary>Show Output</summary>

```diff
module.rhea-so.aws_route53_zone.domain: Creating...
module.rhea-so.aws_route53_zone.domain: Still creating... [10s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [20s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [30s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [40s elapsed]
module.rhea-so.aws_route53_zone.domain: Creation complete after 41s [id=Z064734839OVGZ55CREBF]
module.google-rhea-so.aws_route53_record.domain: Creating...
module.atlantis-rhea-so.aws_route53_record.domain: Creating...
module.google-rhea-so.aws_route53_record.domain: Still creating... [10s elapsed]
module.atlantis-rhea-so.aws_route53_record.domain: Still creating... [10s elapsed]
module.google-rhea-so.aws_route53_record.domain: Still creating... [20s elapsed]
module.atlantis-rhea-so.aws_route53_record.domain: Still creating... [20s elapsed]
module.atlantis-rhea-so.aws_route53_record.domain: Still creating... [30s elapsed]
module.google-rhea-so.aws_route53_record.domain: Still creating... [30s elapsed]
module.google-rhea-so.aws_route53_record.domain: Creation complete after 40s [id=Z064734839OVGZ55CREBF_google.rhea-so.com_A]
module.atlantis-rhea-so.aws_route53_record.domain: Still creating... [40s elapsed]
module.atlantis-rhea-so.aws_route53_record.domain: Creation complete after 41s [id=Z064734839OVGZ55CREBF_atlantis.rhea-so.com_A]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.


```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `00_Environment/03_Production` workspace: `default`

**Pull request merged**
