### PR TITLE
fix: health check

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/bin/terraform plan -input=false -refresh -out \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/42/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/42/default": exit status 1
╷
│ Error: expected health_check.0.timeout to be in the range (2 - 120), got 1
│ 
│   with aws_lb_target_group.memo-alb-target-group,
│   on memo.tf line 123, in resource "aws_lb_target_group" "memo-alb-target-group":
│  123:     timeout             = 1
│ 
╵

```

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_ecs_task_definition.memo-ecs-task-definition has changed
~ resource "aws_ecs_task_definition" "memo-ecs-task-definition" {
        id                       = "memo-ecs-task-definition"
      + tags                     = {}
        # (11 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # aws_lb_target_group.memo-alb-target-group will be updated in-place
~ resource "aws_lb_target_group" "memo-alb-target-group" {
        id                                 = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/b7b417f7555897a6"
        name                               = "memo-alb-target-group"
        tags                               = {}
        # (14 unchanged attributes hidden)

      ~ health_check {
          ~ interval            = 300 -> 10
          ~ timeout             = 60 -> 2
            # (7 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 0 to add, 1 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
aws_lb_target_group.memo-alb-target-group: Modifying... [id=arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/b7b417f7555897a6]
aws_lb_target_group.memo-alb-target-group: Modifications complete after 0s [id=arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/b7b417f7555897a6]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.


```

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
