### PR TITLE
fix: Naming

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `Example` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform plan -input=false -refresh -out \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/84/default/Example/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/84/default/Example": exit status 1
╷
│ Error: Reference to undeclared resource
│ 
│   on main.tf line 7, in resource "aws_db_subnet_group" "iac-db-subnet-group":
│    7:     aws_subnet.iac-subnet-1.id,
│ 
│ A managed resource "aws_subnet" "iac-subnet-1" has not been declared in the
│ root module.
╵
╷
│ Error: Reference to undeclared resource
│ 
│   on main.tf line 8, in resource "aws_db_subnet_group" "iac-db-subnet-group":
│    8:     aws_subnet.iac-subnet-2.id
│ 
│ A managed resource "aws_subnet" "iac-subnet-2" has not been declared in the
│ root module.
╵

```
</details>

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `Example` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_db_subnet_group.iac-db-subnet-group will be created
+ resource "aws_db_subnet_group" "iac-db-subnet-group" {
      + arn         = (known after apply)
      + description = "Managed by Terraform"
      + id          = (known after apply)
      + name        = "iac-db-subnet-group"
      + name_prefix = (known after apply)
      + subnet_ids  = (known after apply)
      + tags        = {
          + "Name" = "iac-db-subnet-group"
        }
      + tags_all    = {
          + "Name" = "iac-db-subnet-group"
        }
    }

  # aws_internet_gateway.iac-igw will be created
+ resource "aws_internet_gateway" "iac-igw" {
      + arn      = (known after apply)
      + id       = (known after apply)
      + owner_id = (known after apply)
      + tags     = {
          + "Name" = "iac-igw"
        }
      + tags_all = {
          + "Name" = "iac-igw"
        }
      + vpc_id   = (known after apply)
    }

  # aws_rds_cluster.iac-rds-cluster will be created
+ resource "aws_rds_cluster" "iac-rds-cluster" {
      + apply_immediately               = (known after apply)
      + arn                             = (known after apply)
      + availability_zones              = [
          + "ap-northeast-2a",
          + "ap-northeast-2b",
          + "ap-northeast-2c",
        ]
      + backup_retention_period         = 5
      + cluster_identifier              = "iac-rds-cluster"
      + cluster_identifier_prefix       = (known after apply)
      + cluster_members                 = (known after apply)
      + cluster_resource_id             = (known after apply)
      + copy_tags_to_snapshot           = false
      + database_name                   = "iac-rds"
      + db_cluster_parameter_group_name = (known after apply)
      + db_subnet_group_name            = "iac-db-subnet-group"
      + enable_global_write_forwarding  = false
      + enable_http_endpoint            = false
      + endpoint                        = (known after apply)
      + engine                          = "aurora"
      + engine_mode                     = "provisioned"
      + engine_version                  = (known after apply)
      + engine_version_actual           = (known after apply)
      + hosted_zone_id                  = (known after apply)
      + iam_roles                       = (known after apply)
      + id                              = (known after apply)
      + kms_key_id                      = (known after apply)
      + master_password                 = (sensitive value)
      + master_username                 = "rheaso"
      + port                            = (known after apply)
      + preferred_backup_window         = "07:00-09:00"
      + preferred_maintenance_window    = (known after apply)
      + reader_endpoint                 = (known after apply)
      + skip_final_snapshot             = false
      + storage_encrypted               = (known after apply)
      + tags_all                        = (known after apply)
      + vpc_security_group_ids          = (known after apply)
    }

  # aws_rds_cluster_instance.iac-rds-cluster-instance-1 will be created
+ resource "aws_rds_cluster_instance" "iac-rds-cluster-instance-1" {
      + apply_immediately                     = true
      + arn                                   = (known after apply)
      + auto_minor_version_upgrade            = true
      + availability_zone                     = (known after apply)
      + ca_cert_identifier                    = (known after apply)
      + cluster_identifier                    = (known after apply)
      + copy_tags_to_snapshot                 = false
      + db_parameter_group_name               = (known after apply)
      + db_subnet_group_name                  = "iac-db-subnet-group"
      + dbi_resource_id                       = (known after apply)
      + endpoint                              = (known after apply)
      + engine                                = "aurora"
      + engine_version                        = (known after apply)
      + engine_version_actual                 = (known after apply)
      + id                                    = (known after apply)
      + identifier                            = "iac-rds-cluster-instance-1"
      + identifier_prefix                     = (known after apply)
      + instance_class                        = "db.t3.small"
      + kms_key_id                            = (known after apply)
      + monitoring_interval                   = 0
      + monitoring_role_arn                   = (known after apply)
      + performance_insights_enabled          = (known after apply)
      + performance_insights_kms_key_id       = (known after apply)
      + performance_insights_retention_period = (known after apply)
      + port                                  = (known after apply)
      + preferred_backup_window               = (known after apply)
      + preferred_maintenance_window          = (known after apply)
      + promotion_tier                        = 0
      + publicly_accessible                   = true
      + storage_encrypted                     = (known after apply)
      + tags_all                              = (known after apply)
      + writer                                = (known after apply)
    }

  # aws_rds_cluster_instance.iac-rds-cluster-instance-2 will be created
+ resource "aws_rds_cluster_instance" "iac-rds-cluster-instance-2" {
      + apply_immediately                     = true
      + arn                                   = (known after apply)
      + auto_minor_version_upgrade            = true
      + availability_zone                     = (known after apply)
      + ca_cert_identifier                    = (known after apply)
      + cluster_identifier                    = (known after apply)
      + copy_tags_to_snapshot                 = false
      + db_parameter_group_name               = (known after apply)
      + db_subnet_group_name                  = "iac-db-subnet-group"
      + dbi_resource_id                       = (known after apply)
      + endpoint                              = (known after apply)
      + engine                                = "aurora"
      + engine_version                        = (known after apply)
      + engine_version_actual                 = (known after apply)
      + id                                    = (known after apply)
      + identifier                            = "iac-rds-cluster-instance-2"
      + identifier_prefix                     = (known after apply)
      + instance_class                        = "db.t3.small"
      + kms_key_id                            = (known after apply)
      + monitoring_interval                   = 0
      + monitoring_role_arn                   = (known after apply)
      + performance_insights_enabled          = (known after apply)
      + performance_insights_kms_key_id       = (known after apply)
      + performance_insights_retention_period = (known after apply)
      + port                                  = (known after apply)
      + preferred_backup_window               = (known after apply)
      + preferred_maintenance_window          = (known after apply)
      + promotion_tier                        = 0
      + publicly_accessible                   = true
      + storage_encrypted                     = (known after apply)
      + tags_all                              = (known after apply)
      + writer                                = (known after apply)
    }

  # aws_route_table.iac-routing-table will be created
+ resource "aws_route_table" "iac-routing-table" {
      + arn              = (known after apply)
      + id               = (known after apply)
      + owner_id         = (known after apply)
      + propagating_vgws = (known after apply)
      + route            = [
          + {
              + carrier_gateway_id         = ""
              + cidr_block                 = "0.0.0.0/0"
              + destination_prefix_list_id = ""
              + egress_only_gateway_id     = ""
              + gateway_id                 = (known after apply)
              + instance_id                = ""
              + ipv6_cidr_block            = ""
              + local_gateway_id           = ""
              + nat_gateway_id             = ""
              + network_interface_id       = ""
              + transit_gateway_id         = ""
              + vpc_endpoint_id            = ""
              + vpc_peering_connection_id  = ""
            },
        ]
      + tags             = {
          + "Name" = "iac-routing-table"
        }
      + tags_all         = {
          + "Name" = "iac-routing-table"
        }
      + vpc_id           = (known after apply)
    }

  # aws_route_table_association.iac-routing-table-association-1 will be created
+ resource "aws_route_table_association" "iac-routing-table-association-1" {
      + id             = (known after apply)
      + route_table_id = (known after apply)
      + subnet_id      = (known after apply)
    }

  # aws_route_table_association.iac-routing-table-association-2 will be created
+ resource "aws_route_table_association" "iac-routing-table-association-2" {
      + id             = (known after apply)
      + route_table_id = (known after apply)
      + subnet_id      = (known after apply)
    }

  # aws_subnet.iac-subnet-1 will be created
+ resource "aws_subnet" "iac-subnet-1" {
      + arn                                            = (known after apply)
      + assign_ipv6_address_on_creation                = false
      + availability_zone                              = "ap-northeast-2a"
      + availability_zone_id                           = (known after apply)
      + cidr_block                                     = "10.0.3.0/24"
      + enable_dns64                                   = false
      + enable_resource_name_dns_a_record_on_launch    = false
      + enable_resource_name_dns_aaaa_record_on_launch = false
      + id                                             = (known after apply)
      + ipv6_cidr_block_association_id                 = (known after apply)
      + ipv6_native                                    = false
      + map_public_ip_on_launch                        = false
      + owner_id                                       = (known after apply)
      + private_dns_hostname_type_on_launch            = (known after apply)
      + tags                                           = {
          + "Name" = "iac-subnet-1"
        }
      + tags_all                                       = {
          + "Name" = "iac-subnet-1"
        }
      + vpc_id                                         = (known after apply)
    }

  # aws_subnet.iac-subnet-2 will be created
+ resource "aws_subnet" "iac-subnet-2" {
      + arn                                            = (known after apply)
      + assign_ipv6_address_on_creation                = false
      + availability_zone                              = "ap-northeast-2c"
      + availability_zone_id                           = (known after apply)
      + cidr_block                                     = "10.0.4.0/24"
      + enable_dns64                                   = false
      + enable_resource_name_dns_a_record_on_launch    = false
      + enable_resource_name_dns_aaaa_record_on_launch = false
      + id                                             = (known after apply)
      + ipv6_cidr_block_association_id                 = (known after apply)
      + ipv6_native                                    = false
      + map_public_ip_on_launch                        = false
      + owner_id                                       = (known after apply)
      + private_dns_hostname_type_on_launch            = (known after apply)
      + tags                                           = {
          + "Name" = "iac-subnet-2"
        }
      + tags_all                                       = {
          + "Name" = "iac-subnet-2"
        }
      + vpc_id                                         = (known after apply)
    }

  # aws_vpc.iac-vpc will be created
+ resource "aws_vpc" "iac-vpc" {
      + arn                                  = (known after apply)
      + cidr_block                           = "10.0.0.0/16"
      + default_network_acl_id               = (known after apply)
      + default_route_table_id               = (known after apply)
      + default_security_group_id            = (known after apply)
      + dhcp_options_id                      = (known after apply)
      + enable_classiclink                   = (known after apply)
      + enable_classiclink_dns_support       = (known after apply)
      + enable_dns_hostnames                 = (known after apply)
      + enable_dns_support                   = true
      + id                                   = (known after apply)
      + instance_tenancy                     = "default"
      + ipv6_association_id                  = (known after apply)
      + ipv6_cidr_block                      = (known after apply)
      + ipv6_cidr_block_network_border_group = (known after apply)
      + main_route_table_id                  = (known after apply)
      + owner_id                             = (known after apply)
      + tags                                 = {
          + "Name" = "iac-vpc"
        }
      + tags_all                             = {
          + "Name" = "iac-vpc"
        }
    }

Plan: 11 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+ iac-rds = (known after apply)

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d Example`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252FExample%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d Example`
</details>
Plan: 11 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `Example` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d Example`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252FExample%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d Example`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `Example` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform apply -input=false \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/84/default/Example/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/84/default/Example": exit status 1
aws_vpc.iac-vpc: Creating...
aws_vpc.iac-vpc: Creation complete after 1s [id=vpc-0d0a053539a93e75d]
aws_internet_gateway.iac-igw: Creating...
aws_subnet.iac-subnet-1: Creating...
aws_subnet.iac-subnet-2: Creating...
aws_internet_gateway.iac-igw: Creation complete after 1s [id=igw-032af43ab25ea0751]
aws_route_table.iac-routing-table: Creating...
aws_subnet.iac-subnet-2: Creation complete after 1s [id=subnet-01625c9cf0664c266]
aws_subnet.iac-subnet-1: Creation complete after 1s [id=subnet-082ceb5b9b0d12404]
aws_db_subnet_group.iac-db-subnet-group: Creating...
aws_route_table.iac-routing-table: Creation complete after 0s [id=rtb-00372486cd1c42736]
aws_route_table_association.iac-routing-table-association-2: Creating...
aws_route_table_association.iac-routing-table-association-1: Creating...
aws_route_table_association.iac-routing-table-association-1: Creation complete after 0s [id=rtbassoc-0408634e53ba2c24e]
aws_route_table_association.iac-routing-table-association-2: Creation complete after 0s [id=rtbassoc-0e9458e2b9c9e81f7]
aws_db_subnet_group.iac-db-subnet-group: Creation complete after 0s [id=iac-db-subnet-group]
aws_rds_cluster.iac-rds-cluster: Creating...
╷
│ Error: error creating RDS cluster: InvalidVPCNetworkStateFault: Availability zone '[ap-northeast-2b]' is unavailable in this region, please choose another zone set.
│ 	status code: 400, request id: cb7684a8-acdb-49f1-b6f2-e2fdc31e81a2
│ 
│   with aws_rds_cluster.iac-rds-cluster,
│   on main.tf line 79, in resource "aws_rds_cluster" "iac-rds-cluster":
│   79: resource "aws_rds_cluster" "iac-rds-cluster" {
│ 
╵

```
</details>

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `Example` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_db_subnet_group.iac-db-subnet-group will be created
+ resource "aws_db_subnet_group" "iac-db-subnet-group" {
      + arn         = (known after apply)
      + description = "Managed by Terraform"
      + id          = (known after apply)
      + name        = "iac-db-subnet-group"
      + name_prefix = (known after apply)
      + subnet_ids  = (known after apply)
      + tags        = {
          + "Name" = "iac-db-subnet-group"
        }
      + tags_all    = {
          + "Name" = "iac-db-subnet-group"
        }
    }

  # aws_internet_gateway.iac-igw will be created
+ resource "aws_internet_gateway" "iac-igw" {
      + arn      = (known after apply)
      + id       = (known after apply)
      + owner_id = (known after apply)
      + tags     = {
          + "Name" = "iac-igw"
        }
      + tags_all = {
          + "Name" = "iac-igw"
        }
      + vpc_id   = (known after apply)
    }

  # aws_rds_cluster.iac-rds-cluster will be created
+ resource "aws_rds_cluster" "iac-rds-cluster" {
      + apply_immediately               = (known after apply)
      + arn                             = (known after apply)
      + availability_zones              = [
          + "ap-northeast-2a",
          + "ap-northeast-2c",
        ]
      + backup_retention_period         = 5
      + cluster_identifier              = "iac-rds-cluster"
      + cluster_identifier_prefix       = (known after apply)
      + cluster_members                 = (known after apply)
      + cluster_resource_id             = (known after apply)
      + copy_tags_to_snapshot           = false
      + database_name                   = "iac-rds"
      + db_cluster_parameter_group_name = (known after apply)
      + db_subnet_group_name            = "iac-db-subnet-group"
      + enable_global_write_forwarding  = false
      + enable_http_endpoint            = false
      + endpoint                        = (known after apply)
      + engine                          = "aurora"
      + engine_mode                     = "provisioned"
      + engine_version                  = (known after apply)
      + engine_version_actual           = (known after apply)
      + hosted_zone_id                  = (known after apply)
      + iam_roles                       = (known after apply)
      + id                              = (known after apply)
      + kms_key_id                      = (known after apply)
      + master_password                 = (sensitive value)
      + master_username                 = "rheaso"
      + port                            = (known after apply)
      + preferred_backup_window         = "07:00-09:00"
      + preferred_maintenance_window    = (known after apply)
      + reader_endpoint                 = (known after apply)
      + skip_final_snapshot             = false
      + storage_encrypted               = (known after apply)
      + tags_all                        = (known after apply)
      + vpc_security_group_ids          = (known after apply)
    }

  # aws_rds_cluster_instance.iac-rds-cluster-instance-1 will be created
+ resource "aws_rds_cluster_instance" "iac-rds-cluster-instance-1" {
      + apply_immediately                     = true
      + arn                                   = (known after apply)
      + auto_minor_version_upgrade            = true
      + availability_zone                     = (known after apply)
      + ca_cert_identifier                    = (known after apply)
      + cluster_identifier                    = (known after apply)
      + copy_tags_to_snapshot                 = false
      + db_parameter_group_name               = (known after apply)
      + db_subnet_group_name                  = "iac-db-subnet-group"
      + dbi_resource_id                       = (known after apply)
      + endpoint                              = (known after apply)
      + engine                                = "aurora"
      + engine_version                        = (known after apply)
      + engine_version_actual                 = (known after apply)
      + id                                    = (known after apply)
      + identifier                            = "iac-rds-cluster-instance-1"
      + identifier_prefix                     = (known after apply)
      + instance_class                        = "db.t3.small"
      + kms_key_id                            = (known after apply)
      + monitoring_interval                   = 0
      + monitoring_role_arn                   = (known after apply)
      + performance_insights_enabled          = (known after apply)
      + performance_insights_kms_key_id       = (known after apply)
      + performance_insights_retention_period = (known after apply)
      + port                                  = (known after apply)
      + preferred_backup_window               = (known after apply)
      + preferred_maintenance_window          = (known after apply)
      + promotion_tier                        = 0
      + publicly_accessible                   = true
      + storage_encrypted                     = (known after apply)
      + tags_all                              = (known after apply)
      + writer                                = (known after apply)
    }

  # aws_rds_cluster_instance.iac-rds-cluster-instance-2 will be created
+ resource "aws_rds_cluster_instance" "iac-rds-cluster-instance-2" {
      + apply_immediately                     = true
      + arn                                   = (known after apply)
      + auto_minor_version_upgrade            = true
      + availability_zone                     = (known after apply)
      + ca_cert_identifier                    = (known after apply)
      + cluster_identifier                    = (known after apply)
      + copy_tags_to_snapshot                 = false
      + db_parameter_group_name               = (known after apply)
      + db_subnet_group_name                  = "iac-db-subnet-group"
      + dbi_resource_id                       = (known after apply)
      + endpoint                              = (known after apply)
      + engine                                = "aurora"
      + engine_version                        = (known after apply)
      + engine_version_actual                 = (known after apply)
      + id                                    = (known after apply)
      + identifier                            = "iac-rds-cluster-instance-2"
      + identifier_prefix                     = (known after apply)
      + instance_class                        = "db.t3.small"
      + kms_key_id                            = (known after apply)
      + monitoring_interval                   = 0
      + monitoring_role_arn                   = (known after apply)
      + performance_insights_enabled          = (known after apply)
      + performance_insights_kms_key_id       = (known after apply)
      + performance_insights_retention_period = (known after apply)
      + port                                  = (known after apply)
      + preferred_backup_window               = (known after apply)
      + preferred_maintenance_window          = (known after apply)
      + promotion_tier                        = 0
      + publicly_accessible                   = true
      + storage_encrypted                     = (known after apply)
      + tags_all                              = (known after apply)
      + writer                                = (known after apply)
    }

  # aws_route_table.iac-routing-table will be created
+ resource "aws_route_table" "iac-routing-table" {
      + arn              = (known after apply)
      + id               = (known after apply)
      + owner_id         = (known after apply)
      + propagating_vgws = (known after apply)
      + route            = [
          + {
              + carrier_gateway_id         = ""
              + cidr_block                 = "0.0.0.0/0"
              + destination_prefix_list_id = ""
              + egress_only_gateway_id     = ""
              + gateway_id                 = (known after apply)
              + instance_id                = ""
              + ipv6_cidr_block            = ""
              + local_gateway_id           = ""
              + nat_gateway_id             = ""
              + network_interface_id       = ""
              + transit_gateway_id         = ""
              + vpc_endpoint_id            = ""
              + vpc_peering_connection_id  = ""
            },
        ]
      + tags             = {
          + "Name" = "iac-routing-table"
        }
      + tags_all         = {
          + "Name" = "iac-routing-table"
        }
      + vpc_id           = (known after apply)
    }

  # aws_route_table_association.iac-routing-table-association-1 will be created
+ resource "aws_route_table_association" "iac-routing-table-association-1" {
      + id             = (known after apply)
      + route_table_id = (known after apply)
      + subnet_id      = (known after apply)
    }

  # aws_route_table_association.iac-routing-table-association-2 will be created
+ resource "aws_route_table_association" "iac-routing-table-association-2" {
      + id             = (known after apply)
      + route_table_id = (known after apply)
      + subnet_id      = (known after apply)
    }

  # aws_subnet.iac-subnet-1 will be created
+ resource "aws_subnet" "iac-subnet-1" {
      + arn                                            = (known after apply)
      + assign_ipv6_address_on_creation                = false
      + availability_zone                              = "ap-northeast-2a"
      + availability_zone_id                           = (known after apply)
      + cidr_block                                     = "10.0.3.0/24"
      + enable_dns64                                   = false
      + enable_resource_name_dns_a_record_on_launch    = false
      + enable_resource_name_dns_aaaa_record_on_launch = false
      + id                                             = (known after apply)
      + ipv6_cidr_block_association_id                 = (known after apply)
      + ipv6_native                                    = false
      + map_public_ip_on_launch                        = false
      + owner_id                                       = (known after apply)
      + private_dns_hostname_type_on_launch            = (known after apply)
      + tags                                           = {
          + "Name" = "iac-subnet-1"
        }
      + tags_all                                       = {
          + "Name" = "iac-subnet-1"
        }
      + vpc_id                                         = (known after apply)
    }

  # aws_subnet.iac-subnet-2 will be created
+ resource "aws_subnet" "iac-subnet-2" {
      + arn                                            = (known after apply)
      + assign_ipv6_address_on_creation                = false
      + availability_zone                              = "ap-northeast-2c"
      + availability_zone_id                           = (known after apply)
      + cidr_block                                     = "10.0.4.0/24"
      + enable_dns64                                   = false
      + enable_resource_name_dns_a_record_on_launch    = false
      + enable_resource_name_dns_aaaa_record_on_launch = false
      + id                                             = (known after apply)
      + ipv6_cidr_block_association_id                 = (known after apply)
      + ipv6_native                                    = false
      + map_public_ip_on_launch                        = false
      + owner_id                                       = (known after apply)
      + private_dns_hostname_type_on_launch            = (known after apply)
      + tags                                           = {
          + "Name" = "iac-subnet-2"
        }
      + tags_all                                       = {
          + "Name" = "iac-subnet-2"
        }
      + vpc_id                                         = (known after apply)
    }

  # aws_vpc.iac-vpc will be created
+ resource "aws_vpc" "iac-vpc" {
      + arn                                  = (known after apply)
      + cidr_block                           = "10.0.0.0/16"
      + default_network_acl_id               = (known after apply)
      + default_route_table_id               = (known after apply)
      + default_security_group_id            = (known after apply)
      + dhcp_options_id                      = (known after apply)
      + enable_classiclink                   = (known after apply)
      + enable_classiclink_dns_support       = (known after apply)
      + enable_dns_hostnames                 = (known after apply)
      + enable_dns_support                   = true
      + id                                   = (known after apply)
      + instance_tenancy                     = "default"
      + ipv6_association_id                  = (known after apply)
      + ipv6_cidr_block                      = (known after apply)
      + ipv6_cidr_block_network_border_group = (known after apply)
      + main_route_table_id                  = (known after apply)
      + owner_id                             = (known after apply)
      + tags                                 = {
          + "Name" = "iac-vpc"
        }
      + tags_all                             = {
          + "Name" = "iac-vpc"
        }
    }

Plan: 11 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+ iac-rds = (known after apply)

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d Example`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252FExample%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d Example`
</details>
Plan: 11 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `Example` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d Example`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252FExample%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d Example`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `Example` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform apply -input=false \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/84/default/Example/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/84/default/Example": exit status 1
aws_vpc.iac-vpc: Creating...
aws_vpc.iac-vpc: Creation complete after 1s [id=vpc-03b53bfcb2e0ed456]
aws_subnet.iac-subnet-2: Creating...
aws_internet_gateway.iac-igw: Creating...
aws_subnet.iac-subnet-1: Creating...
aws_internet_gateway.iac-igw: Creation complete after 0s [id=igw-0d36834471f3317e1]
aws_route_table.iac-routing-table: Creating...
aws_subnet.iac-subnet-2: Creation complete after 0s [id=subnet-0920a7c445e2b0926]
aws_subnet.iac-subnet-1: Creation complete after 0s [id=subnet-0179ec32eea79e76b]
aws_db_subnet_group.iac-db-subnet-group: Creating...
aws_route_table.iac-routing-table: Creation complete after 0s [id=rtb-000838e6c86c10173]
aws_route_table_association.iac-routing-table-association-2: Creating...
aws_route_table_association.iac-routing-table-association-1: Creating...
aws_route_table_association.iac-routing-table-association-2: Creation complete after 1s [id=rtbassoc-0700f872503b66efc]
aws_route_table_association.iac-routing-table-association-1: Still creating... [10s elapsed]
aws_route_table_association.iac-routing-table-association-1: Still creating... [20s elapsed]
aws_route_table_association.iac-routing-table-association-1: Still creating... [30s elapsed]
aws_route_table_association.iac-routing-table-association-1: Still creating... [40s elapsed]
aws_route_table_association.iac-routing-table-association-1: Still creating... [50s elapsed]
aws_route_table_association.iac-routing-table-association-1: Still creating... [1m0s elapsed]
aws_route_table_association.iac-routing-table-association-1: Still creating... [1m10s elapsed]
aws_route_table_association.iac-routing-table-association-1: Still creating... [1m20s elapsed]
aws_route_table_association.iac-routing-table-association-1: Still creating... [1m30s elapsed]
aws_route_table_association.iac-routing-table-association-1: Still creating... [1m40s elapsed]
aws_route_table_association.iac-routing-table-association-1: Still creating... [1m50s elapsed]
aws_route_table_association.iac-routing-table-association-1: Still creating... [2m0s elapsed]
aws_route_table_association.iac-routing-table-association-1: Still creating... [2m10s elapsed]
aws_route_table_association.iac-routing-table-association-1: Still creating... [2m20s elapsed]
aws_route_table_association.iac-routing-table-association-1: Still creating... [2m30s elapsed]
aws_route_table_association.iac-routing-table-association-1: Still creating... [2m40s elapsed]
aws_route_table_association.iac-routing-table-association-1: Creation complete after 2m44s [id=rtbassoc-064926238f8bbf54f]
╷
│ Error: Error creating DB Subnet Group: DBSubnetGroupAlreadyExists: The DB subnet group 'iac-db-subnet-group' already exists.
│ 	status code: 400, request id: a3a2d6fe-24cd-4468-9294-50c796789f43
│ 
│   with aws_db_subnet_group.iac-db-subnet-group,
│   on main.tf line 65, in resource "aws_db_subnet_group" "iac-db-subnet-group":
│   65: resource "aws_db_subnet_group" "iac-db-subnet-group" {
│ 
╵

```
</details>

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `Example` workspace: `default`

```diff

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d Example`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252FExample%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d Example`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `Example` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d Example`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252FExample%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d Example`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `Example` workspace: `default`

```diff

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.


```

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `Example` workspace: `default`

**Pull request merged**
