### PR TITLE
test: api gateway address

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `Example` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_api_gateway_integration.integration will be created
+ resource "aws_api_gateway_integration" "integration" {
      + cache_namespace         = (known after apply)
      + connection_type         = "INTERNET"
      + http_method             = "GET"
      + id                      = (known after apply)
      + integration_http_method = "GET"
      + passthrough_behavior    = (known after apply)
      + resource_id             = (known after apply)
      + rest_api_id             = (known after apply)
      + timeout_milliseconds    = 29000
      + type                    = "HTTP_PROXY"
      + uri                     = "http://google.com"
    }

  # aws_api_gateway_method.iac-api-gateway-method-google-enter will be created
+ resource "aws_api_gateway_method" "iac-api-gateway-method-google-enter" {
      + api_key_required = false
      + authorization    = "NONE"
      + http_method      = "GET"
      + id               = (known after apply)
      + resource_id      = (known after apply)
      + rest_api_id      = (known after apply)
    }

  # aws_api_gateway_resource.iac-api-gateway-resource-google will be created
+ resource "aws_api_gateway_resource" "iac-api-gateway-resource-google" {
      + id          = (known after apply)
      + parent_id   = (known after apply)
      + path        = (known after apply)
      + path_part   = "google"
      + rest_api_id = (known after apply)
    }

  # aws_api_gateway_resource.iac-api-gateway-resource-google-enter will be created
+ resource "aws_api_gateway_resource" "iac-api-gateway-resource-google-enter" {
      + id          = (known after apply)
      + parent_id   = (known after apply)
      + path        = (known after apply)
      + path_part   = "enter"
      + rest_api_id = (known after apply)
    }

  # aws_api_gateway_rest_api.iac-api-gateway will be created
+ resource "aws_api_gateway_rest_api" "iac-api-gateway" {
      + api_key_source               = (known after apply)
      + arn                          = (known after apply)
      + binary_media_types           = (known after apply)
      + created_date                 = (known after apply)
      + description                  = "Proxy to handle requests to our API"
      + disable_execute_api_endpoint = (known after apply)
      + execution_arn                = (known after apply)
      + id                           = (known after apply)
      + minimum_compression_size     = -1
      + name                         = "iac-api-gateway"
      + policy                       = (known after apply)
      + root_resource_id             = (known after apply)
      + tags_all                     = (known after apply)

      + endpoint_configuration {
          + types            = (known after apply)
          + vpc_endpoint_ids = (known after apply)
        }
    }

Plan: 5 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+ iac-api-gateway = (known after apply)

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d Example`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252FExample%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d Example`
</details>
Plan: 5 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `Example` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d Example`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252FExample%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d Example`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `Example` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_api_gateway_integration.iac-api-gateway-integration will be created
+ resource "aws_api_gateway_integration" "iac-api-gateway-integration" {
      + cache_namespace         = (known after apply)
      + connection_type         = "INTERNET"
      + http_method             = "GET"
      + id                      = (known after apply)
      + integration_http_method = "GET"
      + passthrough_behavior    = (known after apply)
      + resource_id             = (known after apply)
      + rest_api_id             = (known after apply)
      + timeout_milliseconds    = 29000
      + type                    = "HTTP_PROXY"
      + uri                     = "http://google.com"
    }

  # aws_api_gateway_method.iac-api-gateway-method-google-enter will be created
+ resource "aws_api_gateway_method" "iac-api-gateway-method-google-enter" {
      + api_key_required = false
      + authorization    = "NONE"
      + http_method      = "GET"
      + id               = (known after apply)
      + resource_id      = (known after apply)
      + rest_api_id      = (known after apply)
    }

  # aws_api_gateway_resource.iac-api-gateway-resource-google will be created
+ resource "aws_api_gateway_resource" "iac-api-gateway-resource-google" {
      + id          = (known after apply)
      + parent_id   = (known after apply)
      + path        = (known after apply)
      + path_part   = "google"
      + rest_api_id = (known after apply)
    }

  # aws_api_gateway_resource.iac-api-gateway-resource-google-enter will be created
+ resource "aws_api_gateway_resource" "iac-api-gateway-resource-google-enter" {
      + id          = (known after apply)
      + parent_id   = (known after apply)
      + path        = (known after apply)
      + path_part   = "enter"
      + rest_api_id = (known after apply)
    }

  # aws_api_gateway_rest_api.iac-api-gateway will be created
+ resource "aws_api_gateway_rest_api" "iac-api-gateway" {
      + api_key_source               = (known after apply)
      + arn                          = (known after apply)
      + binary_media_types           = (known after apply)
      + created_date                 = (known after apply)
      + description                  = "Proxy to handle requests to our API"
      + disable_execute_api_endpoint = (known after apply)
      + execution_arn                = (known after apply)
      + id                           = (known after apply)
      + minimum_compression_size     = -1
      + name                         = "iac-api-gateway"
      + policy                       = (known after apply)
      + root_resource_id             = (known after apply)
      + tags_all                     = (known after apply)

      + endpoint_configuration {
          + types            = (known after apply)
          + vpc_endpoint_ids = (known after apply)
        }
    }

Plan: 5 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+ iac-api-gateway = (known after apply)

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d Example`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252FExample%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d Example`
</details>
Plan: 5 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `Example` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d Example`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252FExample%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d Example`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `Example` workspace: `default`

<details><summary>Show Output</summary>

```diff
aws_api_gateway_rest_api.iac-api-gateway: Creating...
aws_api_gateway_rest_api.iac-api-gateway: Creation complete after 1s [id=4w0848xly3]
aws_api_gateway_resource.iac-api-gateway-resource-google: Creating...
aws_api_gateway_resource.iac-api-gateway-resource-google: Creation complete after 0s [id=t64m0p]
aws_api_gateway_resource.iac-api-gateway-resource-google-enter: Creating...
aws_api_gateway_resource.iac-api-gateway-resource-google-enter: Creation complete after 0s [id=zda2cx]
aws_api_gateway_method.iac-api-gateway-method-google-enter: Creating...
aws_api_gateway_method.iac-api-gateway-method-google-enter: Creation complete after 0s [id=agm-4w0848xly3-zda2cx-GET]
aws_api_gateway_integration.iac-api-gateway-integration: Creating...
aws_api_gateway_integration.iac-api-gateway-integration: Creation complete after 0s [id=agi-4w0848xly3-zda2cx-GET]

Apply complete! Resources: 5 added, 0 changed, 0 destroyed.

Outputs:

iac-api-gateway = "https://4w0848xly3.execute-api.ap-northeast-2.amazonaws.com"

```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `Example` workspace: `default`

**Pull request merged**
