### PR TITLE
remove: memo

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # aws_ecr_lifecycle_policy.memo-ecr-policy will be destroyed
  # (because aws_ecr_lifecycle_policy.memo-ecr-policy is not in configuration)
- resource "aws_ecr_lifecycle_policy" "memo-ecr-policy" {
      - id          = "memo-ecr" -> null
      - policy      = jsonencode(
            {
              - rules = [
                  - {
                      - action       = {
                          - type = "expire"
                        }
                      - description  = "Keep image deployed with tag latest"
                      - rulePriority = 1
                      - selection    = {
                          - countNumber   = 1
                          - countType     = "imageCountMoreThan"
                          - tagPrefixList = [
                              - "latest",
                            ]
                          - tagStatus     = "tagged"
                        }
                    },
                  - {
                      - action       = {
                          - type = "expire"
                        }
                      - description  = "Keep last 2 any images"
                      - rulePriority = 2
                      - selection    = {
                          - countNumber = 2
                          - countType   = "imageCountMoreThan"
                          - tagStatus   = "any"
                        }
                    },
                ]
            }
        ) -> null
      - registry_id = "264842458097" -> null
      - repository  = "memo-ecr" -> null
    }

  # aws_ecr_repository.memo-ecr will be destroyed
  # (because aws_ecr_repository.memo-ecr is not in configuration)
- resource "aws_ecr_repository" "memo-ecr" {
      - arn                  = "arn:aws:ecr:ap-northeast-2:264842458097:repository/memo-ecr" -> null
      - id                   = "memo-ecr" -> null
      - image_tag_mutability = "MUTABLE" -> null
      - name                 = "memo-ecr" -> null
      - registry_id          = "264842458097" -> null
      - repository_url       = "264842458097.dkr.ecr.ap-northeast-2.amazonaws.com/memo-ecr" -> null
      - tags                 = {} -> null
      - tags_all             = {} -> null

      - encryption_configuration {
          - encryption_type = "AES256" -> null
        }

      - image_scanning_configuration {
          - scan_on_push = true -> null
        }
    }

  # aws_ecs_cluster.memo-ecs-cluster will be destroyed
  # (because aws_ecs_cluster.memo-ecs-cluster is not in configuration)
- resource "aws_ecs_cluster" "memo-ecs-cluster" {
      - arn                = "arn:aws:ecs:ap-northeast-2:264842458097:cluster/memo-ecs-cluster" -> null
      - capacity_providers = [
          - "FARGATE",
        ] -> null
      - id                 = "arn:aws:ecs:ap-northeast-2:264842458097:cluster/memo-ecs-cluster" -> null
      - name               = "memo-ecs-cluster" -> null
      - tags               = {
          - "Name" = "memo-ecs-cluster"
        } -> null
      - tags_all           = {
          - "Name" = "memo-ecs-cluster"
        } -> null

      - default_capacity_provider_strategy {
          - base              = 1 -> null
          - capacity_provider = "FARGATE" -> null
          - weight            = 100 -> null
        }

      - setting {
          - name  = "containerInsights" -> null
          - value = "enabled" -> null
        }
    }

  # aws_ecs_cluster_capacity_providers.memo-ecs-cluster-capacity-providers will be destroyed
  # (because aws_ecs_cluster_capacity_providers.memo-ecs-cluster-capacity-providers is not in configuration)
- resource "aws_ecs_cluster_capacity_providers" "memo-ecs-cluster-capacity-providers" {
      - capacity_providers = [
          - "FARGATE",
        ] -> null
      - cluster_name       = "memo-ecs-cluster" -> null
      - id                 = "memo-ecs-cluster" -> null

      - default_capacity_provider_strategy {
          - base              = 1 -> null
          - capacity_provider = "FARGATE" -> null
          - weight            = 100 -> null
        }
    }

  # aws_ecs_service.memo-ecs-service will be destroyed
  # (because aws_ecs_service.memo-ecs-service is not in configuration)
- resource "aws_ecs_service" "memo-ecs-service" {
      - cluster                            = "arn:aws:ecs:ap-northeast-2:264842458097:cluster/memo-ecs-cluster" -> null
      - deployment_maximum_percent         = 200 -> null
      - deployment_minimum_healthy_percent = 100 -> null
      - desired_count                      = 1 -> null
      - enable_ecs_managed_tags            = false -> null
      - enable_execute_command             = false -> null
      - health_check_grace_period_seconds  = 0 -> null
      - iam_role                           = "aws-service-role" -> null
      - id                                 = "arn:aws:ecs:ap-northeast-2:264842458097:service/memo-ecs-cluster/memo-ecs-service" -> null
      - launch_type                        = "FARGATE" -> null
      - name                               = "memo-ecs-service" -> null
      - platform_version                   = "LATEST" -> null
      - propagate_tags                     = "NONE" -> null
      - scheduling_strategy                = "REPLICA" -> null
      - tags                               = {} -> null
      - tags_all                           = {} -> null
      - task_definition                    = "arn:aws:ecs:ap-northeast-2:264842458097:task-definition/memo-ecs-task-definition:10" -> null
      - wait_for_steady_state              = false -> null

      - deployment_circuit_breaker {
          - enable   = false -> null
          - rollback = false -> null
        }

      - deployment_controller {
          - type = "ECS" -> null
        }

      - load_balancer {
          - container_name   = "memo-ecs-container" -> null
          - container_port   = 8080 -> null
          - target_group_arn = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/b1282354ddf594fb" -> null
        }

      - network_configuration {
          - assign_public_ip = true -> null
          - security_groups  = [
              - "sg-06f64f1a2a42dfc63",
            ] -> null
          - subnets          = [
              - "subnet-0b8de44bcd332b5ac",
              - "subnet-0bb6102ac68f7e016",
            ] -> null
        }
    }

  # aws_ecs_task_definition.memo-ecs-task-definition will be destroyed
  # (because aws_ecs_task_definition.memo-ecs-task-definition is not in configuration)
- resource "aws_ecs_task_definition" "memo-ecs-task-definition" {
      - arn                      = "arn:aws:ecs:ap-northeast-2:264842458097:task-definition/memo-ecs-task-definition:10" -> null
      - container_definitions    = jsonencode(
            [
              - {
                  - cpu          = 256
                  - environment  = []
                  - essential    = true
                  - image        = "264842458097.dkr.ecr.ap-northeast-2.amazonaws.com/memo-ecr:60ff002d7bd529810624885e733a9682303f8270"
                  - memory       = 512
                  - mountPoints  = []
                  - name         = "memo-ecs-container"
                  - portMappings = [
                      - {
                          - containerPort = 8080
                          - hostPort      = 8080
                          - protocol      = "tcp"
                        },
                    ]
                  - volumesFrom  = []
                },
            ]
        ) -> null
      - cpu                      = "256" -> null
      - execution_role_arn       = "arn:aws:iam::264842458097:role/ecs-staging-execution-role" -> null
      - family                   = "memo-ecs-task-definition" -> null
      - id                       = "memo-ecs-task-definition" -> null
      - memory                   = "512" -> null
      - network_mode             = "awsvpc" -> null
      - requires_compatibilities = [
          - "FARGATE",
        ] -> null
      - revision                 = 10 -> null
      - skip_destroy             = false -> null
      - tags                     = {} -> null
      - tags_all                 = {} -> null
    }

  # aws_iam_role.ecs-task-execution-role will be destroyed
  # (because aws_iam_role.ecs-task-execution-role is not in configuration)
- resource "aws_iam_role" "ecs-task-execution-role" {
      - arn                   = "arn:aws:iam::264842458097:role/ecs-staging-execution-role" -> null
      - assume_role_policy    = jsonencode(
            {
              - Statement = [
                  - {
                      - Action    = "sts:AssumeRole"
                      - Effect    = "Allow"
                      - Principal = {
                          - Service = "ecs-tasks.amazonaws.com"
                        }
                      - Sid       = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> null
      - create_date           = "2022-02-24T11:35:44Z" -> null
      - force_detach_policies = false -> null
      - id                    = "ecs-staging-execution-role" -> null
      - managed_policy_arns   = [
          - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy",
        ] -> null
      - max_session_duration  = 3600 -> null
      - name                  = "ecs-staging-execution-role" -> null
      - path                  = "/" -> null
      - tags                  = {} -> null
      - tags_all              = {} -> null
      - unique_id             = "AROAT3KOXGPYXOHYFI4MS" -> null

      - inline_policy {}
    }

  # aws_iam_role_policy_attachment.ecs-task-execution-role will be destroyed
  # (because aws_iam_role_policy_attachment.ecs-task-execution-role is not in configuration)
- resource "aws_iam_role_policy_attachment" "ecs-task-execution-role" {
      - id         = "ecs-staging-execution-role-20220224113548242500000001" -> null
      - policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy" -> null
      - role       = "ecs-staging-execution-role" -> null
    }

  # aws_lb.memo-alb will be destroyed
  # (because aws_lb.memo-alb is not in configuration)
- resource "aws_lb" "memo-alb" {
      - arn                        = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:loadbalancer/app/memo-alb/99c5d5623fa5aa5f" -> null
      - arn_suffix                 = "app/memo-alb/99c5d5623fa5aa5f" -> null
      - desync_mitigation_mode     = "defensive" -> null
      - dns_name                   = "memo-alb-1655237520.ap-northeast-2.elb.amazonaws.com" -> null
      - drop_invalid_header_fields = false -> null
      - enable_deletion_protection = true -> null
      - enable_http2               = true -> null
      - enable_waf_fail_open       = false -> null
      - id                         = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:loadbalancer/app/memo-alb/99c5d5623fa5aa5f" -> null
      - idle_timeout               = 60 -> null
      - internal                   = false -> null
      - ip_address_type            = "ipv4" -> null
      - load_balancer_type         = "application" -> null
      - name                       = "memo-alb" -> null
      - security_groups            = [
          - "sg-06f64f1a2a42dfc63",
        ] -> null
      - subnets                    = [
          - "subnet-0b8de44bcd332b5ac",
          - "subnet-0bb6102ac68f7e016",
        ] -> null
      - tags                       = {
          - "Name" = "memo-alb"
        } -> null
      - tags_all                   = {
          - "Name" = "memo-alb"
        } -> null
      - vpc_id                     = "vpc-0119ba5078755447e" -> null
      - zone_id                    = "ZWKZPGTI48KDX" -> null

      - access_logs {
          - enabled = false -> null
        }

      - subnet_mapping {
          - subnet_id = "subnet-0b8de44bcd332b5ac" -> null
        }
      - subnet_mapping {
          - subnet_id = "subnet-0bb6102ac68f7e016" -> null
        }
    }

  # aws_lb_listener.memo-alb-listener will be destroyed
  # (because aws_lb_listener.memo-alb-listener is not in configuration)
- resource "aws_lb_listener" "memo-alb-listener" {
      - arn               = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:listener/app/memo-alb/99c5d5623fa5aa5f/6d34e868e2d2e54e" -> null
      - id                = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:listener/app/memo-alb/99c5d5623fa5aa5f/6d34e868e2d2e54e" -> null
      - load_balancer_arn = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:loadbalancer/app/memo-alb/99c5d5623fa5aa5f" -> null
      - port              = 80 -> null
      - protocol          = "HTTP" -> null
      - tags              = {} -> null
      - tags_all          = {} -> null

      - default_action {
          - order            = 1 -> null
          - target_group_arn = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/b1282354ddf594fb" -> null
          - type             = "forward" -> null
        }
    }

  # aws_lb_target_group.memo-alb-target-group will be destroyed
  # (because aws_lb_target_group.memo-alb-target-group is not in configuration)
- resource "aws_lb_target_group" "memo-alb-target-group" {
      - arn                                = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/b1282354ddf594fb" -> null
      - arn_suffix                         = "targetgroup/memo-alb-target-group/b1282354ddf594fb" -> null
      - connection_termination             = false -> null
      - deregistration_delay               = "300" -> null
      - id                                 = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/b1282354ddf594fb" -> null
      - lambda_multi_value_headers_enabled = false -> null
      - load_balancing_algorithm_type      = "round_robin" -> null
      - name                               = "memo-alb-target-group" -> null
      - port                               = 8080 -> null
      - protocol                           = "HTTP" -> null
      - protocol_version                   = "HTTP1" -> null
      - proxy_protocol_v2                  = false -> null
      - slow_start                         = 0 -> null
      - tags                               = {} -> null
      - tags_all                           = {} -> null
      - target_type                        = "ip" -> null
      - vpc_id                             = "vpc-0119ba5078755447e" -> null

      - health_check {
          - enabled             = true -> null
          - healthy_threshold   = 5 -> null
          - interval            = 10 -> null
          - matcher             = "200" -> null
          - path                = "/" -> null
          - port                = "traffic-port" -> null
          - protocol            = "HTTP" -> null
          - timeout             = 2 -> null
          - unhealthy_threshold = 5 -> null
        }

      - stickiness {
          - cookie_duration = 86400 -> null
          - enabled         = false -> null
          - type            = "lb_cookie" -> null
        }
    }

  # aws_security_group.memo-security-group will be destroyed
  # (because aws_security_group.memo-security-group is not in configuration)
- resource "aws_security_group" "memo-security-group" {
      - arn                    = "arn:aws:ec2:ap-northeast-2:264842458097:security-group/sg-06f64f1a2a42dfc63" -> null
      - description            = "Memo Service Security Group" -> null
      - egress                 = [
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = ""
              - from_port        = 0
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "-1"
              - security_groups  = []
              - self             = false
              - to_port          = 0
            },
        ] -> null
      - id                     = "sg-06f64f1a2a42dfc63" -> null
      - ingress                = [
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = "HTTP"
              - from_port        = 443
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 443
            },
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = "HTTP"
              - from_port        = 8080
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 8080
            },
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = "HTTP"
              - from_port        = 80
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 80
            },
        ] -> null
      - name                   = "memo-security-group" -> null
      - owner_id               = "264842458097" -> null
      - revoke_rules_on_delete = false -> null
      - tags                   = {
          - "Name" = "memo-security-group"
        } -> null
      - tags_all               = {
          - "Name" = "memo-security-group"
        } -> null
      - vpc_id                 = "vpc-0119ba5078755447e" -> null
    }

Plan: 0 to add, 0 to change, 12 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 0 to add, 0 to change, 12 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform apply -input=false \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/47/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/47/default": exit status 1
aws_iam_role_policy_attachment.ecs-task-execution-role: Destroying... [id=ecs-staging-execution-role-20220224113548242500000001]
aws_lb_listener.memo-alb-listener: Destroying... [id=arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:listener/app/memo-alb/99c5d5623fa5aa5f/6d34e868e2d2e54e]
aws_ecs_cluster_capacity_providers.memo-ecs-cluster-capacity-providers: Destroying... [id=memo-ecs-cluster]
aws_ecr_lifecycle_policy.memo-ecr-policy: Destroying... [id=memo-ecr]
aws_ecs_service.memo-ecs-service: Destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097:service/memo-ecs-cluster/memo-ecs-service]
aws_ecr_lifecycle_policy.memo-ecr-policy: Destruction complete after 0s
aws_lb_listener.memo-alb-listener: Destruction complete after 0s
aws_lb.memo-alb: Destroying... [id=arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:loadbalancer/app/memo-alb/99c5d5623fa5aa5f]
aws_iam_role_policy_attachment.ecs-task-execution-role: Destruction complete after 1s
aws_ecs_cluster_capacity_providers.memo-ecs-cluster-capacity-providers: Still destroying... [id=memo-ecs-cluster, 10s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 10s elapsed]
aws_ecs_cluster_capacity_providers.memo-ecs-cluster-capacity-providers: Destruction complete after 10s
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 20s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 30s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 40s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 50s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 1m0s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 1m10s elapsed]
aws_ecs_service.memo-ecs-service: Destruction complete after 1m15s
aws_ecs_task_definition.memo-ecs-task-definition: Destroying... [id=memo-ecs-task-definition]
aws_lb_target_group.memo-alb-target-group: Destroying... [id=arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/b1282354ddf594fb]
aws_ecs_cluster.memo-ecs-cluster: Destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097:cluster/memo-ecs-cluster]
aws_lb_target_group.memo-alb-target-group: Destruction complete after 0s
aws_ecs_task_definition.memo-ecs-task-definition: Destruction complete after 0s
aws_ecr_repository.memo-ecr: Destroying... [id=memo-ecr]
aws_iam_role.ecs-task-execution-role: Destroying... [id=ecs-staging-execution-role]
aws_ecs_cluster.memo-ecs-cluster: Destruction complete after 0s
aws_ecr_repository.memo-ecr: Destruction complete after 0s
aws_iam_role.ecs-task-execution-role: Destruction complete after 3s
╷
│ Error: error deleting LB: OperationNotPermitted: Load balancer 'arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:loadbalancer/app/memo-alb/99c5d5623fa5aa5f' cannot be deleted because deletion protection is enabled
│ 	status code: 400, request id: 4aa00720-7868-43f8-9f55-de420522ba19
│ 
│ 
╵

```
</details>

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

**Apply Error**
```
running "/usr/bin/terraform apply -input=false \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/47/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/47/default": exit status 1
╷
│ Error: Saved plan is stale
│ 
│ The given plan file can no longer be applied because the state was changed
│ by another operation after the plan was created.
╵

```

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_lb.memo-alb has changed
~ resource "aws_lb" "memo-alb" {
      ~ enable_deletion_protection = true -> false
        id                         = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:loadbalancer/app/memo-alb/99c5d5623fa5aa5f"
        name                       = "memo-alb"
        tags                       = {
            "Name" = "memo-alb"
        }
        # (16 unchanged attributes hidden)


        # (3 unchanged blocks hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # aws_lb.memo-alb will be destroyed
  # (because aws_lb.memo-alb is not in configuration)
- resource "aws_lb" "memo-alb" {
      - arn                        = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:loadbalancer/app/memo-alb/99c5d5623fa5aa5f" -> null
      - arn_suffix                 = "app/memo-alb/99c5d5623fa5aa5f" -> null
      - desync_mitigation_mode     = "defensive" -> null
      - dns_name                   = "memo-alb-1655237520.ap-northeast-2.elb.amazonaws.com" -> null
      - drop_invalid_header_fields = false -> null
      - enable_deletion_protection = false -> null
      - enable_http2               = true -> null
      - enable_waf_fail_open       = false -> null
      - id                         = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:loadbalancer/app/memo-alb/99c5d5623fa5aa5f" -> null
      - idle_timeout               = 60 -> null
      - internal                   = false -> null
      - ip_address_type            = "ipv4" -> null
      - load_balancer_type         = "application" -> null
      - name                       = "memo-alb" -> null
      - security_groups            = [
          - "sg-06f64f1a2a42dfc63",
        ] -> null
      - subnets                    = [
          - "subnet-0b8de44bcd332b5ac",
          - "subnet-0bb6102ac68f7e016",
        ] -> null
      - tags                       = {
          - "Name" = "memo-alb"
        } -> null
      - tags_all                   = {
          - "Name" = "memo-alb"
        } -> null
      - vpc_id                     = "vpc-0119ba5078755447e" -> null
      - zone_id                    = "ZWKZPGTI48KDX" -> null

      - access_logs {
          - enabled = false -> null
        }

      - subnet_mapping {
          - subnet_id = "subnet-0b8de44bcd332b5ac" -> null
        }
      - subnet_mapping {
          - subnet_id = "subnet-0bb6102ac68f7e016" -> null
        }
    }

  # aws_security_group.memo-security-group will be destroyed
  # (because aws_security_group.memo-security-group is not in configuration)
- resource "aws_security_group" "memo-security-group" {
      - arn                    = "arn:aws:ec2:ap-northeast-2:264842458097:security-group/sg-06f64f1a2a42dfc63" -> null
      - description            = "Memo Service Security Group" -> null
      - egress                 = [
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = ""
              - from_port        = 0
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "-1"
              - security_groups  = []
              - self             = false
              - to_port          = 0
            },
        ] -> null
      - id                     = "sg-06f64f1a2a42dfc63" -> null
      - ingress                = [
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = "HTTP"
              - from_port        = 443
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 443
            },
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = "HTTP"
              - from_port        = 8080
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 8080
            },
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = "HTTP"
              - from_port        = 80
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 80
            },
        ] -> null
      - name                   = "memo-security-group" -> null
      - owner_id               = "264842458097" -> null
      - revoke_rules_on_delete = false -> null
      - tags                   = {
          - "Name" = "memo-security-group"
        } -> null
      - tags_all               = {
          - "Name" = "memo-security-group"
        } -> null
      - vpc_id                 = "vpc-0119ba5078755447e" -> null
    }

Plan: 0 to add, 0 to change, 2 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 0 to add, 0 to change, 2 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
**Plan Error**
```
The default workspace is currently locked by another command that is running for this pull request.
Wait until the previous command is complete and try again.
```

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
