### PR TITLE
add: subnet into routing table

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/bin/terraform plan -input=false -refresh -out \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/24/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/24/default": exit status 1
╷
│ Error: Unsupported argument
│ 
│   on infra.tf line 28, in resource "aws_route_table" "iac-routing-table-20220223":
│   28:   subnet_id = iac-subnet-20220223
│ 
│ An argument named "subnet_id" is not expected here.
╵

```

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/bin/terraform plan -input=false -refresh -out \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/24/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/24/default": exit status 1
╷
│ Error: Invalid reference
│ 
│   on infra.tf line 28, in resource "aws_route_table" "iac-routing-table-20220223":
│   28:   id = iac-subnet-20220223
│ 
│ A reference to a resource type must be followed by at least one attribute
│ access, specifying the resource name.
╵

```

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/bin/terraform plan -input=false -refresh -out \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/24/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/24/default": exit status 1
Acquiring state lock. This may take a few moments...
╷
│ Error: Invalid or unknown key
│ 
│   with aws_route_table.iac-routing-table-20220223,
│   on infra.tf line 28, in resource "aws_route_table" "iac-routing-table-20220223":
│   28:   id = aws_subnet.iac-subnet-20220223.id
│ 
╵

```

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/bin/terraform plan -input=false -refresh -out \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/24/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/24/default": exit status 1
╷
│ Error: Unsupported argument
│ 
│   on infra.tf line 28, in resource "aws_route_table" "iac-routing-table-20220223":
│   28:   subnet_id = aws_subnet.iac-subnet-20220223.id
│ 
│ An argument named "subnet_id" is not expected here.
╵

```

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_instance.iac-ec2-20220223 has changed
~ resource "aws_instance" "iac-ec2-20220223" {
      ~ associate_public_ip_address          = false -> true
        id                                   = "i-030bd725830bab8e0"
      + public_ip                            = "3.35.1.46"
        tags                                 = {
            "Name" = "iac-ec2-20220223"
        }
        # (26 unchanged attributes hidden)





        # (5 unchanged blocks hidden)
    }

  # aws_subnet.iac-subnet-20220223 has changed
~ resource "aws_subnet" "iac-subnet-20220223" {
        id                                             = "subnet-0f934a92067b0f67e"
      + tags                                           = {}
        # (15 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_route_table_association.iac-routing-table-association-20220223 will be created
+ resource "aws_route_table_association" "iac-routing-table-association-20220223" {
      + id             = (known after apply)
      + route_table_id = "rtb-0a1e2908f34d32eb9"
      + subnet_id      = "subnet-0f934a92067b0f67e"
    }

Plan: 1 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
Acquiring state lock. This may take a few moments...
aws_route_table_association.iac-routing-table-association-20220223: Creating...
aws_route_table_association.iac-routing-table-association-20220223: Creation complete after 0s [id=rtbassoc-06c8df1d7504d8e41]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.


```

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
