### PR TITLE
delete: google

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # module.production.module.atlantis-rhea-so.aws_route53_record.domain has changed
~ resource "aws_route53_record" "domain" {
        id              = "Z007496927OLC0YXP6DHX_atlantis.rhea-so.com_A"
        name            = "atlantis.rhea-so.com"
        # (6 unchanged attributes hidden)
    }

  # module.production.module.google-rhea-so.aws_route53_record.domain has changed
~ resource "aws_route53_record" "domain" {
        id              = "Z007496927OLC0YXP6DHX_google.rhea-so.com_A"
        name            = "google.rhea-so.com"
        # (6 unchanged attributes hidden)
    }

  # module.production.module.rhea-so.aws_route53_zone.domain has changed
~ resource "aws_route53_zone" "domain" {
        id            = "Z007496927OLC0YXP6DHX"
        name          = "rhea-so.com"
      + tags          = {}
        # (6 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # module.production.module.google-rhea-so.aws_route53_record.domain will be destroyed
  # (because aws_route53_record.domain is not in configuration)
- resource "aws_route53_record" "domain" {
      - allow_overwrite = true -> null
      - fqdn            = "google.rhea-so.com" -> null
      - id              = "Z007496927OLC0YXP6DHX_google.rhea-so.com_A" -> null
      - name            = "google.rhea-so.com" -> null
      - records         = [
          - "172.217.31.174",
        ] -> null
      - ttl             = 300 -> null
      - type            = "A" -> null
      - zone_id         = "Z007496927OLC0YXP6DHX" -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 0 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
**Plan Error**
```
The default workspace is currently locked by another command that is running for this pull request.
Wait until the previous command is complete and try again.
```

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
module.production.module.google-rhea-so.aws_route53_record.domain: Destroying... [id=Z007496927OLC0YXP6DHX_google.rhea-so.com_A]
module.production.module.google-rhea-so.aws_route53_record.domain: Still destroying... [id=Z007496927OLC0YXP6DHX_google.rhea-so.com_A, 10s elapsed]
module.production.module.google-rhea-so.aws_route53_record.domain: Still destroying... [id=Z007496927OLC0YXP6DHX_google.rhea-so.com_A, 20s elapsed]
module.production.module.google-rhea-so.aws_route53_record.domain: Still destroying... [id=Z007496927OLC0YXP6DHX_google.rhea-so.com_A, 30s elapsed]
module.production.module.google-rhea-so.aws_route53_record.domain: Destruction complete after 40s

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.


```

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
