### PR TITLE
test: api gateway

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/bin/terraform plan -input=false -refresh -out \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/121/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/121/default": exit status 1
╷
│ Error: Missing required argument
│ 
│   on modules/environment/production/main.tf line 9, in module "api-gateway":
│    9: module "api-gateway" {
│ 
│ The argument "name" is required, but no definition was found.
╵

```

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/bin/terraform plan -input=false -refresh -out \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/121/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/121/default": exit status 1
╷
│ Error: Reference to undeclared resource
│ 
│   on modules/aws/api-gateway/outputs.tf line 2, in output "id":
│    2:   value = aws_vpc.vpc.id
│ 
│ A managed resource "aws_vpc" "vpc" has not been declared in
│ module.production.module.api-gateway.
╵

```

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # module.rhea-so.aws_route53_zone.domain has changed
~ resource "aws_route53_zone" "domain" {
        id            = "Z0097287UVNCC6G4O03H"
        name          = "rhea-so.com"
      + tags          = {}
        # (6 unchanged attributes hidden)
    }

  # module.production.module.atlantis-rhea-so.aws_route53_record.domain has changed
~ resource "aws_route53_record" "domain" {
        id              = "Z0097287UVNCC6G4O03H_atlantis.rhea-so.com_A"
        name            = "atlantis.rhea-so.com"
        # (6 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
- destroy

Terraform will perform the following actions:

  # module.production.module.api-gateway.aws_api_gateway_integration.iac-api-gateway-integration will be created
+ resource "aws_api_gateway_integration" "iac-api-gateway-integration" {
      + cache_namespace         = (known after apply)
      + connection_type         = "INTERNET"
      + http_method             = "GET"
      + id                      = (known after apply)
      + integration_http_method = "GET"
      + passthrough_behavior    = (known after apply)
      + resource_id             = (known after apply)
      + rest_api_id             = (known after apply)
      + timeout_milliseconds    = 29000
      + type                    = "HTTP_PROXY"
      + uri                     = "http://google.com"
    }

  # module.production.module.api-gateway.aws_api_gateway_method.iac-api-gateway-method-google-enter will be created
+ resource "aws_api_gateway_method" "iac-api-gateway-method-google-enter" {
      + api_key_required = false
      + authorization    = "NONE"
      + http_method      = "GET"
      + id               = (known after apply)
      + resource_id      = (known after apply)
      + rest_api_id      = (known after apply)
    }

  # module.production.module.api-gateway.aws_api_gateway_resource.iac-api-gateway-resource-google will be created
+ resource "aws_api_gateway_resource" "iac-api-gateway-resource-google" {
      + id          = (known after apply)
      + parent_id   = (known after apply)
      + path        = (known after apply)
      + path_part   = "google"
      + rest_api_id = (known after apply)
    }

  # module.production.module.api-gateway.aws_api_gateway_resource.iac-api-gateway-resource-google-enter will be created
+ resource "aws_api_gateway_resource" "iac-api-gateway-resource-google-enter" {
      + id          = (known after apply)
      + parent_id   = (known after apply)
      + path        = (known after apply)
      + path_part   = "enter"
      + rest_api_id = (known after apply)
    }

  # module.production.module.api-gateway.aws_api_gateway_rest_api.iac-api-gateway will be created
+ resource "aws_api_gateway_rest_api" "iac-api-gateway" {
      + api_key_source               = (known after apply)
      + arn                          = (known after apply)
      + binary_media_types           = (known after apply)
      + created_date                 = (known after apply)
      + description                  = "Proxy to handle requests to our API"
      + disable_execute_api_endpoint = (known after apply)
      + execution_arn                = (known after apply)
      + id                           = (known after apply)
      + minimum_compression_size     = -1
      + name                         = "iac-api-gateway"
      + policy                       = (known after apply)
      + root_resource_id             = (known after apply)
      + tags_all                     = (known after apply)

      + endpoint_configuration {
          + types            = (known after apply)
          + vpc_endpoint_ids = (known after apply)
        }
    }

  # module.production.module.production-vpc.aws_vpc.vpc will be destroyed
  # (because aws_vpc.vpc is not in configuration)
- resource "aws_vpc" "vpc" {
      - arn                              = "arn:aws:ec2:ap-northeast-2:264842458097:vpc/vpc-065f63385559fb8ee" -> null
      - assign_generated_ipv6_cidr_block = false -> null
      - cidr_block                       = "10.0.0.0/16" -> null
      - default_network_acl_id           = "acl-03486df82c02f741c" -> null
      - default_route_table_id           = "rtb-01dabacb03277fcac" -> null
      - default_security_group_id        = "sg-08b165e24ed78f7c5" -> null
      - dhcp_options_id                  = "dopt-0439dc969e8731205" -> null
      - enable_classiclink               = false -> null
      - enable_classiclink_dns_support   = false -> null
      - enable_dns_hostnames             = false -> null
      - enable_dns_support               = true -> null
      - id                               = "vpc-065f63385559fb8ee" -> null
      - instance_tenancy                 = "default" -> null
      - ipv6_netmask_length              = 0 -> null
      - main_route_table_id              = "rtb-01dabacb03277fcac" -> null
      - owner_id                         = "264842458097" -> null
      - tags                             = {
          - "Name" = "production-vpc"
        } -> null
      - tags_all                         = {
          - "Name" = "production-vpc"
        } -> null
    }

Plan: 5 to add, 0 to change, 1 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 5 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
module.production.module.production-vpc.aws_vpc.vpc: Destroying... [id=vpc-065f63385559fb8ee]
module.production.module.api-gateway.aws_api_gateway_rest_api.iac-api-gateway: Creating...
module.production.module.production-vpc.aws_vpc.vpc: Destruction complete after 0s
module.production.module.api-gateway.aws_api_gateway_rest_api.iac-api-gateway: Creation complete after 1s [id=kb4bj3xon8]
module.production.module.api-gateway.aws_api_gateway_resource.iac-api-gateway-resource-google: Creating...
module.production.module.api-gateway.aws_api_gateway_resource.iac-api-gateway-resource-google: Creation complete after 0s [id=4jr77i]
module.production.module.api-gateway.aws_api_gateway_resource.iac-api-gateway-resource-google-enter: Creating...
module.production.module.api-gateway.aws_api_gateway_resource.iac-api-gateway-resource-google-enter: Creation complete after 0s [id=rekm5u]
module.production.module.api-gateway.aws_api_gateway_method.iac-api-gateway-method-google-enter: Creating...
module.production.module.api-gateway.aws_api_gateway_method.iac-api-gateway-method-google-enter: Creation complete after 0s [id=agm-kb4bj3xon8-rekm5u-GET]
module.production.module.api-gateway.aws_api_gateway_integration.iac-api-gateway-integration: Creating...
module.production.module.api-gateway.aws_api_gateway_integration.iac-api-gateway-integration: Creation complete after 0s [id=agi-kb4bj3xon8-rekm5u-GET]

Apply complete! Resources: 5 added, 0 changed, 1 destroyed.


```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
