### PR TITLE
add: RabbitMQ Test

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/bin/terraform plan -input=false -refresh -out \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/68/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/68/default": exit status 1
╷
│ Error: "user.0.password" must be 12 to 250 characters long. provided string length: 6
│ 
│   with aws_mq_broker.rabbitmq,
│   on rabbitmq.tf line 30, in resource "aws_mq_broker" "rabbitmq":
│   30: resource "aws_mq_broker" "rabbitmq" {
│ 
╵

```

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_mq_broker.rabbitmq will be created
+ resource "aws_mq_broker" "rabbitmq" {
      + apply_immediately          = false
      + arn                        = (known after apply)
      + authentication_strategy    = (known after apply)
      + auto_minor_version_upgrade = false
      + broker_name                = "rabbitmq"
      + deployment_mode            = "SINGLE_INSTANCE"
      + engine_type                = "RabbitMQ"
      + engine_version             = "3.8.6"
      + host_instance_type         = "mq.t3.micro"
      + id                         = (known after apply)
      + instances                  = (known after apply)
      + publicly_accessible        = false
      + security_groups            = (known after apply)
      + storage_type               = (known after apply)
      + subnet_ids                 = (known after apply)
      + tags_all                   = (known after apply)

      + configuration {
          + id       = (known after apply)
          + revision = (known after apply)
        }

      + maintenance_window_start_time {
          + day_of_week = (known after apply)
          + time_of_day = (known after apply)
          + time_zone   = (known after apply)
        }

      + user {
          + console_access = false
          + groups         = []
          + password       = (sensitive value)
          + username       = "rhea-so"
        }
    }

  # aws_security_group.rabbitmq-security-group will be created
+ resource "aws_security_group" "rabbitmq-security-group" {
      + arn                    = (known after apply)
      + description            = "Allow RabbitMQ inbound traffic"
      + egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "-1"
              + security_groups  = []
              + self             = false
              + to_port          = 0
            },
        ]
      + id                     = (known after apply)
      + ingress                = [
          + {
              + cidr_blocks      = [
                  + "39.7.24.115/32",
                ]
              + description      = "SSH"
              + from_port        = 22
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 22
            },
        ]
      + name                   = "rabbitmq-security-group"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "Name" = "rabbitmq-security-group"
        }
      + tags_all               = {
          + "Name" = "rabbitmq-security-group"
        }
      + vpc_id                 = "vpc-0119ba5078755447e"
    }

Plan: 2 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 2 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform apply -input=false \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/68/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/68/default": exit status 1
aws_security_group.rabbitmq-security-group: Creating...
aws_security_group.rabbitmq-security-group: Creation complete after 2s [id=sg-05abf5b39ed51fe93]
aws_mq_broker.rabbitmq: Creating...
╷
│ Error: BadRequestException: Subnets and security groups must belong to the default VPC when only one is provided.
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "e288ea34-52ea-4b18-97ea-c0b51b57958d"
│   },
│   ErrorAttribute: "securityGroups",
│   Message_: "Subnets and security groups must belong to the default VPC when only one is provided."
│ }
│ 
│   with aws_mq_broker.rabbitmq,
│   on rabbitmq.tf line 30, in resource "aws_mq_broker" "rabbitmq":
│   30: resource "aws_mq_broker" "rabbitmq" {
│ 
╵

```
</details>

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/bin/terraform plan -input=false -refresh -out \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/68/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/68/default": exit status 1
╷
│ Error: Unsupported argument
│ 
│   on rabbitmq.tf line 38, in resource "aws_mq_broker" "rabbitmq":
│   38:   subnet_id = aws_subnet.iac-subnet-1.id
│ 
│ An argument named "subnet_id" is not expected here. Did you mean
│ "subnet_ids"?
╵

```

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_mq_broker.rabbitmq will be created
+ resource "aws_mq_broker" "rabbitmq" {
      + apply_immediately          = false
      + arn                        = (known after apply)
      + authentication_strategy    = (known after apply)
      + auto_minor_version_upgrade = false
      + broker_name                = "rabbitmq"
      + deployment_mode            = "SINGLE_INSTANCE"
      + engine_type                = "RabbitMQ"
      + engine_version             = "3.8.6"
      + host_instance_type         = "mq.t3.micro"
      + id                         = (known after apply)
      + instances                  = (known after apply)
      + publicly_accessible        = true
      + security_groups            = [
          + "sg-05abf5b39ed51fe93",
        ]
      + storage_type               = (known after apply)
      + subnet_ids                 = [
          + "subnet-0bb6102ac68f7e016",
        ]
      + tags_all                   = (known after apply)

      + configuration {
          + id       = (known after apply)
          + revision = (known after apply)
        }

      + maintenance_window_start_time {
          + day_of_week = (known after apply)
          + time_of_day = (known after apply)
          + time_zone   = (known after apply)
        }

      + user {
          + console_access = false
          + groups         = []
          + password       = (sensitive value)
          + username       = "rhea-so"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform apply -input=false \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/68/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/68/default": exit status 1
Acquiring state lock. This may take a few moments...
aws_mq_broker.rabbitmq: Creating...
╷
│ Error: BadRequestException: Broker with [publiclyAccessible] set to true does not support specifying [securityGroups]
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "bec76287-3655-4497-ac90-1abb638f3364"
│   },
│   ErrorAttribute: "securityGroups",
│   Message_: "Broker with [publiclyAccessible] set to true does not support specifying [securityGroups]"
│ }
│ 
│   with aws_mq_broker.rabbitmq,
│   on rabbitmq.tf line 30, in resource "aws_mq_broker" "rabbitmq":
│   30: resource "aws_mq_broker" "rabbitmq" {
│ 
╵

```
</details>

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_mq_broker.rabbitmq will be created
+ resource "aws_mq_broker" "rabbitmq" {
      + apply_immediately          = false
      + arn                        = (known after apply)
      + authentication_strategy    = (known after apply)
      + auto_minor_version_upgrade = false
      + broker_name                = "rabbitmq"
      + deployment_mode            = "SINGLE_INSTANCE"
      + engine_type                = "RabbitMQ"
      + engine_version             = "3.8.6"
      + host_instance_type         = "mq.t3.micro"
      + id                         = (known after apply)
      + instances                  = (known after apply)
      + publicly_accessible        = true
      + storage_type               = (known after apply)
      + subnet_ids                 = [
          + "subnet-0bb6102ac68f7e016",
        ]
      + tags_all                   = (known after apply)

      + configuration {
          + id       = (known after apply)
          + revision = (known after apply)
        }

      + maintenance_window_start_time {
          + day_of_week = (known after apply)
          + time_of_day = (known after apply)
          + time_zone   = (known after apply)
        }

      + user {
          + console_access = false
          + groups         = []
          + password       = (sensitive value)
          + username       = "rhea-so"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by rhea-so** [comment]
스크린샷 2022-03-12 오후 7 41 01

> https://docs.aws.amazon.com/ko_kr/amazon-mq/latest/developer-guide/getting-started-rabbitmq.html

네?

15분이나 걸린다구요?

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
aws_mq_broker.rabbitmq: Creating...
aws_mq_broker.rabbitmq: Still creating... [10s elapsed]
aws_mq_broker.rabbitmq: Still creating... [20s elapsed]
aws_mq_broker.rabbitmq: Still creating... [30s elapsed]
aws_mq_broker.rabbitmq: Still creating... [40s elapsed]
aws_mq_broker.rabbitmq: Still creating... [50s elapsed]
aws_mq_broker.rabbitmq: Still creating... [1m0s elapsed]
aws_mq_broker.rabbitmq: Still creating... [1m10s elapsed]
aws_mq_broker.rabbitmq: Still creating... [1m20s elapsed]
aws_mq_broker.rabbitmq: Still creating... [1m30s elapsed]
aws_mq_broker.rabbitmq: Still creating... [1m40s elapsed]
aws_mq_broker.rabbitmq: Still creating... [1m50s elapsed]
aws_mq_broker.rabbitmq: Still creating... [2m0s elapsed]
aws_mq_broker.rabbitmq: Still creating... [2m10s elapsed]
aws_mq_broker.rabbitmq: Still creating... [2m20s elapsed]
aws_mq_broker.rabbitmq: Still creating... [2m30s elapsed]
aws_mq_broker.rabbitmq: Still creating... [2m40s elapsed]
aws_mq_broker.rabbitmq: Still creating... [2m50s elapsed]
aws_mq_broker.rabbitmq: Still creating... [3m0s elapsed]
aws_mq_broker.rabbitmq: Still creating... [3m10s elapsed]
aws_mq_broker.rabbitmq: Still creating... [3m20s elapsed]
aws_mq_broker.rabbitmq: Still creating... [3m30s elapsed]
aws_mq_broker.rabbitmq: Still creating... [3m40s elapsed]
aws_mq_broker.rabbitmq: Still creating... [3m50s elapsed]
aws_mq_broker.rabbitmq: Still creating... [4m0s elapsed]
aws_mq_broker.rabbitmq: Still creating... [4m10s elapsed]
aws_mq_broker.rabbitmq: Still creating... [4m20s elapsed]
aws_mq_broker.rabbitmq: Still creating... [4m30s elapsed]
aws_mq_broker.rabbitmq: Still creating... [4m40s elapsed]
aws_mq_broker.rabbitmq: Still creating... [4m50s elapsed]
aws_mq_broker.rabbitmq: Still creating... [5m0s elapsed]
aws_mq_broker.rabbitmq: Still creating... [5m10s elapsed]
aws_mq_broker.rabbitmq: Still creating... [5m20s elapsed]
aws_mq_broker.rabbitmq: Still creating... [5m30s elapsed]
aws_mq_broker.rabbitmq: Still creating... [5m40s elapsed]
aws_mq_broker.rabbitmq: Still creating... [5m50s elapsed]
aws_mq_broker.rabbitmq: Still creating... [6m0s elapsed]
aws_mq_broker.rabbitmq: Still creating... [6m10s elapsed]
aws_mq_broker.rabbitmq: Still creating... [6m20s elapsed]
aws_mq_broker.rabbitmq: Still creating... [6m30s elapsed]
aws_mq_broker.rabbitmq: Still creating... [6m40s elapsed]
aws_mq_broker.rabbitmq: Still creating... [6m50s elapsed]
aws_mq_broker.rabbitmq: Still creating... [7m0s elapsed]
aws_mq_broker.rabbitmq: Still creating... [7m10s elapsed]
aws_mq_broker.rabbitmq: Still creating... [7m20s elapsed]
aws_mq_broker.rabbitmq: Still creating... [7m30s elapsed]
aws_mq_broker.rabbitmq: Still creating... [7m40s elapsed]
aws_mq_broker.rabbitmq: Still creating... [7m50s elapsed]
aws_mq_broker.rabbitmq: Still creating... [8m0s elapsed]
aws_mq_broker.rabbitmq: Still creating... [8m10s elapsed]
aws_mq_broker.rabbitmq: Still creating... [8m20s elapsed]
aws_mq_broker.rabbitmq: Still creating... [8m30s elapsed]
aws_mq_broker.rabbitmq: Still creating... [8m40s elapsed]
aws_mq_broker.rabbitmq: Creation complete after 8m50s [id=b-6b70b3cf-9401-4f4d-85e3-9f18b9044b91]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.


```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Comment by rhea-so** [comment]
스크린샷 2022-03-12 오후 7 45 20

오오.. 쩌네

이걸 이렇게 쉽게 금방 만든다고?

**Pull request merged**
