### PR TITLE
fix: ec2 to backup, vpc renewal

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_route53_record.iac-route53-20220223 has changed
~ resource "aws_route53_record" "iac-route53-20220223" {
        id      = "Z00481431FE9EJXZFCWSO_rhea-so.com_A"
        name    = "rhea-so.com"
        # (5 unchanged attributes hidden)
    }

  # aws_route53_zone.rhea-so has changed
~ resource "aws_route53_zone" "rhea-so" {
        id            = "Z00481431FE9EJXZFCWSO"
        name          = "rhea-so.com"
      + tags          = {}
        # (6 unchanged attributes hidden)
    }

  # aws_security_group.iac-security-group-20220223 has changed
~ resource "aws_security_group" "iac-security-group-20220223" {
        id                     = "sg-0d141357be85e3913"
      ~ ingress                = [
          + {
              + cidr_blocks      = [
                  + "39.7.28.205/32",
                ]
              + description      = ""
              + from_port        = 80
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 80
            },
            # (1 unchanged element hidden)
        ]
        name                   = "iac-security-group-20220223"
        tags                   = {
            "Name" = "iac-security-group-20220223"
        }
        # (7 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
- destroy

Terraform will perform the following actions:

  # aws_eip.iac-eip-20220223 will be destroyed
  # (because aws_eip.iac-eip-20220223 is not in configuration)
- resource "aws_eip" "iac-eip-20220223" {
      - allocation_id        = "eipalloc-06664f8ac0365d0dd" -> null
      - association_id       = "eipassoc-0ff4d4cfb59487f76" -> null
      - domain               = "vpc" -> null
      - id                   = "eipalloc-06664f8ac0365d0dd" -> null
      - instance             = "i-030bd725830bab8e0" -> null
      - network_border_group = "ap-northeast-2" -> null
      - network_interface    = "eni-0864415f9b0a3bac1" -> null
      - private_dns          = "ip-10-0-1-239.ap-northeast-2.compute.internal" -> null
      - private_ip           = "10.0.1.239" -> null
      - public_dns           = "ec2-3-39-31-8.ap-northeast-2.compute.amazonaws.com" -> null
      - public_ip            = "3.39.31.8" -> null
      - public_ipv4_pool     = "amazon" -> null
      - tags                 = {
          - "Name" = "iac-eip-20220223"
        } -> null
      - tags_all             = {
          - "Name" = "iac-eip-20220223"
        } -> null
      - vpc                  = true -> null
    }

  # aws_instance.iac-ec2-20220223 will be destroyed
  # (because aws_instance.iac-ec2-20220223 is not in configuration)
- resource "aws_instance" "iac-ec2-20220223" {
      - ami                                  = "ami-0454bb2fefc7de534" -> null
      - arn                                  = "arn:aws:ec2:ap-northeast-2:264842458097:instance/i-030bd725830bab8e0" -> null
      - associate_public_ip_address          = true -> null
      - availability_zone                    = "ap-northeast-2b" -> null
      - cpu_core_count                       = 1 -> null
      - cpu_threads_per_core                 = 2 -> null
      - disable_api_termination              = false -> null
      - ebs_optimized                        = false -> null
      - get_password_data                    = false -> null
      - hibernation                          = false -> null
      - id                                   = "i-030bd725830bab8e0" -> null
      - instance_initiated_shutdown_behavior = "stop" -> null
      - instance_state                       = "running" -> null
      - instance_type                        = "t3.nano" -> null
      - ipv6_address_count                   = 0 -> null
      - ipv6_addresses                       = [] -> null
      - key_name                             = "Home" -> null
      - monitoring                           = false -> null
      - primary_network_interface_id         = "eni-0864415f9b0a3bac1" -> null
      - private_dns                          = "ip-10-0-1-239.ap-northeast-2.compute.internal" -> null
      - private_ip                           = "10.0.1.239" -> null
      - public_ip                            = "3.39.31.8" -> null
      - secondary_private_ips                = [] -> null
      - security_groups                      = [] -> null
      - source_dest_check                    = true -> null
      - subnet_id                            = "subnet-0f934a92067b0f67e" -> null
      - tags                                 = {
          - "Name" = "iac-ec2-20220223"
        } -> null
      - tags_all                             = {
          - "Name" = "iac-ec2-20220223"
        } -> null
      - tenancy                              = "default" -> null
      - vpc_security_group_ids               = [
          - "sg-0d141357be85e3913",
        ] -> null

      - capacity_reservation_specification {
          - capacity_reservation_preference = "open" -> null
        }

      - credit_specification {
          - cpu_credits = "unlimited" -> null
        }

      - enclave_options {
          - enabled = false -> null
        }

      - metadata_options {
          - http_endpoint               = "enabled" -> null
          - http_put_response_hop_limit = 1 -> null
          - http_tokens                 = "optional" -> null
          - instance_metadata_tags      = "disabled" -> null
        }

      - root_block_device {
          - delete_on_termination = true -> null
          - device_name           = "/dev/sda1" -> null
          - encrypted             = false -> null
          - iops                  = 100 -> null
          - tags                  = {} -> null
          - throughput            = 0 -> null
          - volume_id             = "vol-054d465dcf1cc0c69" -> null
          - volume_size           = 8 -> null
          - volume_type           = "gp2" -> null
        }
    }

  # aws_internet_gateway.iac-igw will be created
+ resource "aws_internet_gateway" "iac-igw" {
      + arn      = (known after apply)
      + id       = (known after apply)
      + owner_id = (known after apply)
      + tags     = {
          + "Name" = "iac-igw"
        }
      + tags_all = {
          + "Name" = "iac-igw"
        }
      + vpc_id   = (known after apply)
    }

  # aws_internet_gateway.iac-igw-20220223 will be destroyed
  # (because aws_internet_gateway.iac-igw-20220223 is not in configuration)
- resource "aws_internet_gateway" "iac-igw-20220223" {
      - arn      = "arn:aws:ec2:ap-northeast-2:264842458097:internet-gateway/igw-0d7fc83f1a73f0cfd" -> null
      - id       = "igw-0d7fc83f1a73f0cfd" -> null
      - owner_id = "264842458097" -> null
      - tags     = {
          - "Name" = "iac-igw-20220223"
        } -> null
      - tags_all = {
          - "Name" = "iac-igw-20220223"
        } -> null
      - vpc_id   = "vpc-0ef1a2cf24ec0eeda" -> null
    }

  # aws_route53_record.iac-route53-20220223 will be destroyed
  # (because aws_route53_record.iac-route53-20220223 is not in configuration)
- resource "aws_route53_record" "iac-route53-20220223" {
      - fqdn    = "rhea-so.com" -> null
      - id      = "Z00481431FE9EJXZFCWSO_rhea-so.com_A" -> null
      - name    = "rhea-so.com" -> null
      - records = [
          - "3.39.31.8",
        ] -> null
      - ttl     = 300 -> null
      - type    = "A" -> null
      - zone_id = "Z00481431FE9EJXZFCWSO" -> null
    }

  # aws_route_table.iac-routing-table will be created
+ resource "aws_route_table" "iac-routing-table" {
      + arn              = (known after apply)
      + id               = (known after apply)
      + owner_id         = (known after apply)
      + propagating_vgws = (known after apply)
      + route            = [
          + {
              + carrier_gateway_id         = ""
              + cidr_block                 = "0.0.0.0/0"
              + destination_prefix_list_id = ""
              + egress_only_gateway_id     = ""
              + gateway_id                 = (known after apply)
              + instance_id                = ""
              + ipv6_cidr_block            = ""
              + local_gateway_id           = ""
              + nat_gateway_id             = ""
              + network_interface_id       = ""
              + transit_gateway_id         = ""
              + vpc_endpoint_id            = ""
              + vpc_peering_connection_id  = ""
            },
        ]
      + tags             = {
          + "Name" = "iac-routing-table"
        }
      + tags_all         = {
          + "Name" = "iac-routing-table"
        }
      + vpc_id           = (known after apply)
    }

  # aws_route_table.iac-routing-table-20220223 will be destroyed
  # (because aws_route_table.iac-routing-table-20220223 is not in configuration)
- resource "aws_route_table" "iac-routing-table-20220223" {
      - arn              = "arn:aws:ec2:ap-northeast-2:264842458097:route-table/rtb-0a1e2908f34d32eb9" -> null
      - id               = "rtb-0a1e2908f34d32eb9" -> null
      - owner_id         = "264842458097" -> null
      - propagating_vgws = [] -> null
      - route            = [
          - {
              - carrier_gateway_id         = ""
              - cidr_block                 = "0.0.0.0/0"
              - destination_prefix_list_id = ""
              - egress_only_gateway_id     = ""
              - gateway_id                 = "igw-0d7fc83f1a73f0cfd"
              - instance_id                = ""
              - ipv6_cidr_block            = ""
              - local_gateway_id           = ""
              - nat_gateway_id             = ""
              - network_interface_id       = ""
              - transit_gateway_id         = ""
              - vpc_endpoint_id            = ""
              - vpc_peering_connection_id  = ""
            },
        ] -> null
      - tags             = {
          - "Name" = "iac-routing-table-20220223"
        } -> null
      - tags_all         = {
          - "Name" = "iac-routing-table-20220223"
        } -> null
      - vpc_id           = "vpc-0ef1a2cf24ec0eeda" -> null
    }

  # aws_route_table_association.iac-routing-table-association will be created
+ resource "aws_route_table_association" "iac-routing-table-association" {
      + id             = (known after apply)
      + route_table_id = (known after apply)
      + subnet_id      = (known after apply)
    }

  # aws_route_table_association.iac-routing-table-association-20220223 will be destroyed
  # (because aws_route_table_association.iac-routing-table-association-20220223 is not in configuration)
- resource "aws_route_table_association" "iac-routing-table-association-20220223" {
      - id             = "rtbassoc-06c8df1d7504d8e41" -> null
      - route_table_id = "rtb-0a1e2908f34d32eb9" -> null
      - subnet_id      = "subnet-0f934a92067b0f67e" -> null
    }

  # aws_security_group.iac-security-group-20220223 will be destroyed
  # (because aws_security_group.iac-security-group-20220223 is not in configuration)
- resource "aws_security_group" "iac-security-group-20220223" {
      - arn                    = "arn:aws:ec2:ap-northeast-2:264842458097:security-group/sg-0d141357be85e3913" -> null
      - description            = "Allow CoffeeTree inbound traffic" -> null
      - egress                 = [
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = ""
              - from_port        = 0
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "-1"
              - security_groups  = []
              - self             = false
              - to_port          = 0
            },
        ] -> null
      - id                     = "sg-0d141357be85e3913" -> null
      - ingress                = [
          - {
              - cidr_blocks      = [
                  - "39.7.28.205/32",
                ]
              - description      = ""
              - from_port        = 80
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 80
            },
          - {
              - cidr_blocks      = [
                  - "39.7.28.205/32",
                ]
              - description      = "SSH"
              - from_port        = 22
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 22
            },
        ] -> null
      - name                   = "iac-security-group-20220223" -> null
      - owner_id               = "264842458097" -> null
      - revoke_rules_on_delete = false -> null
      - tags                   = {
          - "Name" = "iac-security-group-20220223"
        } -> null
      - tags_all               = {
          - "Name" = "iac-security-group-20220223"
        } -> null
      - vpc_id                 = "vpc-0ef1a2cf24ec0eeda" -> null
    }

  # aws_subnet.iac-subnet will be created
+ resource "aws_subnet" "iac-subnet" {
      + arn                                            = (known after apply)
      + assign_ipv6_address_on_creation                = false
      + availability_zone                              = (known after apply)
      + availability_zone_id                           = (known after apply)
      + cidr_block                                     = "10.0.1.0/24"
      + enable_dns64                                   = false
      + enable_resource_name_dns_a_record_on_launch    = false
      + enable_resource_name_dns_aaaa_record_on_launch = false
      + id                                             = (known after apply)
      + ipv6_cidr_block_association_id                 = (known after apply)
      + ipv6_native                                    = false
      + map_public_ip_on_launch                        = false
      + owner_id                                       = (known after apply)
      + private_dns_hostname_type_on_launch            = (known after apply)
      + tags                                           = {
          + "Name" = "iac-subnet"
        }
      + tags_all                                       = {
          + "Name" = "iac-subnet"
        }
      + vpc_id                                         = (known after apply)
    }

  # aws_subnet.iac-subnet-20220223 will be destroyed
  # (because aws_subnet.iac-subnet-20220223 is not in configuration)
- resource "aws_subnet" "iac-subnet-20220223" {
      - arn                                            = "arn:aws:ec2:ap-northeast-2:264842458097:subnet/subnet-0f934a92067b0f67e" -> null
      - assign_ipv6_address_on_creation                = false -> null
      - availability_zone                              = "ap-northeast-2b" -> null
      - availability_zone_id                           = "apne2-az2" -> null
      - cidr_block                                     = "10.0.1.0/24" -> null
      - enable_dns64                                   = false -> null
      - enable_resource_name_dns_a_record_on_launch    = false -> null
      - enable_resource_name_dns_aaaa_record_on_launch = false -> null
      - id                                             = "subnet-0f934a92067b0f67e" -> null
      - ipv6_native                                    = false -> null
      - map_customer_owned_ip_on_launch                = false -> null
      - map_public_ip_on_launch                        = false -> null
      - owner_id                                       = "264842458097" -> null
      - private_dns_hostname_type_on_launch            = "ip-name" -> null
      - tags                                           = {
          - "Name" = "iac-subnet-20220223"
        } -> null
      - tags_all                                       = {
          - "Name" = "iac-subnet-20220223"
        } -> null
      - vpc_id                                         = "vpc-0ef1a2cf24ec0eeda" -> null
    }

  # aws_vpc.iac-vpc will be created
+ resource "aws_vpc" "iac-vpc" {
      + arn                                  = (known after apply)
      + cidr_block                           = "10.0.0.0/16"
      + default_network_acl_id               = (known after apply)
      + default_route_table_id               = (known after apply)
      + default_security_group_id            = (known after apply)
      + dhcp_options_id                      = (known after apply)
      + enable_classiclink                   = (known after apply)
      + enable_classiclink_dns_support       = (known after apply)
      + enable_dns_hostnames                 = (known after apply)
      + enable_dns_support                   = true
      + id                                   = (known after apply)
      + instance_tenancy                     = "default"
      + ipv6_association_id                  = (known after apply)
      + ipv6_cidr_block                      = (known after apply)
      + ipv6_cidr_block_network_border_group = (known after apply)
      + main_route_table_id                  = (known after apply)
      + owner_id                             = (known after apply)
      + tags                                 = {
          + "Name" = "iac-vpc"
        }
      + tags_all                             = {
          + "Name" = "iac-vpc"
        }
    }

  # aws_vpc.iac-vpc-20220223 will be destroyed
  # (because aws_vpc.iac-vpc-20220223 is not in configuration)
- resource "aws_vpc" "iac-vpc-20220223" {
      - arn                              = "arn:aws:ec2:ap-northeast-2:264842458097:vpc/vpc-0ef1a2cf24ec0eeda" -> null
      - assign_generated_ipv6_cidr_block = false -> null
      - cidr_block                       = "10.0.0.0/16" -> null
      - default_network_acl_id           = "acl-05ab76d1bb8f9f880" -> null
      - default_route_table_id           = "rtb-06dd304e611efcd8f" -> null
      - default_security_group_id        = "sg-0794ffd74b1d60d42" -> null
      - dhcp_options_id                  = "dopt-0439dc969e8731205" -> null
      - enable_classiclink               = false -> null
      - enable_classiclink_dns_support   = false -> null
      - enable_dns_hostnames             = false -> null
      - enable_dns_support               = true -> null
      - id                               = "vpc-0ef1a2cf24ec0eeda" -> null
      - instance_tenancy                 = "default" -> null
      - ipv6_netmask_length              = 0 -> null
      - main_route_table_id              = "rtb-06dd304e611efcd8f" -> null
      - owner_id                         = "264842458097" -> null
      - tags                             = {
          - "Name" = "iac-vpc-20220223"
        } -> null
      - tags_all                         = {
          - "Name" = "iac-vpc-20220223"
        } -> null
    }

Plan: 5 to add, 0 to change, 9 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 5 to add, 0 to change, 9 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
Acquiring state lock. This may take a few moments...
aws_route_table_association.iac-routing-table-association-20220223: Destroying... [id=rtbassoc-06c8df1d7504d8e41]
aws_route53_record.iac-route53-20220223: Destroying... [id=Z00481431FE9EJXZFCWSO_rhea-so.com_A]
aws_vpc.iac-vpc: Creating...
aws_route_table_association.iac-routing-table-association-20220223: Destruction complete after 1s
aws_route_table.iac-routing-table-20220223: Destroying... [id=rtb-0a1e2908f34d32eb9]
aws_route_table.iac-routing-table-20220223: Destruction complete after 0s
aws_internet_gateway.iac-igw-20220223: Destroying... [id=igw-0d7fc83f1a73f0cfd]
aws_vpc.iac-vpc: Creation complete after 1s [id=vpc-0119ba5078755447e]
aws_internet_gateway.iac-igw: Creating...
aws_subnet.iac-subnet: Creating...
aws_internet_gateway.iac-igw: Creation complete after 0s [id=igw-0bddddc19e3a443b3]
aws_route_table.iac-routing-table: Creating...
aws_subnet.iac-subnet: Creation complete after 1s [id=subnet-0e75be0b66a30a3fd]
aws_route_table.iac-routing-table: Creation complete after 0s [id=rtb-0da83ad9a5908a01f]
aws_route_table_association.iac-routing-table-association: Creating...
aws_route_table_association.iac-routing-table-association: Creation complete after 0s [id=rtbassoc-08482a64b39ed3e14]
aws_route53_record.iac-route53-20220223: Still destroying... [id=Z00481431FE9EJXZFCWSO_rhea-so.com_A, 10s elapsed]
aws_internet_gateway.iac-igw-20220223: Still destroying... [id=igw-0d7fc83f1a73f0cfd, 10s elapsed]
aws_route53_record.iac-route53-20220223: Still destroying... [id=Z00481431FE9EJXZFCWSO_rhea-so.com_A, 20s elapsed]
aws_internet_gateway.iac-igw-20220223: Still destroying... [id=igw-0d7fc83f1a73f0cfd, 20s elapsed]
aws_route53_record.iac-route53-20220223: Still destroying... [id=Z00481431FE9EJXZFCWSO_rhea-so.com_A, 30s elapsed]
aws_internet_gateway.iac-igw-20220223: Still destroying... [id=igw-0d7fc83f1a73f0cfd, 30s elapsed]
aws_route53_record.iac-route53-20220223: Still destroying... [id=Z00481431FE9EJXZFCWSO_rhea-so.com_A, 40s elapsed]
aws_internet_gateway.iac-igw-20220223: Still destroying... [id=igw-0d7fc83f1a73f0cfd, 40s elapsed]
aws_route53_record.iac-route53-20220223: Still destroying... [id=Z00481431FE9EJXZFCWSO_rhea-so.com_A, 50s elapsed]
aws_internet_gateway.iac-igw-20220223: Still destroying... [id=igw-0d7fc83f1a73f0cfd, 50s elapsed]
aws_route53_record.iac-route53-20220223: Destruction complete after 54s
aws_eip.iac-eip-20220223: Destroying... [id=eipalloc-06664f8ac0365d0dd]
aws_eip.iac-eip-20220223: Destruction complete after 1s
aws_instance.iac-ec2-20220223: Destroying... [id=i-030bd725830bab8e0]
aws_internet_gateway.iac-igw-20220223: Destruction complete after 57s
aws_instance.iac-ec2-20220223: Still destroying... [id=i-030bd725830bab8e0, 10s elapsed]
aws_instance.iac-ec2-20220223: Still destroying... [id=i-030bd725830bab8e0, 20s elapsed]
aws_instance.iac-ec2-20220223: Destruction complete after 30s
aws_subnet.iac-subnet-20220223: Destroying... [id=subnet-0f934a92067b0f67e]
aws_security_group.iac-security-group-20220223: Destroying... [id=sg-0d141357be85e3913]
aws_subnet.iac-subnet-20220223: Destruction complete after 0s
aws_security_group.iac-security-group-20220223: Destruction complete after 0s
aws_vpc.iac-vpc-20220223: Destroying... [id=vpc-0ef1a2cf24ec0eeda]
aws_vpc.iac-vpc-20220223: Destruction complete after 1s

Apply complete! Resources: 5 added, 0 changed, 9 destroyed.


```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
