### PR TITLE
delete: api gateway

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # module.production.module.api-gateway.aws_api_gateway_integration.iac-api-gateway-integration-google-exit will be destroyed
  # (because aws_api_gateway_integration.iac-api-gateway-integration-google-exit is not in configuration)
- resource "aws_api_gateway_integration" "iac-api-gateway-integration-google-exit" {
      - cache_key_parameters    = [] -> null
      - cache_namespace         = "tzp9x9" -> null
      - connection_type         = "INTERNET" -> null
      - http_method             = "GET" -> null
      - id                      = "agi-kb4bj3xon8-tzp9x9-GET" -> null
      - integration_http_method = "GET" -> null
      - passthrough_behavior    = "WHEN_NO_MATCH" -> null
      - request_parameters      = {} -> null
      - request_templates       = {} -> null
      - resource_id             = "tzp9x9" -> null
      - rest_api_id             = "kb4bj3xon8" -> null
      - timeout_milliseconds    = 29000 -> null
      - type                    = "HTTP_PROXY" -> null
      - uri                     = "http://google.com" -> null
    }

  # module.production.module.api-gateway.aws_api_gateway_method.iac-api-gateway-method-google-exit will be destroyed
  # (because aws_api_gateway_method.iac-api-gateway-method-google-exit is not in configuration)
- resource "aws_api_gateway_method" "iac-api-gateway-method-google-exit" {
      - api_key_required     = false -> null
      - authorization        = "NONE" -> null
      - authorization_scopes = [] -> null
      - http_method          = "GET" -> null
      - id                   = "agm-kb4bj3xon8-tzp9x9-GET" -> null
      - request_models       = {} -> null
      - request_parameters   = {} -> null
      - resource_id          = "tzp9x9" -> null
      - rest_api_id          = "kb4bj3xon8" -> null
    }

  # module.production.module.api-gateway.aws_api_gateway_resource.iac-api-gateway-resource-google will be destroyed
  # (because aws_api_gateway_resource.iac-api-gateway-resource-google is not in configuration)
- resource "aws_api_gateway_resource" "iac-api-gateway-resource-google" {
      - id          = "4jr77i" -> null
      - parent_id   = "63hb8mjype" -> null
      - path        = "/google" -> null
      - path_part   = "google" -> null
      - rest_api_id = "kb4bj3xon8" -> null
    }

  # module.production.module.api-gateway.aws_api_gateway_resource.iac-api-gateway-resource-google-exit will be destroyed
  # (because aws_api_gateway_resource.iac-api-gateway-resource-google-exit is not in configuration)
- resource "aws_api_gateway_resource" "iac-api-gateway-resource-google-exit" {
      - id          = "tzp9x9" -> null
      - parent_id   = "4jr77i" -> null
      - path        = "/google/exit" -> null
      - path_part   = "exit" -> null
      - rest_api_id = "kb4bj3xon8" -> null
    }

  # module.production.module.api-gateway.aws_api_gateway_rest_api.iac-api-gateway will be destroyed
  # (because aws_api_gateway_rest_api.iac-api-gateway is not in configuration)
- resource "aws_api_gateway_rest_api" "iac-api-gateway" {
      - api_key_source               = "HEADER" -> null
      - arn                          = "arn:aws:apigateway:ap-northeast-2::/restapis/kb4bj3xon8" -> null
      - binary_media_types           = [] -> null
      - created_date                 = "2022-03-13T18:21:17Z" -> null
      - description                  = "Proxy to handle requests to our API" -> null
      - disable_execute_api_endpoint = false -> null
      - execution_arn                = "arn:aws:execute-api:ap-northeast-2:264842458097:kb4bj3xon8" -> null
      - id                           = "kb4bj3xon8" -> null
      - minimum_compression_size     = -1 -> null
      - name                         = "iac-api-gateway" -> null
      - root_resource_id             = "63hb8mjype" -> null
      - tags                         = {} -> null
      - tags_all                     = {} -> null

      - endpoint_configuration {
          - types            = [
              - "EDGE",
            ] -> null
          - vpc_endpoint_ids = [] -> null
        }
    }

Plan: 0 to add, 0 to change, 5 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 0 to add, 0 to change, 5 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
module.production.module.api-gateway.aws_api_gateway_integration.iac-api-gateway-integration-google-exit: Destroying... [id=agi-kb4bj3xon8-tzp9x9-GET]
module.production.module.api-gateway.aws_api_gateway_integration.iac-api-gateway-integration-google-exit: Destruction complete after 0s
module.production.module.api-gateway.aws_api_gateway_method.iac-api-gateway-method-google-exit: Destroying... [id=agm-kb4bj3xon8-tzp9x9-GET]
module.production.module.api-gateway.aws_api_gateway_method.iac-api-gateway-method-google-exit: Destruction complete after 0s
module.production.module.api-gateway.aws_api_gateway_resource.iac-api-gateway-resource-google-exit: Destroying... [id=tzp9x9]
module.production.module.api-gateway.aws_api_gateway_resource.iac-api-gateway-resource-google-exit: Destruction complete after 0s
module.production.module.api-gateway.aws_api_gateway_resource.iac-api-gateway-resource-google: Destroying... [id=4jr77i]
module.production.module.api-gateway.aws_api_gateway_resource.iac-api-gateway-resource-google: Destruction complete after 0s
module.production.module.api-gateway.aws_api_gateway_rest_api.iac-api-gateway: Destroying... [id=kb4bj3xon8]
module.production.module.api-gateway.aws_api_gateway_rest_api.iac-api-gateway: Destruction complete after 0s

Apply complete! Resources: 0 added, 0 changed, 5 destroyed.


```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
