### PR TITLE
add: route table

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_route_table.iac-routing-table has changed
~ resource "aws_route_table" "iac-routing-table" {
      + arn              = "arn:aws:ec2:ap-northeast-2:264842458097:route-table/rtb-0ee967f1124f5e44a"
        id               = "rtb-0ee967f1124f5e44a"
      + owner_id         = "264842458097"
      ~ route            = [
          - {
              - carrier_gateway_id         = ""
              - cidr_block                 = "10.0.1.0/24"
              - destination_prefix_list_id = ""
              - egress_only_gateway_id     = ""
              - gateway_id                 = "igw-0e1bd0e0ac954279d"
              - instance_id                = ""
              - ipv6_cidr_block            = ""
              - local_gateway_id           = ""
              - nat_gateway_id             = ""
              - network_interface_id       = ""
              - transit_gateway_id         = ""
              - vpc_endpoint_id            = ""
              - vpc_peering_connection_id  = ""
            },
        ]
        tags             = {
            "Name" = "iac-routing-table"
        }
        # (3 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
- destroy

Terraform will perform the following actions:

  # aws_route_table.iac-route-table will be created
+ resource "aws_route_table" "iac-route-table" {
      + arn              = (known after apply)
      + id               = (known after apply)
      + owner_id         = (known after apply)
      + propagating_vgws = (known after apply)
      + route            = [
          + {
              + carrier_gateway_id         = ""
              + cidr_block                 = "0.0.0.0/0"
              + destination_prefix_list_id = ""
              + egress_only_gateway_id     = ""
              + gateway_id                 = "igw-0e1bd0e0ac954279d"
              + instance_id                = ""
              + ipv6_cidr_block            = ""
              + local_gateway_id           = ""
              + nat_gateway_id             = ""
              + network_interface_id       = ""
              + transit_gateway_id         = ""
              + vpc_endpoint_id            = ""
              + vpc_peering_connection_id  = ""
            },
        ]
      + tags             = {
          + "Name" = "iac-route-table"
        }
      + tags_all         = {
          + "Name" = "iac-route-table"
        }
      + vpc_id           = "vpc-08dcb17c8de524b67"
    }

  # aws_route_table.iac-routing-table will be destroyed
  # (because aws_route_table.iac-routing-table is not in configuration)
- resource "aws_route_table" "iac-routing-table" {
      - arn              = "arn:aws:ec2:ap-northeast-2:264842458097:route-table/rtb-0ee967f1124f5e44a" -> null
      - id               = "rtb-0ee967f1124f5e44a" -> null
      - owner_id         = "264842458097" -> null
      - propagating_vgws = [] -> null
      - route            = [] -> null
      - tags             = {
          - "Name" = "iac-routing-table"
        } -> null
      - tags_all         = {
          - "Name" = "iac-routing-table"
        } -> null
      - vpc_id           = "vpc-08dcb17c8de524b67" -> null
    }

Plan: 1 to add, 0 to change, 1 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 1 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by rhea-so** [comment]
제발 되어라

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
aws_route_table.iac-routing-table: Destroying... [id=rtb-0ee967f1124f5e44a]
aws_route_table.iac-route-table: Creating...
aws_route_table.iac-routing-table: Destruction complete after 0s
aws_route_table.iac-route-table: Creation complete after 0s [id=rtb-0efdc44c6bfa956da]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.


```

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
