### PR TITLE
delete: api gateway

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # module.production.module.api-gateway.aws_api_gateway_integration.iac-api-gateway-integration-google-enter has changed
~ resource "aws_api_gateway_integration" "iac-api-gateway-integration-google-enter" {
      + cache_key_parameters    = []
        id                      = "agi-kb4bj3xon8-rekm5u-GET"
      + request_parameters      = {}
      + request_templates       = {}
        # (10 unchanged attributes hidden)
    }

  # module.production.module.api-gateway.aws_api_gateway_integration.iac-api-gateway-integration-google-exit has changed
~ resource "aws_api_gateway_integration" "iac-api-gateway-integration-google-exit" {
      + cache_key_parameters    = []
        id                      = "agi-kb4bj3xon8-tzp9x9-GET"
      + request_parameters      = {}
      + request_templates       = {}
        # (10 unchanged attributes hidden)
    }

  # module.production.module.api-gateway.aws_api_gateway_method.iac-api-gateway-method-google-exit has changed
~ resource "aws_api_gateway_method" "iac-api-gateway-method-google-exit" {
      + authorization_scopes = []
        id                   = "agm-kb4bj3xon8-tzp9x9-GET"
      + request_models       = {}
      + request_parameters   = {}
        # (5 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # module.production.module.api-gateway.aws_api_gateway_integration.iac-api-gateway-integration-google-enter will be destroyed
  # (because aws_api_gateway_integration.iac-api-gateway-integration-google-enter is not in configuration)
- resource "aws_api_gateway_integration" "iac-api-gateway-integration-google-enter" {
      - cache_key_parameters    = [] -> null
      - cache_namespace         = "rekm5u" -> null
      - connection_type         = "INTERNET" -> null
      - http_method             = "GET" -> null
      - id                      = "agi-kb4bj3xon8-rekm5u-GET" -> null
      - integration_http_method = "GET" -> null
      - passthrough_behavior    = "WHEN_NO_MATCH" -> null
      - request_parameters      = {} -> null
      - request_templates       = {} -> null
      - resource_id             = "rekm5u" -> null
      - rest_api_id             = "kb4bj3xon8" -> null
      - timeout_milliseconds    = 29000 -> null
      - type                    = "HTTP_PROXY" -> null
      - uri                     = "http://google.com" -> null
    }

  # module.production.module.api-gateway.aws_api_gateway_method.iac-api-gateway-method-google-enter will be destroyed
  # (because aws_api_gateway_method.iac-api-gateway-method-google-enter is not in configuration)
- resource "aws_api_gateway_method" "iac-api-gateway-method-google-enter" {
      - api_key_required     = false -> null
      - authorization        = "NONE" -> null
      - authorization_scopes = [] -> null
      - http_method          = "GET" -> null
      - id                   = "agm-kb4bj3xon8-rekm5u-GET" -> null
      - request_models       = {} -> null
      - request_parameters   = {} -> null
      - resource_id          = "rekm5u" -> null
      - rest_api_id          = "kb4bj3xon8" -> null
    }

  # module.production.module.api-gateway.aws_api_gateway_resource.iac-api-gateway-resource-google-enter will be destroyed
  # (because aws_api_gateway_resource.iac-api-gateway-resource-google-enter is not in configuration)
- resource "aws_api_gateway_resource" "iac-api-gateway-resource-google-enter" {
      - id          = "rekm5u" -> null
      - parent_id   = "4jr77i" -> null
      - path        = "/google/enter" -> null
      - path_part   = "enter" -> null
      - rest_api_id = "kb4bj3xon8" -> null
    }

Plan: 0 to add, 0 to change, 3 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 0 to add, 0 to change, 3 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
module.production.module.api-gateway.aws_api_gateway_integration.iac-api-gateway-integration-google-enter: Destroying... [id=agi-kb4bj3xon8-rekm5u-GET]
module.production.module.api-gateway.aws_api_gateway_integration.iac-api-gateway-integration-google-enter: Destruction complete after 0s
module.production.module.api-gateway.aws_api_gateway_method.iac-api-gateway-method-google-enter: Destroying... [id=agm-kb4bj3xon8-rekm5u-GET]
module.production.module.api-gateway.aws_api_gateway_method.iac-api-gateway-method-google-enter: Destruction complete after 0s
module.production.module.api-gateway.aws_api_gateway_resource.iac-api-gateway-resource-google-enter: Destroying... [id=rekm5u]
module.production.module.api-gateway.aws_api_gateway_resource.iac-api-gateway-resource-google-enter: Destruction complete after 1s

Apply complete! Resources: 0 added, 0 changed, 3 destroyed.


```

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
