### PR TITLE
Auto scaling test

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_ecr_repository.memo-ecr has changed
~ resource "aws_ecr_repository" "memo-ecr" {
        id                   = "memo-ecr"
        name                 = "memo-ecr"
      + tags                 = {}
        # (5 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }

  # aws_ecs_cluster.memo-ecs-cluster has changed
~ resource "aws_ecs_cluster" "memo-ecs-cluster" {
      ~ capacity_providers = [
          + "FARGATE",
        ]
        id                 = "arn:aws:ecs:ap-northeast-2:264842458097:cluster/memo-ecs-cluster"
        name               = "memo-ecs-cluster"
        tags               = {
            "Name" = "memo-ecs-cluster"
        }
        # (2 unchanged attributes hidden)

      + default_capacity_provider_strategy {
          + base              = 1
          + capacity_provider = "FARGATE"
          + weight            = 100
        }

        # (1 unchanged block hidden)
    }

  # aws_ecs_service.memo-ecs-service has changed
~ resource "aws_ecs_service" "memo-ecs-service" {
        id                                 = "arn:aws:ecs:ap-northeast-2:264842458097:service/memo-ecs-cluster/memo-ecs-service"
        name                               = "memo-ecs-service"
      + tags                               = {}
      ~ task_definition                    = "arn:aws:ecs:ap-northeast-2:264842458097:task-definition/memo-ecs-task-definition:21" -> "arn:aws:ecs:ap-northeast-2:264842458097:task-definition/memo-ecs-task-definition:22"
        # (14 unchanged attributes hidden)





        # (5 unchanged blocks hidden)
    }

  # aws_ecs_task_definition.memo-ecs-task-definition has changed
~ resource "aws_ecs_task_definition" "memo-ecs-task-definition" {
        id                       = "memo-ecs-task-definition"
      + tags                     = {}
        # (11 unchanged attributes hidden)
    }

  # aws_iam_role.ecs-task-execution-role has changed
~ resource "aws_iam_role" "ecs-task-execution-role" {
        id                    = "ecs-staging-execution-role"
      ~ managed_policy_arns   = [
          + "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy",
        ]
        name                  = "ecs-staging-execution-role"
      + tags                  = {}
        # (8 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # aws_lb_listener.memo-alb-listener has changed
~ resource "aws_lb_listener" "memo-alb-listener" {
        id                = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:listener/app/memo-alb/b92d4cf4de8c23d5/b4ed3608fe88fa7d"
      + tags              = {}
        # (5 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # aws_lb_target_group.memo-alb-target-group has changed
~ resource "aws_lb_target_group" "memo-alb-target-group" {
        id                                 = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/c47d1f669ad31ea7"
        name                               = "memo-alb-target-group"
      + tags                               = {}
        # (14 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }

  # aws_route53_record.memo-domain has changed
~ resource "aws_route53_record" "memo-domain" {
        id      = "Z00481431FE9EJXZFCWSO_memo.rhea-so.com_A"
        name    = "memo.rhea-so.com"
      + records = []
      + ttl     = 0
        # (3 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # aws_appautoscaling_policy.memo-ecs-autoscaling-policy-cpu will be updated in-place
~ resource "aws_appautoscaling_policy" "memo-ecs-autoscaling-policy-cpu" {
        id                 = "cpu-autoscaling"
        name               = "cpu-autoscaling"
        # (5 unchanged attributes hidden)

      ~ target_tracking_scaling_policy_configuration {
          ~ target_value       = 60 -> 30
            # (3 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }
    }

  # aws_ecs_service.memo-ecs-service will be updated in-place
~ resource "aws_ecs_service" "memo-ecs-service" {
      ~ desired_count                      = 3 -> 1
        id                                 = "arn:aws:ecs:ap-northeast-2:264842458097:service/memo-ecs-cluster/memo-ecs-service"
        name                               = "memo-ecs-service"
        tags                               = {}
      ~ task_definition                    = "arn:aws:ecs:ap-northeast-2:264842458097:task-definition/memo-ecs-task-definition:22" -> "arn:aws:ecs:ap-northeast-2:264842458097:task-definition/memo-ecs-task-definition:21"
        # (13 unchanged attributes hidden)





        # (5 unchanged blocks hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 0 to add, 2 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
aws_appautoscaling_policy.memo-ecs-autoscaling-policy-cpu: Modifying... [id=cpu-autoscaling]
aws_ecs_service.memo-ecs-service: Modifying... [id=arn:aws:ecs:ap-northeast-2:264842458097:service/memo-ecs-cluster/memo-ecs-service]
aws_ecs_service.memo-ecs-service: Modifications complete after 0s [id=arn:aws:ecs:ap-northeast-2:264842458097:service/memo-ecs-cluster/memo-ecs-service]
aws_appautoscaling_policy.memo-ecs-autoscaling-policy-cpu: Modifications complete after 0s [id=cpu-autoscaling]

Apply complete! Resources: 0 added, 2 changed, 0 destroyed.


```

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
