### PR TITLE
delete: Google

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `00_Environment/03_Production` workspace: `production`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.atlantis-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "atlantis.rhea-so.com"
      + records         = [
          + "52.78.144.248",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

  # module.rhea-so.aws_route53_zone.domain will be created
+ resource "aws_route53_zone" "domain" {
      + arn           = (known after apply)
      + comment       = "Managed by Terraform"
      + force_destroy = true
      + id            = (known after apply)
      + name          = "rhea-so.com"
      + name_servers  = (known after apply)
      + tags_all      = (known after apply)
      + zone_id       = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production -w production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fproduction)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d 00_Environment/03_Production -w production`
</details>
Plan: 2 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `00_Environment/03_Production` workspace: `production`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production -w production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fproduction)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d 00_Environment/03_Production -w production`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `00_Environment/03_Production` workspace: `production`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_route53_record.atlantis-rhea-so will be created
+ resource "aws_route53_record" "atlantis-rhea-so" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "atlantis.rhea-so.com"
      + records         = [
          + "52.78.144.248",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

  # aws_route53_zone.rhea-so will be created
+ resource "aws_route53_zone" "rhea-so" {
      + arn           = (known after apply)
      + comment       = "Managed by Terraform"
      + force_destroy = true
      + id            = (known after apply)
      + name          = "rhea-so"
      + name_servers  = (known after apply)
      + tags_all      = (known after apply)
      + zone_id       = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production -w production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fproduction)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d 00_Environment/03_Production -w production`
</details>
Plan: 2 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `00_Environment/03_Production` workspace: `production`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production -w production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fproduction)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d 00_Environment/03_Production -w production`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `00_Environment/03_Production` workspace: `production`

**Apply Error**
```
running "/usr/bin/terraform apply -input=false \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/96/production/00_Environment/03_Production/production.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/96/production/00_Environment/03_Production": exit status 1
aws_route53_zone.rhea-so: Creating...
╷
│ Error: error creating Route53 Hosted Zone: InvalidDomainName: rhea-so is reserved by AWS!
│ 	status code: 400, request id: 99df334f-1466-4f2f-beac-541959b8ea10
│ 
│   with aws_route53_zone.rhea-so,
│   on main.tf line 2, in resource "aws_route53_zone" "rhea-so":
│    2: resource "aws_route53_zone" "rhea-so" {
│ 
╵

```

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `00_Environment/03_Production` workspace: `production`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_route53_record.atlantis-rhea-so will be created
+ resource "aws_route53_record" "atlantis-rhea-so" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "atlantis.rhea-so.com"
      + records         = [
          + "52.78.144.248",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

  # aws_route53_zone.rhea-so will be created
+ resource "aws_route53_zone" "rhea-so" {
      + arn           = (known after apply)
      + comment       = "Managed by Terraform"
      + force_destroy = true
      + id            = (known after apply)
      + name          = "rhea-so.com"
      + name_servers  = (known after apply)
      + tags_all      = (known after apply)
      + zone_id       = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production -w production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fproduction)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d 00_Environment/03_Production -w production`
</details>
Plan: 2 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `00_Environment/03_Production` workspace: `production`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production -w production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fproduction)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d 00_Environment/03_Production -w production`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `00_Environment/03_Production` workspace: `production`

<details><summary>Show Output</summary>

```diff
aws_route53_zone.rhea-so: Creating...
aws_route53_zone.rhea-so: Still creating... [10s elapsed]
aws_route53_zone.rhea-so: Still creating... [20s elapsed]
aws_route53_zone.rhea-so: Still creating... [30s elapsed]
aws_route53_zone.rhea-so: Creation complete after 39s [id=Z0066789Y7PNGXVFQVQJ]
aws_route53_record.atlantis-rhea-so: Creating...
aws_route53_record.atlantis-rhea-so: Still creating... [10s elapsed]
aws_route53_record.atlantis-rhea-so: Still creating... [20s elapsed]
aws_route53_record.atlantis-rhea-so: Still creating... [30s elapsed]
aws_route53_record.atlantis-rhea-so: Still creating... [40s elapsed]
aws_route53_record.atlantis-rhea-so: Creation complete after 47s [id=Z0066789Y7PNGXVFQVQJ_atlantis.rhea-so.com_A]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.


```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `00_Environment/03_Production` workspace: `production`

**Pull request merged**
