### PR TITLE
Memo Service Test

### PR DESCRIPTION
**Pull request by rhea-so**
처음부터 끝까지 모든 리소스가 한번에 만들어지는지 확인

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_ecr_lifecycle_policy.memo-ecr-policy will be created
+ resource "aws_ecr_lifecycle_policy" "memo-ecr-policy" {
      + id          = (known after apply)
      + policy      = jsonencode(
            {
              + rules = [
                  + {
                      + action       = {
                          + type = "expire"
                        }
                      + description  = "Keep image deployed with tag latest"
                      + rulePriority = 1
                      + selection    = {
                          + countNumber   = 1
                          + countType     = "imageCountMoreThan"
                          + tagPrefixList = [
                              + "latest",
                            ]
                          + tagStatus     = "tagged"
                        }
                    },
                  + {
                      + action       = {
                          + type = "expire"
                        }
                      + description  = "Keep last 2 any images"
                      + rulePriority = 2
                      + selection    = {
                          + countNumber = 2
                          + countType   = "imageCountMoreThan"
                          + tagStatus   = "any"
                        }
                    },
                ]
            }
        )
      + registry_id = (known after apply)
      + repository  = "memo-ecr"
    }

  # aws_ecr_repository.memo-ecr will be created
+ resource "aws_ecr_repository" "memo-ecr" {
      + arn                  = (known after apply)
      + id                   = (known after apply)
      + image_tag_mutability = "MUTABLE"
      + name                 = "memo-ecr"
      + registry_id          = (known after apply)
      + repository_url       = (known after apply)
      + tags_all             = (known after apply)

      + image_scanning_configuration {
          + scan_on_push = true
        }
    }

  # aws_ecs_cluster.memo-ecs-cluster will be created
+ resource "aws_ecs_cluster" "memo-ecs-cluster" {
      + arn                = (known after apply)
      + capacity_providers = (known after apply)
      + id                 = (known after apply)
      + name               = "memo-ecs-cluster"
      + tags               = {
          + "Name" = "memo-ecs-cluster"
        }
      + tags_all           = {
          + "Name" = "memo-ecs-cluster"
        }

      + default_capacity_provider_strategy {
          + base              = (known after apply)
          + capacity_provider = (known after apply)
          + weight            = (known after apply)
        }

      + setting {
          + name  = "containerInsights"
          + value = "enabled"
        }
    }

  # aws_ecs_cluster_capacity_providers.memo-ecs-cluster-capacity-providers will be created
+ resource "aws_ecs_cluster_capacity_providers" "memo-ecs-cluster-capacity-providers" {
      + capacity_providers = [
          + "FARGATE",
        ]
      + cluster_name       = "memo-ecs-cluster"
      + id                 = (known after apply)

      + default_capacity_provider_strategy {
          + base              = 1
          + capacity_provider = "FARGATE"
          + weight            = 100
        }
    }

  # aws_ecs_service.memo-ecs-service will be created
+ resource "aws_ecs_service" "memo-ecs-service" {
      + cluster                            = (known after apply)
      + deployment_maximum_percent         = 200
      + deployment_minimum_healthy_percent = 100
      + desired_count                      = 1
      + enable_ecs_managed_tags            = false
      + enable_execute_command             = false
      + iam_role                           = (known after apply)
      + id                                 = (known after apply)
      + launch_type                        = "FARGATE"
      + name                               = "memo-ecs-service"
      + platform_version                   = (known after apply)
      + scheduling_strategy                = "REPLICA"
      + tags_all                           = (known after apply)
      + task_definition                    = (known after apply)
      + wait_for_steady_state              = false

      + load_balancer {
          + container_name   = "memo-ecs-container"
          + container_port   = 8080
          + target_group_arn = (known after apply)
        }

      + network_configuration {
          + assign_public_ip = true
          + security_groups  = (known after apply)
          + subnets          = [
              + "subnet-0b8de44bcd332b5ac",
              + "subnet-0bb6102ac68f7e016",
            ]
        }
    }

  # aws_ecs_task_definition.memo-ecs-task-definition will be created
+ resource "aws_ecs_task_definition" "memo-ecs-task-definition" {
      + arn                      = (known after apply)
      + container_definitions    = (known after apply)
      + cpu                      = "256"
      + execution_role_arn       = (known after apply)
      + family                   = "memo-ecs-task-definition"
      + id                       = (known after apply)
      + memory                   = "512"
      + network_mode             = "awsvpc"
      + requires_compatibilities = [
          + "FARGATE",
        ]
      + revision                 = (known after apply)
      + skip_destroy             = false
      + tags_all                 = (known after apply)
    }

  # aws_iam_role.ecs-task-execution-role will be created
+ resource "aws_iam_role" "ecs-task-execution-role" {
      + arn                   = (known after apply)
      + assume_role_policy    = jsonencode(
            {
              + Statement = [
                  + {
                      + Action    = "sts:AssumeRole"
                      + Effect    = "Allow"
                      + Principal = {
                          + Service = "ecs-tasks.amazonaws.com"
                        }
                      + Sid       = ""
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + create_date           = (known after apply)
      + force_detach_policies = false
      + id                    = (known after apply)
      + managed_policy_arns   = (known after apply)
      + max_session_duration  = 3600
      + name                  = "ecs-staging-execution-role"
      + name_prefix           = (known after apply)
      + path                  = "/"
      + tags_all              = (known after apply)
      + unique_id             = (known after apply)

      + inline_policy {
          + name   = (known after apply)
          + policy = (known after apply)
        }
    }

  # aws_iam_role_policy_attachment.ecs-task-execution-role will be created
+ resource "aws_iam_role_policy_attachment" "ecs-task-execution-role" {
      + id         = (known after apply)
      + policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
      + role       = "ecs-staging-execution-role"
    }

  # aws_lb.memo-alb will be created
+ resource "aws_lb" "memo-alb" {
      + arn                        = (known after apply)
      + arn_suffix                 = (known after apply)
      + desync_mitigation_mode     = "defensive"
      + dns_name                   = (known after apply)
      + drop_invalid_header_fields = false
      + enable_deletion_protection = false
      + enable_http2               = true
      + enable_waf_fail_open       = false
      + id                         = (known after apply)
      + idle_timeout               = 60
      + internal                   = (known after apply)
      + ip_address_type            = (known after apply)
      + load_balancer_type         = "application"
      + name                       = "memo-alb"
      + security_groups            = (known after apply)
      + subnets                    = [
          + "subnet-0b8de44bcd332b5ac",
          + "subnet-0bb6102ac68f7e016",
        ]
      + tags                       = {
          + "Name" = "memo-alb"
        }
      + tags_all                   = {
          + "Name" = "memo-alb"
        }
      + vpc_id                     = (known after apply)
      + zone_id                    = (known after apply)

      + subnet_mapping {
          + allocation_id        = (known after apply)
          + ipv6_address         = (known after apply)
          + outpost_id           = (known after apply)
          + private_ipv4_address = (known after apply)
          + subnet_id            = (known after apply)
        }
    }

  # aws_lb_listener.memo-alb-listener will be created
+ resource "aws_lb_listener" "memo-alb-listener" {
      + arn               = (known after apply)
      + id                = (known after apply)
      + load_balancer_arn = (known after apply)
      + port              = 80
      + protocol          = "HTTP"
      + ssl_policy        = (known after apply)
      + tags_all          = (known after apply)

      + default_action {
          + order            = (known after apply)
          + target_group_arn = (known after apply)
          + type             = "forward"
        }
    }

  # aws_lb_target_group.memo-alb-target-group will be created
+ resource "aws_lb_target_group" "memo-alb-target-group" {
      + arn                                = (known after apply)
      + arn_suffix                         = (known after apply)
      + connection_termination             = false
      + deregistration_delay               = "300"
      + id                                 = (known after apply)
      + lambda_multi_value_headers_enabled = false
      + load_balancing_algorithm_type      = (known after apply)
      + name                               = "memo-alb-target-group"
      + port                               = 8080
      + preserve_client_ip                 = (known after apply)
      + protocol                           = "HTTP"
      + protocol_version                   = (known after apply)
      + proxy_protocol_v2                  = false
      + slow_start                         = 0
      + tags_all                           = (known after apply)
      + target_type                        = "ip"
      + vpc_id                             = "vpc-0119ba5078755447e"

      + health_check {
          + enabled             = true
          + healthy_threshold   = 5
          + interval            = 10
          + matcher             = "200"
          + path                = "/"
          + port                = "traffic-port"
          + protocol            = "HTTP"
          + timeout             = 2
          + unhealthy_threshold = 5
        }

      + stickiness {
          + cookie_duration = (known after apply)
          + cookie_name     = (known after apply)
          + enabled         = (known after apply)
          + type            = (known after apply)
        }
    }

  # aws_security_group.memo-security-group will be created
+ resource "aws_security_group" "memo-security-group" {
      + arn                    = (known after apply)
      + description            = "Memo Service Security Group"
      + egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "-1"
              + security_groups  = []
              + self             = false
              + to_port          = 0
            },
        ]
      + id                     = (known after apply)
      + ingress                = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = "HTTP"
              + from_port        = 443
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 443
            },
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = "HTTP"
              + from_port        = 80
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 80
            },
          + {
              + cidr_blocks      = [
                  + "10.0.0.0/16",
                ]
              + description      = "HTTP"
              + from_port        = 8080
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 8080
            },
        ]
      + name                   = "memo-security-group"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "Name" = "memo-security-group"
        }
      + tags_all               = {
          + "Name" = "memo-security-group"
        }
      + vpc_id                 = "vpc-0119ba5078755447e"
    }

Plan: 12 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 12 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
aws_ecr_repository.memo-ecr: Creating...
aws_ecs_cluster.memo-ecs-cluster: Creating...
aws_lb_target_group.memo-alb-target-group: Creating...
aws_security_group.memo-security-group: Creating...
aws_iam_role.ecs-task-execution-role: Creating...
aws_ecr_repository.memo-ecr: Creation complete after 0s [id=memo-ecr]
aws_ecr_lifecycle_policy.memo-ecr-policy: Creating...
aws_ecr_lifecycle_policy.memo-ecr-policy: Creation complete after 0s [id=memo-ecr]
aws_lb_target_group.memo-alb-target-group: Creation complete after 0s [id=arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/99278abcd215a9ed]
aws_security_group.memo-security-group: Creation complete after 2s [id=sg-0eb350c3b10b70410]
aws_lb.memo-alb: Creating...
aws_iam_role.ecs-task-execution-role: Creation complete after 4s [id=ecs-staging-execution-role]
aws_iam_role_policy_attachment.ecs-task-execution-role: Creating...
aws_ecs_task_definition.memo-ecs-task-definition: Creating...
aws_ecs_task_definition.memo-ecs-task-definition: Creation complete after 0s [id=memo-ecs-task-definition]
aws_iam_role_policy_attachment.ecs-task-execution-role: Creation complete after 1s [id=ecs-staging-execution-role-20220224132435271200000001]
aws_ecs_cluster.memo-ecs-cluster: Still creating... [10s elapsed]
aws_ecs_cluster.memo-ecs-cluster: Creation complete after 10s [id=arn:aws:ecs:ap-northeast-2:264842458097:cluster/memo-ecs-cluster]
aws_ecs_cluster_capacity_providers.memo-ecs-cluster-capacity-providers: Creating...
aws_ecs_service.memo-ecs-service: Creating...
aws_lb.memo-alb: Still creating... [10s elapsed]
aws_ecs_cluster_capacity_providers.memo-ecs-cluster-capacity-providers: Still creating... [10s elapsed]
aws_ecs_service.memo-ecs-service: Still creating... [10s elapsed]
aws_ecs_cluster_capacity_providers.memo-ecs-cluster-capacity-providers: Creation complete after 11s [id=memo-ecs-cluster]
aws_lb.memo-alb: Still creating... [20s elapsed]
aws_ecs_service.memo-ecs-service: Still creating... [20s elapsed]
aws_lb.memo-alb: Still creating... [30s elapsed]
aws_ecs_service.memo-ecs-service: Still creating... [30s elapsed]
aws_lb.memo-alb: Still creating... [40s elapsed]
aws_ecs_service.memo-ecs-service: Still creating... [40s elapsed]
aws_lb.memo-alb: Still creating... [50s elapsed]
aws_ecs_service.memo-ecs-service: Still creating... [50s elapsed]
aws_lb.memo-alb: Still creating... [1m0s elapsed]
aws_ecs_service.memo-ecs-service: Still creating... [1m0s elapsed]
aws_lb.memo-alb: Still creating... [1m10s elapsed]
aws_ecs_service.memo-ecs-service: Still creating... [1m10s elapsed]
aws_lb.memo-alb: Still creating... [1m20s elapsed]
aws_ecs_service.memo-ecs-service: Still creating... [1m20s elapsed]
aws_lb.memo-alb: Still creating... [1m30s elapsed]
aws_ecs_service.memo-ecs-service: Still creating... [1m30s elapsed]
aws_lb.memo-alb: Still creating... [1m40s elapsed]
aws_ecs_service.memo-ecs-service: Still creating... [1m40s elapsed]
aws_lb.memo-alb: Still creating... [1m50s elapsed]
aws_ecs_service.memo-ecs-service: Still creating... [1m50s elapsed]
aws_lb.memo-alb: Still creating... [2m0s elapsed]
aws_lb.memo-alb: Creation complete after 2m2s [id=arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:loadbalancer/app/memo-alb/0ec61370de96c544]
aws_lb_listener.memo-alb-listener: Creating...
aws_lb_listener.memo-alb-listener: Creation complete after 0s [id=arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:listener/app/memo-alb/0ec61370de96c544/3b844e500fa4eab1]
aws_ecs_service.memo-ecs-service: Creation complete after 1m58s [id=arn:aws:ecs:ap-northeast-2:264842458097:service/memo-ecs-cluster/memo-ecs-service]

Apply complete! Resources: 12 added, 0 changed, 0 destroyed.


```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
