### PR TITLE
add: Memo ECS Cluster

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform plan -input=false -refresh -out \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/33/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/33/default": exit status 1
╷
│ Error: Incorrect attribute value type
│ 
│   on memo.tf line 15, in resource "aws_ecr_lifecycle_policy" "memo-ecr-policy":
│   15:   policy = {
│   16:     "rules": [
│   17:       {
│   18:         "rulePriority": 1,
│   19:         "description": "Keep image deployed with tag latest",
│   20:         "selection": {
│   21:           "tagStatus": "tagged",
│   22:           "tagPrefixList": ["latest"],
│   23:           "countType": "imageCountMoreThan",
│   24:           "countNumber": 1
│   25:         },
│   26:         "action": {
│   27:           "type": "expire"
│   28:         }
│   29:       },
│   30:       {
│   31:         "rulePriority": 2,
│   32:         "description": "Keep last 2 any images",
│   33:         "selection": {
│   34:           "tagStatus": "any",
│   35:           "countType": "imageCountMoreThan",
│   36:           "countNumber": 2
│   37:         },
│   38:         "action": {
│   39:           "type": "expire"
│   40:         }
│   41:       }
│   42:     ]
│   43:   }
│ 
│ Inappropriate value for attribute "policy": string required.
╵

```
</details>

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_ecr_lifecycle_policy.memo-ecr-policy will be created
+ resource "aws_ecr_lifecycle_policy" "memo-ecr-policy" {
      + id          = (known after apply)
      + policy      = jsonencode(
            {
              + rules = [
                  + {
                      + action       = {
                          + type = "expire"
                        }
                      + description  = "Keep image deployed with tag latest"
                      + rulePriority = 1
                      + selection    = {
                          + countNumber   = 1
                          + countType     = "imageCountMoreThan"
                          + tagPrefixList = [
                              + "latest",
                            ]
                          + tagStatus     = "tagged"
                        }
                    },
                  + {
                      + action       = {
                          + type = "expire"
                        }
                      + description  = "Keep last 2 any images"
                      + rulePriority = 2
                      + selection    = {
                          + countNumber = 2
                          + countType   = "imageCountMoreThan"
                          + tagStatus   = "any"
                        }
                    },
                ]
            }
        )
      + registry_id = (known after apply)
      + repository  = "memo-ecr"
    }

  # aws_ecs_cluster.memo-ecs-cluster will be created
+ resource "aws_ecs_cluster" "memo-ecs-cluster" {
      + arn                = (known after apply)
      + capacity_providers = (known after apply)
      + id                 = (known after apply)
      + name               = "memo-ecs-cluster"
      + tags               = {
          + "Name" = "memo-ecs-cluster"
        }
      + tags_all           = {
          + "Name" = "memo-ecs-cluster"
        }

      + default_capacity_provider_strategy {
          + base              = (known after apply)
          + capacity_provider = (known after apply)
          + weight            = (known after apply)
        }

      + setting {
          + name  = "containerInsights"
          + value = "enabled"
        }
    }

  # aws_security_group.memo-security-group will be created
+ resource "aws_security_group" "memo-security-group" {
      + arn                    = (known after apply)
      + description            = "Memo Service Security Group"
      + egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "-1"
              + security_groups  = []
              + self             = false
              + to_port          = 0
            },
        ]
      + id                     = (known after apply)
      + ingress                = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = "HTTP"
              + from_port        = 80
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 80
            },
        ]
      + name                   = "memo-security-group"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "Name" = "memo-security-group"
        }
      + tags_all               = {
          + "Name" = "memo-security-group"
        }
      + vpc_id                 = "vpc-0119ba5078755447e"
    }

Plan: 3 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 3 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
aws_ecr_lifecycle_policy.memo-ecr-policy: Creating...
aws_ecs_cluster.memo-ecs-cluster: Creating...
aws_security_group.memo-security-group: Creating...
aws_ecr_lifecycle_policy.memo-ecr-policy: Creation complete after 0s [id=memo-ecr]
aws_security_group.memo-security-group: Creation complete after 2s [id=sg-06f64f1a2a42dfc63]
aws_ecs_cluster.memo-ecs-cluster: Still creating... [10s elapsed]
aws_ecs_cluster.memo-ecs-cluster: Creation complete after 10s [id=arn:aws:ecs:ap-northeast-2:264842458097:cluster/memo-ecs-cluster]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.


```

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
