### PR TITLE
fix: Route53

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
- destroy
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.rhea-so.aws_route53_zone.domain will be created
+ resource "aws_route53_zone" "domain" {
      + arn           = (known after apply)
      + comment       = "Managed by Terraform"
      + force_destroy = false
      + id            = (known after apply)
      + name          = "rhea-so.com"
      + name_servers  = (known after apply)
      + tags_all      = (known after apply)
      + zone_id       = (known after apply)
    }

  # module.production.module.atlantis-rhea-so.aws_route53_record.domain must be replaced
-/+ resource "aws_route53_record" "domain" {
      ~ fqdn            = "atlantis.rhea-so.com" -> (known after apply)
      ~ id              = "Z007496927OLC0YXP6DHX_atlantis.rhea-so.com_A" -> (known after apply)
        name            = "atlantis.rhea-so.com"
      ~ zone_id         = "Z007496927OLC0YXP6DHX" -> (known after apply) # forces replacement
        # (4 unchanged attributes hidden)
    }

  # module.production.module.rhea-so.aws_route53_zone.domain will be destroyed
  # (because aws_route53_zone.domain is not in configuration)
- resource "aws_route53_zone" "domain" {
      - arn           = "arn:aws:route53:::hostedzone/Z007496927OLC0YXP6DHX" -> null
      - comment       = "Managed by Terraform" -> null
      - force_destroy = false -> null
      - id            = "Z007496927OLC0YXP6DHX" -> null
      - name          = "rhea-so.com" -> null
      - name_servers  = [
          - "ns-1158.awsdns-16.org",
          - "ns-1997.awsdns-57.co.uk",
          - "ns-73.awsdns-09.com",
          - "ns-811.awsdns-37.net",
        ] -> null
      - tags          = {} -> null
      - tags_all      = {} -> null
      - zone_id       = "Z007496927OLC0YXP6DHX" -> null
    }

Plan: 2 to add, 0 to change, 2 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 2 to add, 0 to change, 2 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
module.production.module.atlantis-rhea-so.aws_route53_record.domain: Destroying... [id=Z007496927OLC0YXP6DHX_atlantis.rhea-so.com_A]
module.production.module.atlantis-rhea-so.aws_route53_record.domain: Still destroying... [id=Z007496927OLC0YXP6DHX_atlantis.rhea-so.com_A, 10s elapsed]
module.production.module.atlantis-rhea-so.aws_route53_record.domain: Still destroying... [id=Z007496927OLC0YXP6DHX_atlantis.rhea-so.com_A, 20s elapsed]
module.production.module.atlantis-rhea-so.aws_route53_record.domain: Still destroying... [id=Z007496927OLC0YXP6DHX_atlantis.rhea-so.com_A, 30s elapsed]
module.production.module.atlantis-rhea-so.aws_route53_record.domain: Destruction complete after 36s
module.production.module.rhea-so.aws_route53_zone.domain: Destroying... [id=Z007496927OLC0YXP6DHX]
module.rhea-so.aws_route53_zone.domain: Creating...
module.production.module.rhea-so.aws_route53_zone.domain: Destruction complete after 1s
module.rhea-so.aws_route53_zone.domain: Still creating... [10s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [20s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [30s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [40s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [50s elapsed]
module.rhea-so.aws_route53_zone.domain: Creation complete after 55s [id=Z0097287UVNCC6G4O03H]
module.production.module.atlantis-rhea-so.aws_route53_record.domain: Creating...
module.production.module.atlantis-rhea-so.aws_route53_record.domain: Still creating... [10s elapsed]
module.production.module.atlantis-rhea-so.aws_route53_record.domain: Still creating... [20s elapsed]
module.production.module.atlantis-rhea-so.aws_route53_record.domain: Still creating... [30s elapsed]
module.production.module.atlantis-rhea-so.aws_route53_record.domain: Creation complete after 38s [id=Z0097287UVNCC6G4O03H_atlantis.rhea-so.com_A]

Apply complete! Resources: 2 added, 0 changed, 2 destroyed.


```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
