### PR TITLE
delete: route 53

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by rhea-so** [comment]
atlantis help

**Comment by AyameNakiri** [comment]
```cmake
atlantis
Terraform Pull Request Automation

Usage:
  atlantis <command> [options] -- [terraform options]

Examples:
  # run plan in the root directory passing the -target flag to terraform
  atlantis plan -d . -- -target=resource

  # apply all unapplied plans from this pull request
  atlantis apply

  # apply the plan for the root directory and staging workspace
  atlantis apply -d . -w staging

Commands:
  plan     Runs 'terraform plan' for the changes in this pull request.
           To plan a specific project, use the -d, -w and -p flags.
  apply    Runs 'terraform apply' on all unapplied plans from this pull request.
           To only apply a specific plan, use the -d, -w and -p flags.
  unlock   Removes all atlantis locks and discards all plans for this PR.
           To unlock a specific plan you can use the Atlantis UI.
  approve_policies
           Approves all current policy checking failures for the PR.
  version  Print the output of 'terraform version'
  help     View help.

Flags:
  -h, --help   help for atlantis

Use "atlantis [command] --help" for more information about a command.
```

**Comment by rhea-so** [comment]
atlantis plan

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # aws_route53_zone.rhea-so will be destroyed
  # (because aws_route53_zone.rhea-so is not in configuration)
- resource "aws_route53_zone" "rhea-so" {
      - arn           = "arn:aws:route53:::hostedzone/Z00481431FE9EJXZFCWSO" -> null
      - comment       = "Managed by Terraform" -> null
      - force_destroy = false -> null
      - id            = "Z00481431FE9EJXZFCWSO" -> null
      - name          = "rhea-so.com" -> null
      - name_servers  = [
          - "ns-1402.awsdns-47.org",
          - "ns-1840.awsdns-38.co.uk",
          - "ns-391.awsdns-48.com",
          - "ns-600.awsdns-11.net",
        ] -> null
      - tags          = {} -> null
      - tags_all      = {} -> null
      - zone_id       = "Z00481431FE9EJXZFCWSO" -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 0 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis help

**Comment by rhea-so** [comment]
atlantis help

**Comment by rhea-so** [comment]
atlantis help

**Comment by rhea-so** [comment]
atlantis help

**Comment by rhea-so** [comment]
atlantis help

**Comment by AyameNakiri** [comment]
```cmake
atlantis
Terraform Pull Request Automation

Usage:
  atlantis <command> [options] -- [terraform options]

Examples:
  # run plan in the root directory passing the -target flag to terraform
  atlantis plan -d . -- -target=resource

  # apply all unapplied plans from this pull request
  atlantis apply

  # apply the plan for the root directory and staging workspace
  atlantis apply -d . -w staging

Commands:
  plan     Runs 'terraform plan' for the changes in this pull request.
           To plan a specific project, use the -d, -w and -p flags.
  apply    Runs 'terraform apply' on all unapplied plans from this pull request.
           To only apply a specific plan, use the -d, -w and -p flags.
  unlock   Removes all atlantis locks and discards all plans for this PR.
           To unlock a specific plan you can use the Atlantis UI.
  approve_policies
           Approves all current policy checking failures for the PR.
  version  Print the output of 'terraform version'
  help     View help.

Flags:
  -h, --help   help for atlantis

Use "atlantis [command] --help" for more information about a command.
```

**Comment by rhea-so** [comment]
atlantis plan

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/bin/terraform init -input=false -upgrade" in "/root/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/63/default": exit status 1

Initializing the backend...
╷
│ Error: Required token could not be found
│ 
│ Run the following command to generate a token for app.terraform.io:
│     terraform login
╵


```

**Comment by rhea-so** [comment]
atlantis plan

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/bin/terraform init -input=false -upgrade" in "/root/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/63/default": exit status 1

Initializing the backend...
╷
│ Error: Required token could not be found
│ 
│ Run the following command to generate a token for app.terraform.io:
│     terraform login
╵


```

**Comment by rhea-so** [comment]
atlantis plan

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/bin/terraform init -input=false -upgrade" in "/root/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/63/default": exit status 1

Initializing the backend...
╷
│ Error: Required token could not be found
│ 
│ Run the following command to generate a token for app.terraform.io:
│     terraform login
╵


```

**Comment by rhea-so** [comment]
atlantis plan

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform plan -input=false -refresh -out \"/root/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/63/default/default.tfplan\"" in "/root/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/63/default": exit status 1
╷
│ Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
│ 
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│ 
│ Error: NoCredentialProviders: no valid providers in chain
│ caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
│ SharedCredsLoad: failed to load profile, default.
│ EC2RoleRequestError: no EC2 instance role found
│ caused by: EC2MetadataError: failed to make EC2Metadata request
│ <?xml version="1.0" encoding="iso-8859-1"?>
│ <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
│ 		 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
│ <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
│  <head>
│   <title>404 - Not Found</title>
│  </head>
│  <body>
│   <h1>404 - Not Found</h1>
│  </body>
│ </html>
│ 
│ 	status code: 404, request id: 
│ 
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on provider.tf line 19, in provider "aws":
│   19: provider "aws" {
│ 
╵

```
</details>

**Comment by rhea-so** [comment]
atlantis plan

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform plan -input=false -refresh -out \"/root/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/63/default/default.tfplan\"" in "/root/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/63/default": exit status 1
╷
│ Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
│ 
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│ 
│ Error: NoCredentialProviders: no valid providers in chain
│ caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
│ SharedCredsLoad: failed to load profile, default.
│ EC2RoleRequestError: no EC2 instance role found
│ caused by: EC2MetadataError: failed to make EC2Metadata request
│ <?xml version="1.0" encoding="iso-8859-1"?>
│ <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
│ 		 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
│ <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
│  <head>
│   <title>404 - Not Found</title>
│  </head>
│  <body>
│   <h1>404 - Not Found</h1>
│  </body>
│ </html>
│ 
│ 	status code: 404, request id: 
│ 
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on provider.tf line 19, in provider "aws":
│   19: provider "aws" {
│ 
╵

```
</details>

**Comment by rhea-so** [comment]
atlantis plan

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # aws_route53_zone.rhea-so will be destroyed
  # (because aws_route53_zone.rhea-so is not in configuration)
- resource "aws_route53_zone" "rhea-so" {
      - arn           = "arn:aws:route53:::hostedzone/Z00481431FE9EJXZFCWSO" -> null
      - comment       = "Managed by Terraform" -> null
      - force_destroy = false -> null
      - id            = "Z00481431FE9EJXZFCWSO" -> null
      - name          = "rhea-so.com" -> null
      - name_servers  = [
          - "ns-1402.awsdns-47.org",
          - "ns-1840.awsdns-38.co.uk",
          - "ns-391.awsdns-48.com",
          - "ns-600.awsdns-11.net",
        ] -> null
      - tags          = {} -> null
      - tags_all      = {} -> null
      - zone_id       = "Z00481431FE9EJXZFCWSO" -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 0 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
와 ㅠㅠㅠ 드디어 된다 ㅠㅠ

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
aws_route53_zone.rhea-so: Destroying... [id=Z00481431FE9EJXZFCWSO]
aws_route53_zone.rhea-so: Destruction complete after 1s

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.


```

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
