### PR TITLE
delete: RabbitMQ

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_mq_broker.rabbitmq has changed
~ resource "aws_mq_broker" "rabbitmq" {
        id                         = "b-6b70b3cf-9401-4f4d-85e3-9f18b9044b91"
      + security_groups            = []
      + tags                       = {}
        # (14 unchanged attributes hidden)




      - user {
          - console_access = false -> null
          - groups         = [] -> null
          - password       = (sensitive value)
          - username       = "rhea-so" -> null
        }
        # (3 unchanged blocks hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # aws_mq_broker.rabbitmq will be destroyed
  # (because aws_mq_broker.rabbitmq is not in configuration)
- resource "aws_mq_broker" "rabbitmq" {
      - apply_immediately          = false -> null
      - arn                        = "arn:aws:mq:ap-northeast-2:264842458097:broker:rabbitmq:b-6b70b3cf-9401-4f4d-85e3-9f18b9044b91" -> null
      - authentication_strategy    = "simple" -> null
      - auto_minor_version_upgrade = false -> null
      - broker_name                = "rabbitmq" -> null
      - deployment_mode            = "SINGLE_INSTANCE" -> null
      - engine_type                = "RabbitMQ" -> null
      - engine_version             = "3.8.6" -> null
      - host_instance_type         = "mq.t3.micro" -> null
      - id                         = "b-6b70b3cf-9401-4f4d-85e3-9f18b9044b91" -> null
      - instances                  = [
          - {
              - console_url = "https://b-6b70b3cf-9401-4f4d-85e3-9f18b9044b91.mq.ap-northeast-2.amazonaws.com"
              - endpoints   = [
                  - "amqps://b-6b70b3cf-9401-4f4d-85e3-9f18b9044b91.mq.ap-northeast-2.amazonaws.com:5671",
                ]
              - ip_address  = ""
            },
        ] -> null
      - publicly_accessible        = true -> null
      - security_groups            = [] -> null
      - storage_type               = "ebs" -> null
      - subnet_ids                 = [
          - "subnet-0bb6102ac68f7e016",
        ] -> null
      - tags                       = {} -> null
      - tags_all                   = {} -> null

      - encryption_options {
          - use_aws_owned_key = true -> null
        }

      - logs {
          - general = false -> null
        }

      - maintenance_window_start_time {
          - day_of_week = "TUESDAY" -> null
          - time_of_day = "18:00" -> null
          - time_zone   = "UTC" -> null
        }
    }

  # aws_security_group.rabbitmq-security-group will be destroyed
  # (because aws_security_group.rabbitmq-security-group is not in configuration)
- resource "aws_security_group" "rabbitmq-security-group" {
      - arn                    = "arn:aws:ec2:ap-northeast-2:264842458097:security-group/sg-05abf5b39ed51fe93" -> null
      - description            = "Allow RabbitMQ inbound traffic" -> null
      - egress                 = [
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = ""
              - from_port        = 0
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "-1"
              - security_groups  = []
              - self             = false
              - to_port          = 0
            },
        ] -> null
      - id                     = "sg-05abf5b39ed51fe93" -> null
      - ingress                = [
          - {
              - cidr_blocks      = [
                  - "39.7.24.115/32",
                ]
              - description      = "SSH"
              - from_port        = 22
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 22
            },
        ] -> null
      - name                   = "rabbitmq-security-group" -> null
      - owner_id               = "264842458097" -> null
      - revoke_rules_on_delete = false -> null
      - tags                   = {
          - "Name" = "rabbitmq-security-group"
        } -> null
      - tags_all               = {
          - "Name" = "rabbitmq-security-group"
        } -> null
      - vpc_id                 = "vpc-0119ba5078755447e" -> null
    }

Plan: 0 to add, 0 to change, 2 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 0 to add, 0 to change, 2 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
aws_security_group.rabbitmq-security-group: Destroying... [id=sg-05abf5b39ed51fe93]
aws_mq_broker.rabbitmq: Destroying... [id=b-6b70b3cf-9401-4f4d-85e3-9f18b9044b91]
aws_security_group.rabbitmq-security-group: Destruction complete after 0s
aws_mq_broker.rabbitmq: Still destroying... [id=b-6b70b3cf-9401-4f4d-85e3-9f18b9044b91, 10s elapsed]
aws_mq_broker.rabbitmq: Still destroying... [id=b-6b70b3cf-9401-4f4d-85e3-9f18b9044b91, 20s elapsed]
aws_mq_broker.rabbitmq: Still destroying... [id=b-6b70b3cf-9401-4f4d-85e3-9f18b9044b91, 30s elapsed]
aws_mq_broker.rabbitmq: Still destroying... [id=b-6b70b3cf-9401-4f4d-85e3-9f18b9044b91, 40s elapsed]
aws_mq_broker.rabbitmq: Still destroying... [id=b-6b70b3cf-9401-4f4d-85e3-9f18b9044b91, 50s elapsed]
aws_mq_broker.rabbitmq: Still destroying... [id=b-6b70b3cf-9401-4f4d-85e3-9f18b9044b91, 1m0s elapsed]
aws_mq_broker.rabbitmq: Destruction complete after 1m4s

Apply complete! Resources: 0 added, 0 changed, 2 destroyed.


```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
