### PR TITLE
delete: all environment

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # module.production.module.vpc.aws_vpc.vpc will be destroyed
  # (because aws_vpc.vpc is not in configuration)
- resource "aws_vpc" "vpc" {
      - arn                              = "arn:aws:ec2:ap-northeast-2:264842458097:vpc/vpc-00d8aeee3029369cc" -> null
      - assign_generated_ipv6_cidr_block = false -> null
      - cidr_block                       = "10.0.0.0/16" -> null
      - default_network_acl_id           = "acl-01cb046dfae9a2bbf" -> null
      - default_route_table_id           = "rtb-006c0c43b219e0071" -> null
      - default_security_group_id        = "sg-062de3e9b70d07175" -> null
      - dhcp_options_id                  = "dopt-0439dc969e8731205" -> null
      - enable_classiclink               = false -> null
      - enable_classiclink_dns_support   = false -> null
      - enable_dns_hostnames             = false -> null
      - enable_dns_support               = true -> null
      - id                               = "vpc-00d8aeee3029369cc" -> null
      - instance_tenancy                 = "default" -> null
      - ipv6_netmask_length              = 0 -> null
      - main_route_table_id              = "rtb-006c0c43b219e0071" -> null
      - owner_id                         = "264842458097" -> null
      - tags                             = {
          - "Name" = "production-vpc"
        } -> null
      - tags_all                         = {
          - "Name" = "production-vpc"
        } -> null
    }

  # module.staging.module.staging-vpc.aws_vpc.vpc will be destroyed
  # (because aws_vpc.vpc is not in configuration)
- resource "aws_vpc" "vpc" {
      - arn                              = "arn:aws:ec2:ap-northeast-2:264842458097:vpc/vpc-04d25ff670001c798" -> null
      - assign_generated_ipv6_cidr_block = false -> null
      - cidr_block                       = "10.0.0.0/16" -> null
      - default_network_acl_id           = "acl-0b03ef49d9895bae0" -> null
      - default_route_table_id           = "rtb-0c531c340336202ee" -> null
      - default_security_group_id        = "sg-0a875fbe7092cc24d" -> null
      - dhcp_options_id                  = "dopt-0439dc969e8731205" -> null
      - enable_classiclink               = false -> null
      - enable_classiclink_dns_support   = false -> null
      - enable_dns_hostnames             = false -> null
      - enable_dns_support               = true -> null
      - id                               = "vpc-04d25ff670001c798" -> null
      - instance_tenancy                 = "default" -> null
      - ipv6_netmask_length              = 0 -> null
      - main_route_table_id              = "rtb-0c531c340336202ee" -> null
      - owner_id                         = "264842458097" -> null
      - tags                             = {
          - "Name" = "staging-vpc"
        } -> null
      - tags_all                         = {
          - "Name" = "staging-vpc"
        } -> null
    }

Plan: 0 to add, 0 to change, 2 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 0 to add, 0 to change, 2 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
module.production.module.vpc.aws_vpc.vpc: Destroying... [id=vpc-00d8aeee3029369cc]
module.staging.module.staging-vpc.aws_vpc.vpc: Destroying... [id=vpc-04d25ff670001c798]
module.staging.module.staging-vpc.aws_vpc.vpc: Destruction complete after 1s
module.production.module.vpc.aws_vpc.vpc: Destruction complete after 1s

Apply complete! Resources: 0 added, 0 changed, 2 destroyed.


```

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
