### PR TITLE
add: routing table

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_eip.stage_server has changed
~ resource "aws_eip" "stage_server" {
        id                   = "eipalloc-0b75e301a5b3e6534"
      + tags                 = {}
        # (13 unchanged attributes hidden)
    }

  # aws_instance.stage_server has changed
~ resource "aws_instance" "stage_server" {
      ~ associate_public_ip_address          = false -> true
        id                                   = "i-0abdca8a9d70c1957"
      + public_ip                            = "3.35.1.46"
        tags                                 = {
            "Name" = "stage_server"
        }
        # (26 unchanged attributes hidden)





        # (5 unchanged blocks hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_route_table.iac-routing-table will be created
+ resource "aws_route_table" "iac-routing-table" {
      + arn              = (known after apply)
      + id               = (known after apply)
      + owner_id         = (known after apply)
      + propagating_vgws = (known after apply)
      + route            = [
          + {
              + carrier_gateway_id         = ""
              + cidr_block                 = "10.0.1.0/24"
              + destination_prefix_list_id = ""
              + egress_only_gateway_id     = ""
              + gateway_id                 = "igw-0e1bd0e0ac954279d"
              + instance_id                = ""
              + ipv6_cidr_block            = ""
              + local_gateway_id           = ""
              + nat_gateway_id             = ""
              + network_interface_id       = ""
              + transit_gateway_id         = ""
              + vpc_endpoint_id            = ""
              + vpc_peering_connection_id  = ""
            },
        ]
      + tags             = {
          + "Name" = "iac-routing-table"
        }
      + tags_all         = {
          + "Name" = "iac-routing-table"
        }
      + vpc_id           = "vpc-08dcb17c8de524b67"
    }

Plan: 1 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

**Apply Error**
```
running "/usr/bin/terraform apply -input=false \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/21/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/21/default": exit status 1
aws_route_table.iac-routing-table: Creating...
╷
│ Error: error creating Route in Route Table (rtb-0ee967f1124f5e44a) with destination (10.0.1.0/24): InvalidParameterValue: The destination CIDR block 10.0.1.0/24 is equal to or more specific than one of this VPC's CIDR blocks. This route can target only an interface or an instance.
│ 	status code: 400, request id: a3d59ad7-7b79-4914-83d6-8c97afa6568b
│ 
│   with aws_route_table.iac-routing-table,
│   on routing_table.tf line 1, in resource "aws_route_table" "iac-routing-table":
│    1: resource "aws_route_table" "iac-routing-table" {
│ 
╵

```

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_route_table.iac-routing-table has changed
~ resource "aws_route_table" "iac-routing-table" {
      + arn              = "arn:aws:ec2:ap-northeast-2:264842458097:route-table/rtb-0ee967f1124f5e44a"
        id               = "rtb-0ee967f1124f5e44a"
      + owner_id         = "264842458097"
      ~ route            = [
          - {
              - carrier_gateway_id         = ""
              - cidr_block                 = "10.0.1.0/24"
              - destination_prefix_list_id = ""
              - egress_only_gateway_id     = ""
              - gateway_id                 = "igw-0e1bd0e0ac954279d"
              - instance_id                = ""
              - ipv6_cidr_block            = ""
              - local_gateway_id           = ""
              - nat_gateway_id             = ""
              - network_interface_id       = ""
              - transit_gateway_id         = ""
              - vpc_endpoint_id            = ""
              - vpc_peering_connection_id  = ""
            },
        ]
        tags             = {
            "Name" = "iac-routing-table"
        }
        # (3 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # aws_route_table.iac-routing-table is tainted, so must be replaced
-/+ resource "aws_route_table" "iac-routing-table" {
      ~ arn              = "arn:aws:ec2:ap-northeast-2:264842458097:route-table/rtb-0ee967f1124f5e44a" -> (known after apply)
      ~ id               = "rtb-0ee967f1124f5e44a" -> (known after apply)
      ~ owner_id         = "264842458097" -> (known after apply)
      ~ propagating_vgws = [] -> (known after apply)
      ~ route            = [
          + {
              + carrier_gateway_id         = ""
              + cidr_block                 = "0.0.0.0/0"
              + destination_prefix_list_id = ""
              + egress_only_gateway_id     = ""
              + gateway_id                 = "igw-0e1bd0e0ac954279d"
              + instance_id                = ""
              + ipv6_cidr_block            = ""
              + local_gateway_id           = ""
              + nat_gateway_id             = ""
              + network_interface_id       = ""
              + transit_gateway_id         = ""
              + vpc_endpoint_id            = ""
              + vpc_peering_connection_id  = ""
            },
        ]
        tags             = {
            "Name" = "iac-routing-table"
        }
        # (2 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 1 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
**Apply Error**
```
The Atlantis working dir is currently locked by another command that is running for this pull request.
Wait until the previous command is complete and try again.
```

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis unlock

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
**Apply Error**
```
checking if workspace exists: stat /home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/21/default: no such file or directory
```

**Comment by AyameNakiri** [comment]
```
Error: unknown command "destroy".
Run 'atlantis --help' for usage.
```

**Pull request merged**
