### PR TITLE
fix: directroy structure

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # aws_internet_gateway.iac-igw will be destroyed
  # (because aws_internet_gateway.iac-igw is not in configuration)
- resource "aws_internet_gateway" "iac-igw" {
      - arn      = "arn:aws:ec2:ap-northeast-2:264842458097:internet-gateway/igw-0bddddc19e3a443b3" -> null
      - id       = "igw-0bddddc19e3a443b3" -> null
      - owner_id = "264842458097" -> null
      - tags     = {
          - "Name" = "iac-igw"
        } -> null
      - tags_all = {
          - "Name" = "iac-igw"
        } -> null
      - vpc_id   = "vpc-0119ba5078755447e" -> null
    }

  # aws_route_table.iac-routing-table will be destroyed
  # (because aws_route_table.iac-routing-table is not in configuration)
- resource "aws_route_table" "iac-routing-table" {
      - arn              = "arn:aws:ec2:ap-northeast-2:264842458097:route-table/rtb-0da83ad9a5908a01f" -> null
      - id               = "rtb-0da83ad9a5908a01f" -> null
      - owner_id         = "264842458097" -> null
      - propagating_vgws = [] -> null
      - route            = [
          - {
              - carrier_gateway_id         = ""
              - cidr_block                 = "0.0.0.0/0"
              - destination_prefix_list_id = ""
              - egress_only_gateway_id     = ""
              - gateway_id                 = "igw-0bddddc19e3a443b3"
              - instance_id                = ""
              - ipv6_cidr_block            = ""
              - local_gateway_id           = ""
              - nat_gateway_id             = ""
              - network_interface_id       = ""
              - transit_gateway_id         = ""
              - vpc_endpoint_id            = ""
              - vpc_peering_connection_id  = ""
            },
        ] -> null
      - tags             = {
          - "Name" = "iac-routing-table"
        } -> null
      - tags_all         = {
          - "Name" = "iac-routing-table"
        } -> null
      - vpc_id           = "vpc-0119ba5078755447e" -> null
    }

  # aws_route_table_association.iac-routing-table-association-1 will be destroyed
  # (because aws_route_table_association.iac-routing-table-association-1 is not in configuration)
- resource "aws_route_table_association" "iac-routing-table-association-1" {
      - id             = "rtbassoc-050b8de7698e5dee8" -> null
      - route_table_id = "rtb-0da83ad9a5908a01f" -> null
      - subnet_id      = "subnet-0bb6102ac68f7e016" -> null
    }

  # aws_route_table_association.iac-routing-table-association-2 will be destroyed
  # (because aws_route_table_association.iac-routing-table-association-2 is not in configuration)
- resource "aws_route_table_association" "iac-routing-table-association-2" {
      - id             = "rtbassoc-09baaf5639e061758" -> null
      - route_table_id = "rtb-0da83ad9a5908a01f" -> null
      - subnet_id      = "subnet-0b8de44bcd332b5ac" -> null
    }

  # aws_subnet.iac-subnet-1 will be destroyed
  # (because aws_subnet.iac-subnet-1 is not in configuration)
- resource "aws_subnet" "iac-subnet-1" {
      - arn                                            = "arn:aws:ec2:ap-northeast-2:264842458097:subnet/subnet-0bb6102ac68f7e016" -> null
      - assign_ipv6_address_on_creation                = false -> null
      - availability_zone                              = "ap-northeast-2a" -> null
      - availability_zone_id                           = "apne2-az1" -> null
      - cidr_block                                     = "10.0.3.0/24" -> null
      - enable_dns64                                   = false -> null
      - enable_resource_name_dns_a_record_on_launch    = false -> null
      - enable_resource_name_dns_aaaa_record_on_launch = false -> null
      - id                                             = "subnet-0bb6102ac68f7e016" -> null
      - ipv6_native                                    = false -> null
      - map_customer_owned_ip_on_launch                = false -> null
      - map_public_ip_on_launch                        = false -> null
      - owner_id                                       = "264842458097" -> null
      - private_dns_hostname_type_on_launch            = "ip-name" -> null
      - tags                                           = {
          - "Name" = "iac-subnet-1"
        } -> null
      - tags_all                                       = {
          - "Name" = "iac-subnet-1"
        } -> null
      - vpc_id                                         = "vpc-0119ba5078755447e" -> null
    }

  # aws_subnet.iac-subnet-2 will be destroyed
  # (because aws_subnet.iac-subnet-2 is not in configuration)
- resource "aws_subnet" "iac-subnet-2" {
      - arn                                            = "arn:aws:ec2:ap-northeast-2:264842458097:subnet/subnet-0b8de44bcd332b5ac" -> null
      - assign_ipv6_address_on_creation                = false -> null
      - availability_zone                              = "ap-northeast-2c" -> null
      - availability_zone_id                           = "apne2-az3" -> null
      - cidr_block                                     = "10.0.4.0/24" -> null
      - enable_dns64                                   = false -> null
      - enable_resource_name_dns_a_record_on_launch    = false -> null
      - enable_resource_name_dns_aaaa_record_on_launch = false -> null
      - id                                             = "subnet-0b8de44bcd332b5ac" -> null
      - ipv6_native                                    = false -> null
      - map_customer_owned_ip_on_launch                = false -> null
      - map_public_ip_on_launch                        = false -> null
      - owner_id                                       = "264842458097" -> null
      - private_dns_hostname_type_on_launch            = "ip-name" -> null
      - tags                                           = {
          - "Name" = "iac-subnet-2"
        } -> null
      - tags_all                                       = {
          - "Name" = "iac-subnet-2"
        } -> null
      - vpc_id                                         = "vpc-0119ba5078755447e" -> null
    }

  # aws_vpc.iac-vpc will be destroyed
  # (because aws_vpc.iac-vpc is not in configuration)
- resource "aws_vpc" "iac-vpc" {
      - arn                              = "arn:aws:ec2:ap-northeast-2:264842458097:vpc/vpc-0119ba5078755447e" -> null
      - assign_generated_ipv6_cidr_block = false -> null
      - cidr_block                       = "10.0.0.0/16" -> null
      - default_network_acl_id           = "acl-0483282775e9f8f7e" -> null
      - default_route_table_id           = "rtb-07926b43d726e7a02" -> null
      - default_security_group_id        = "sg-081e6ec7d341eb8c5" -> null
      - dhcp_options_id                  = "dopt-0439dc969e8731205" -> null
      - enable_classiclink               = false -> null
      - enable_classiclink_dns_support   = false -> null
      - enable_dns_hostnames             = false -> null
      - enable_dns_support               = true -> null
      - id                               = "vpc-0119ba5078755447e" -> null
      - instance_tenancy                 = "default" -> null
      - ipv6_netmask_length              = 0 -> null
      - main_route_table_id              = "rtb-07926b43d726e7a02" -> null
      - owner_id                         = "264842458097" -> null
      - tags                             = {
          - "Name" = "iac-vpc"
        } -> null
      - tags_all                         = {
          - "Name" = "iac-vpc"
        } -> null
    }

Plan: 0 to add, 0 to change, 7 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 0 to add, 0 to change, 7 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
aws_route_table_association.iac-routing-table-association-1: Destroying... [id=rtbassoc-050b8de7698e5dee8]
aws_route_table_association.iac-routing-table-association-2: Destroying... [id=rtbassoc-09baaf5639e061758]
aws_route_table_association.iac-routing-table-association-2: Destruction complete after 0s
aws_subnet.iac-subnet-2: Destroying... [id=subnet-0b8de44bcd332b5ac]
aws_route_table_association.iac-routing-table-association-1: Destruction complete after 0s
aws_route_table.iac-routing-table: Destroying... [id=rtb-0da83ad9a5908a01f]
aws_subnet.iac-subnet-1: Destroying... [id=subnet-0bb6102ac68f7e016]
aws_route_table.iac-routing-table: Destruction complete after 0s
aws_internet_gateway.iac-igw: Destroying... [id=igw-0bddddc19e3a443b3]
aws_subnet.iac-subnet-1: Destruction complete after 0s
aws_subnet.iac-subnet-2: Destruction complete after 1s
aws_internet_gateway.iac-igw: Destruction complete after 1s
aws_vpc.iac-vpc: Destroying... [id=vpc-0119ba5078755447e]
aws_vpc.iac-vpc: Destruction complete after 0s

Apply complete! Resources: 0 added, 0 changed, 7 destroyed.


```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
