### PR TITLE
add: domain

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/bin/terraform plan -input=false -refresh -out \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/25/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/25/default": exit status 1
╷
│ Error: Reference to undeclared resource
│ 
│   on ec2.tf line 54, in resource "aws_route53_record" "iac-route53-20220223":
│   54:   zone_id = aws_route53_zone.primary.zone_id
│ 
│ A managed resource "aws_route53_zone" "primary" has not been declared in
│ the root module.
╵

```

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
- destroy

Terraform will perform the following actions:

  # aws_eip.iac-eip-20220223 will be created
+ resource "aws_eip" "iac-eip-20220223" {
      + allocation_id        = (known after apply)
      + association_id       = (known after apply)
      + carrier_ip           = (known after apply)
      + customer_owned_ip    = (known after apply)
      + domain               = (known after apply)
      + id                   = (known after apply)
      + instance             = "i-030bd725830bab8e0"
      + network_border_group = (known after apply)
      + network_interface    = (known after apply)
      + private_dns          = (known after apply)
      + private_ip           = (known after apply)
      + public_dns           = (known after apply)
      + public_ip            = (known after apply)
      + public_ipv4_pool     = (known after apply)
      + tags                 = {
          + "Name" = "iac-eip-20220223"
        }
      + tags_all             = {
          + "Name" = "iac-eip-20220223"
        }
      + vpc                  = true
    }

  # aws_eip.stage_server will be destroyed
  # (because aws_eip.stage_server is not in configuration)
- resource "aws_eip" "stage_server" {
      - allocation_id        = "eipalloc-0b75e301a5b3e6534" -> null
      - association_id       = "eipassoc-0ff151de453310fcb" -> null
      - domain               = "vpc" -> null
      - id                   = "eipalloc-0b75e301a5b3e6534" -> null
      - instance             = "i-030bd725830bab8e0" -> null
      - network_border_group = "ap-northeast-2" -> null
      - network_interface    = "eni-0864415f9b0a3bac1" -> null
      - private_dns          = "ip-10-0-1-239.ap-northeast-2.compute.internal" -> null
      - private_ip           = "10.0.1.239" -> null
      - public_dns           = "ec2-3-35-1-46.ap-northeast-2.compute.amazonaws.com" -> null
      - public_ip            = "3.35.1.46" -> null
      - public_ipv4_pool     = "amazon" -> null
      - tags                 = {} -> null
      - tags_all             = {} -> null
      - vpc                  = true -> null
    }

  # aws_route53_record.iac-route53-20220223 will be created
+ resource "aws_route53_record" "iac-route53-20220223" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "www.rhea-so.com"
      + records         = (known after apply)
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

  # aws_route53_zone.primary will be created
+ resource "aws_route53_zone" "primary" {
      + arn           = (known after apply)
      + comment       = "Managed by Terraform"
      + force_destroy = false
      + id            = (known after apply)
      + name          = "rhea-so.com"
      + name_servers  = (known after apply)
      + tags_all      = (known after apply)
      + zone_id       = (known after apply)
    }

Plan: 3 to add, 0 to change, 1 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 3 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
- destroy

Terraform will perform the following actions:

  # aws_eip.iac-eip-20220223 will be created
+ resource "aws_eip" "iac-eip-20220223" {
      + allocation_id        = (known after apply)
      + association_id       = (known after apply)
      + carrier_ip           = (known after apply)
      + customer_owned_ip    = (known after apply)
      + domain               = (known after apply)
      + id                   = (known after apply)
      + instance             = "i-030bd725830bab8e0"
      + network_border_group = (known after apply)
      + network_interface    = (known after apply)
      + private_dns          = (known after apply)
      + private_ip           = (known after apply)
      + public_dns           = (known after apply)
      + public_ip            = (known after apply)
      + public_ipv4_pool     = (known after apply)
      + tags                 = {
          + "Name" = "iac-eip-20220223"
        }
      + tags_all             = {
          + "Name" = "iac-eip-20220223"
        }
      + vpc                  = true
    }

  # aws_eip.stage_server will be destroyed
  # (because aws_eip.stage_server is not in configuration)
- resource "aws_eip" "stage_server" {
      - allocation_id        = "eipalloc-0b75e301a5b3e6534" -> null
      - association_id       = "eipassoc-0ff151de453310fcb" -> null
      - domain               = "vpc" -> null
      - id                   = "eipalloc-0b75e301a5b3e6534" -> null
      - instance             = "i-030bd725830bab8e0" -> null
      - network_border_group = "ap-northeast-2" -> null
      - network_interface    = "eni-0864415f9b0a3bac1" -> null
      - private_dns          = "ip-10-0-1-239.ap-northeast-2.compute.internal" -> null
      - private_ip           = "10.0.1.239" -> null
      - public_dns           = "ec2-3-35-1-46.ap-northeast-2.compute.amazonaws.com" -> null
      - public_ip            = "3.35.1.46" -> null
      - public_ipv4_pool     = "amazon" -> null
      - tags                 = {} -> null
      - tags_all             = {} -> null
      - vpc                  = true -> null
    }

  # aws_route53_record.iac-route53-20220223 will be created
+ resource "aws_route53_record" "iac-route53-20220223" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "iac.rhea-so.com"
      + records         = (known after apply)
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

  # aws_route53_zone.primary will be created
+ resource "aws_route53_zone" "primary" {
      + arn           = (known after apply)
      + comment       = "Managed by Terraform"
      + force_destroy = false
      + id            = (known after apply)
      + name          = "rhea-so.com"
      + name_servers  = (known after apply)
      + tags_all      = (known after apply)
      + zone_id       = (known after apply)
    }

Plan: 3 to add, 0 to change, 1 to destroy.
Releasing state lock. This may take a few moments...

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 3 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
aws_eip.stage_server: Destroying... [id=eipalloc-0b75e301a5b3e6534]
aws_route53_zone.primary: Creating...
aws_eip.iac-eip-20220223: Creating...
aws_eip.iac-eip-20220223: Creation complete after 1s [id=eipalloc-06664f8ac0365d0dd]
aws_eip.stage_server: Destruction complete after 1s
aws_route53_zone.primary: Still creating... [10s elapsed]
aws_route53_zone.primary: Still creating... [20s elapsed]
aws_route53_zone.primary: Creation complete after 30s [id=Z0991838PJM65M902BCW]
aws_route53_record.iac-route53-20220223: Creating...
aws_route53_record.iac-route53-20220223: Still creating... [10s elapsed]
aws_route53_record.iac-route53-20220223: Still creating... [20s elapsed]
aws_route53_record.iac-route53-20220223: Still creating... [30s elapsed]
aws_route53_record.iac-route53-20220223: Creation complete after 36s [id=Z0991838PJM65M902BCW_iac.rhea-so.com_A]

Apply complete! Resources: 3 added, 0 changed, 1 destroyed.


```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
