### PR TITLE
add: Route 53

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by rhea-so** [comment]
atlantis plan

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
- destroy

Terraform will perform the following actions:

  # aws_ecr_repository.iac-ecr will be destroyed
  # (because aws_ecr_repository.iac-ecr is not in configuration)
- resource "aws_ecr_repository" "iac-ecr" {
      - arn                  = "arn:aws:ecr:ap-northeast-2:264842458097:repository/iac-ecr" -> null
      - id                   = "iac-ecr" -> null
      - image_tag_mutability = "MUTABLE" -> null
      - name                 = "iac-ecr" -> null
      - registry_id          = "264842458097" -> null
      - repository_url       = "264842458097.dkr.ecr.ap-northeast-2.amazonaws.com/iac-ecr" -> null
      - tags                 = {} -> null
      - tags_all             = {} -> null

      - encryption_configuration {
          - encryption_type = "AES256" -> null
        }

      - image_scanning_configuration {
          - scan_on_push = true -> null
        }
    }

  # aws_route53_zone.rhea-so will be created
+ resource "aws_route53_zone" "rhea-so" {
      + arn           = (known after apply)
      + comment       = "Managed by Terraform"
      + force_destroy = true
      + id            = (known after apply)
      + name          = "rhea-so.com"
      + name_servers  = (known after apply)
      + tags_all      = (known after apply)
      + zone_id       = (known after apply)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
Releasing state lock. This may take a few moments...

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 1 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
aws_ecr_repository.iac-ecr: Destroying... [id=iac-ecr]
aws_route53_zone.rhea-so: Creating...
aws_ecr_repository.iac-ecr: Destruction complete after 0s
aws_route53_zone.rhea-so: Still creating... [10s elapsed]
aws_route53_zone.rhea-so: Still creating... [20s elapsed]
aws_route53_zone.rhea-so: Still creating... [30s elapsed]
aws_route53_zone.rhea-so: Still creating... [40s elapsed]
aws_route53_zone.rhea-so: Creation complete after 40s [id=Z02629952Z1ESWD7VTUX1]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.


```

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
