### PR TITLE
test: Backup Folder

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # module.production.module.home-sg.aws_security_group.security-group has changed
~ resource "aws_security_group" "security-group" {
      ~ egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 22
              + ipv6_cidr_blocks = [
                  + "::/0",
                ]
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 22
            },
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = ""
              - from_port        = 22
              - ipv6_cidr_blocks = [
                  - "::0/0",
                ]
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 22
            },
        ]
        id                     = "sg-0ca28bfad29672cc3"
        name                   = "home-sg-security-group"
        tags                   = {
            "Name" = "home-sg-security-group"
        }
        # (7 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # module.production.module.home-sg.aws_security_group.security-group will be destroyed
  # (because aws_security_group.security-group is not in configuration)
- resource "aws_security_group" "security-group" {
      - arn                    = "arn:aws:ec2:ap-northeast-2:264842458097:security-group/sg-0ca28bfad29672cc3" -> null
      - description            = "Managed by Terraform" -> null
      - egress                 = [
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = ""
              - from_port        = 22
              - ipv6_cidr_blocks = [
                  - "::/0",
                ]
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 22
            },
        ] -> null
      - id                     = "sg-0ca28bfad29672cc3" -> null
      - ingress                = [
          - {
              - cidr_blocks      = [
                  - "121.161.240.241/32",
                ]
              - description      = ""
              - from_port        = 22
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 22
            },
        ] -> null
      - name                   = "home-sg-security-group" -> null
      - owner_id               = "264842458097" -> null
      - revoke_rules_on_delete = false -> null
      - tags                   = {
          - "Name" = "home-sg-security-group"
        } -> null
      - tags_all               = {
          - "Name" = "home-sg-security-group"
        } -> null
      - vpc_id                 = "vpc-07c8dd70613d34120" -> null
    }

  # module.production.module.vpc.aws_internet_gateway.internet-gateway will be destroyed
  # (because aws_internet_gateway.internet-gateway is not in configuration)
- resource "aws_internet_gateway" "internet-gateway" {
      - arn      = "arn:aws:ec2:ap-northeast-2:264842458097:internet-gateway/igw-0bd506c36aa27d796" -> null
      - id       = "igw-0bd506c36aa27d796" -> null
      - owner_id = "264842458097" -> null
      - tags     = {
          - "Name" = "test-internet-gateway"
        } -> null
      - tags_all = {
          - "Name" = "test-internet-gateway"
        } -> null
      - vpc_id   = "vpc-07c8dd70613d34120" -> null
    }

  # module.production.module.vpc.aws_route_table.routing-table will be destroyed
  # (because aws_route_table.routing-table is not in configuration)
- resource "aws_route_table" "routing-table" {
      - arn              = "arn:aws:ec2:ap-northeast-2:264842458097:route-table/rtb-041ea4ae0bf777187" -> null
      - id               = "rtb-041ea4ae0bf777187" -> null
      - owner_id         = "264842458097" -> null
      - propagating_vgws = [] -> null
      - route            = [
          - {
              - carrier_gateway_id         = ""
              - cidr_block                 = "0.0.0.0/0"
              - destination_prefix_list_id = ""
              - egress_only_gateway_id     = ""
              - gateway_id                 = "igw-0bd506c36aa27d796"
              - instance_id                = ""
              - ipv6_cidr_block            = ""
              - local_gateway_id           = ""
              - nat_gateway_id             = ""
              - network_interface_id       = ""
              - transit_gateway_id         = ""
              - vpc_endpoint_id            = ""
              - vpc_peering_connection_id  = ""
            },
        ] -> null
      - tags             = {
          - "Name" = "test-routing-table"
        } -> null
      - tags_all         = {
          - "Name" = "test-routing-table"
        } -> null
      - vpc_id           = "vpc-07c8dd70613d34120" -> null
    }

  # module.production.module.vpc.aws_route_table_association.routing-table-association-1 will be destroyed
  # (because aws_route_table_association.routing-table-association-1 is not in configuration)
- resource "aws_route_table_association" "routing-table-association-1" {
      - id             = "rtbassoc-07bac00f2f1f929bd" -> null
      - route_table_id = "rtb-041ea4ae0bf777187" -> null
      - subnet_id      = "subnet-0d27582222e386668" -> null
    }

  # module.production.module.vpc.aws_route_table_association.routing-table-association-2 will be destroyed
  # (because aws_route_table_association.routing-table-association-2 is not in configuration)
- resource "aws_route_table_association" "routing-table-association-2" {
      - id             = "rtbassoc-069c8bd858f68705d" -> null
      - route_table_id = "rtb-041ea4ae0bf777187" -> null
      - subnet_id      = "subnet-05404ba31f94380ef" -> null
    }

  # module.production.module.vpc.aws_subnet.subnet-1 will be destroyed
  # (because aws_subnet.subnet-1 is not in configuration)
- resource "aws_subnet" "subnet-1" {
      - arn                                            = "arn:aws:ec2:ap-northeast-2:264842458097:subnet/subnet-0d27582222e386668" -> null
      - assign_ipv6_address_on_creation                = false -> null
      - availability_zone                              = "ap-northeast-2a" -> null
      - availability_zone_id                           = "apne2-az1" -> null
      - cidr_block                                     = "10.0.1.0/24" -> null
      - enable_dns64                                   = false -> null
      - enable_resource_name_dns_a_record_on_launch    = false -> null
      - enable_resource_name_dns_aaaa_record_on_launch = false -> null
      - id                                             = "subnet-0d27582222e386668" -> null
      - ipv6_native                                    = false -> null
      - map_customer_owned_ip_on_launch                = false -> null
      - map_public_ip_on_launch                        = false -> null
      - owner_id                                       = "264842458097" -> null
      - private_dns_hostname_type_on_launch            = "ip-name" -> null
      - tags                                           = {
          - "Name" = "test-subnet-1"
        } -> null
      - tags_all                                       = {
          - "Name" = "test-subnet-1"
        } -> null
      - vpc_id                                         = "vpc-07c8dd70613d34120" -> null
    }

  # module.production.module.vpc.aws_subnet.subnet-2 will be destroyed
  # (because aws_subnet.subnet-2 is not in configuration)
- resource "aws_subnet" "subnet-2" {
      - arn                                            = "arn:aws:ec2:ap-northeast-2:264842458097:subnet/subnet-05404ba31f94380ef" -> null
      - assign_ipv6_address_on_creation                = false -> null
      - availability_zone                              = "ap-northeast-2c" -> null
      - availability_zone_id                           = "apne2-az3" -> null
      - cidr_block                                     = "10.0.2.0/24" -> null
      - enable_dns64                                   = false -> null
      - enable_resource_name_dns_a_record_on_launch    = false -> null
      - enable_resource_name_dns_aaaa_record_on_launch = false -> null
      - id                                             = "subnet-05404ba31f94380ef" -> null
      - ipv6_native                                    = false -> null
      - map_customer_owned_ip_on_launch                = false -> null
      - map_public_ip_on_launch                        = false -> null
      - owner_id                                       = "264842458097" -> null
      - private_dns_hostname_type_on_launch            = "ip-name" -> null
      - tags                                           = {
          - "Name" = "test-subnet-2"
        } -> null
      - tags_all                                       = {
          - "Name" = "test-subnet-2"
        } -> null
      - vpc_id                                         = "vpc-07c8dd70613d34120" -> null
    }

  # module.production.module.vpc.aws_vpc.vpc will be destroyed
  # (because aws_vpc.vpc is not in configuration)
- resource "aws_vpc" "vpc" {
      - arn                              = "arn:aws:ec2:ap-northeast-2:264842458097:vpc/vpc-07c8dd70613d34120" -> null
      - assign_generated_ipv6_cidr_block = false -> null
      - cidr_block                       = "10.0.0.0/16" -> null
      - default_network_acl_id           = "acl-0a6f91582c3506b82" -> null
      - default_route_table_id           = "rtb-0ddc6572ba422945b" -> null
      - default_security_group_id        = "sg-0d1450d2b3cba7e39" -> null
      - dhcp_options_id                  = "dopt-0439dc969e8731205" -> null
      - enable_classiclink               = false -> null
      - enable_classiclink_dns_support   = false -> null
      - enable_dns_hostnames             = false -> null
      - enable_dns_support               = true -> null
      - id                               = "vpc-07c8dd70613d34120" -> null
      - instance_tenancy                 = "default" -> null
      - ipv6_netmask_length              = 0 -> null
      - main_route_table_id              = "rtb-0ddc6572ba422945b" -> null
      - owner_id                         = "264842458097" -> null
      - tags                             = {
          - "Name" = "test-vpc"
        } -> null
      - tags_all                         = {
          - "Name" = "test-vpc"
        } -> null
    }

Plan: 0 to add, 0 to change, 8 to destroy.
Releasing state lock. This may take a few moments...

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 0 to add, 0 to change, 8 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
module.production.module.vpc.aws_route_table_association.routing-table-association-2: Destroying... [id=rtbassoc-069c8bd858f68705d]
module.production.module.vpc.aws_route_table_association.routing-table-association-1: Destroying... [id=rtbassoc-07bac00f2f1f929bd]
module.production.module.home-sg.aws_security_group.security-group: Destroying... [id=sg-0ca28bfad29672cc3]
module.production.module.vpc.aws_route_table_association.routing-table-association-1: Destruction complete after 0s
module.production.module.vpc.aws_subnet.subnet-1: Destroying... [id=subnet-0d27582222e386668]
module.production.module.vpc.aws_route_table_association.routing-table-association-2: Destruction complete after 0s
module.production.module.vpc.aws_subnet.subnet-2: Destroying... [id=subnet-05404ba31f94380ef]
module.production.module.vpc.aws_route_table.routing-table: Destroying... [id=rtb-041ea4ae0bf777187]
module.production.module.home-sg.aws_security_group.security-group: Destruction complete after 0s
module.production.module.vpc.aws_subnet.subnet-2: Destruction complete after 0s
module.production.module.vpc.aws_subnet.subnet-1: Destruction complete after 0s
module.production.module.vpc.aws_route_table.routing-table: Destruction complete after 1s
module.production.module.vpc.aws_internet_gateway.internet-gateway: Destroying... [id=igw-0bd506c36aa27d796]
module.production.module.vpc.aws_internet_gateway.internet-gateway: Destruction complete after 0s
module.production.module.vpc.aws_vpc.vpc: Destroying... [id=vpc-07c8dd70613d34120]
module.production.module.vpc.aws_vpc.vpc: Destruction complete after 0s

Apply complete! Resources: 0 added, 0 changed, 8 destroyed.


```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Comment by rhea-so** [comment]
atlantis help

**Comment by AyameNakiri** [comment]
```cmake
atlantis
Terraform Pull Request Automation

Usage:
  atlantis <command> [options] -- [terraform options]

Examples:
  # run plan in the root directory passing the -target flag to terraform
  atlantis plan -d . -- -target=resource

  # apply all unapplied plans from this pull request
  atlantis apply

  # apply the plan for the root directory and staging workspace
  atlantis apply -d . -w staging

Commands:
  plan     Runs 'terraform plan' for the changes in this pull request.
           To plan a specific project, use the -d, -w and -p flags.
  apply    Runs 'terraform apply' on all unapplied plans from this pull request.
           To only apply a specific plan, use the -d, -w and -p flags.
  unlock   Removes all atlantis locks and discards all plans for this PR.
           To unlock a specific plan you can use the Atlantis UI.
  approve_policies
           Approves all current policy checking failures for the PR.
  version  Print the output of 'terraform version'
  help     View help.

Flags:
  -h, --help   help for atlantis

Use "atlantis [command] --help" for more information about a command.
```

**Pull request merged**
