### PR TITLE
add: example

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `00_Environment/03_Production` workspace: `production`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.atlantis-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "atlantis.rhea-so.com"
      + records         = [
          + "52.78.144.248",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

  # module.google-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "google.rhea-so.com"
      + records         = [
          + "172.217.31.174",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

  # module.rhea-so.aws_route53_zone.domain will be created
+ resource "aws_route53_zone" "domain" {
      + arn           = (known after apply)
      + comment       = "Managed by Terraform"
      + force_destroy = true
      + id            = (known after apply)
      + name          = "rhea-so.com"
      + name_servers  = (known after apply)
      + tags_all      = (known after apply)
      + zone_id       = (known after apply)
    }

  # module.test-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "test.rhea-so.com"
      + records         = [
          + "172.217.31.174",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

Plan: 4 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production -w production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fproduction)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d 00_Environment/03_Production -w production`
</details>
Plan: 4 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `00_Environment/03_Production` workspace: `production`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production -w production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fproduction)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d 00_Environment/03_Production -w production`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `00_Environment/03_Production` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.atlantis-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "atlantis.rhea-so.com"
      + records         = [
          + "52.78.144.248",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

  # module.google-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "google.rhea-so.com"
      + records         = [
          + "172.217.31.174",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

  # module.rhea-so.aws_route53_zone.domain will be created
+ resource "aws_route53_zone" "domain" {
      + arn           = (known after apply)
      + comment       = "Managed by Terraform"
      + force_destroy = true
      + id            = (known after apply)
      + name          = "rhea-so.com"
      + name_servers  = (known after apply)
      + tags_all      = (known after apply)
      + zone_id       = (known after apply)
    }

  # module.test-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "test.rhea-so.com"
      + records         = [
          + "172.217.31.174",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

Plan: 4 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d 00_Environment/03_Production`
</details>
Plan: 4 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `00_Environment/03_Production` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d 00_Environment/03_Production`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
**Apply Error**
```
building command for dir "00_Environment/03_Production": running commands in workspace "production" is not allowed because this directory is only configured for the following workspaces: default
```

**Comment by AyameNakiri** [comment]
**Plan Error**
```
parsing atlantis.yaml: repo config not allowed to set 'apply_requirements' key: server-side config needs 'allowed_overrides: [apply_requirements]'
```

**Comment by AyameNakiri** [comment]
**Plan Error**
```
parsing atlantis.yaml: repo config not allowed to set 'apply_requirements' key: server-side config needs 'allowed_overrides: [apply_requirements]'
```

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `00_Environment/03_Production` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.atlantis-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "atlantis.rhea-so.com"
      + records         = [
          + "52.78.144.248",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

  # module.google-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "google.rhea-so.com"
      + records         = [
          + "172.217.31.174",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

  # module.rhea-so.aws_route53_zone.domain will be created
+ resource "aws_route53_zone" "domain" {
      + arn           = (known after apply)
      + comment       = "Managed by Terraform"
      + force_destroy = true
      + id            = (known after apply)
      + name          = "rhea-so.com"
      + name_servers  = (known after apply)
      + tags_all      = (known after apply)
      + zone_id       = (known after apply)
    }

  # module.test-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "test.rhea-so.com"
      + records         = [
          + "172.217.31.174",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

Plan: 4 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d 00_Environment/03_Production`
</details>
Plan: 4 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `00_Environment/03_Production` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d 00_Environment/03_Production`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
**Apply Error**
```
building command for dir "00_Environment/03_Production": running commands in workspace "production" is not allowed because this directory is only configured for the following workspaces: default
```

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `00_Environment/03_Production` workspace: `production`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.atlantis-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "atlantis.rhea-so.com"
      + records         = [
          + "52.78.144.248",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

  # module.google-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "google.rhea-so.com"
      + records         = [
          + "172.217.31.174",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

  # module.rhea-so.aws_route53_zone.domain will be created
+ resource "aws_route53_zone" "domain" {
      + arn           = (known after apply)
      + comment       = "Managed by Terraform"
      + force_destroy = true
      + id            = (known after apply)
      + name          = "rhea-so.com"
      + name_servers  = (known after apply)
      + tags_all      = (known after apply)
      + zone_id       = (known after apply)
    }

  # module.test-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "test.rhea-so.com"
      + records         = [
          + "172.217.31.174",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

Plan: 4 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production -w production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fproduction)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d 00_Environment/03_Production -w production`
</details>
Plan: 4 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `00_Environment/03_Production` workspace: `production`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production -w production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fproduction)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d 00_Environment/03_Production -w production`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Plan for 3 projects:

1. dir: `00_Environment/01_Dev` workspace: `dev`
1. dir: `00_Environment/02_Staging` workspace: `staging`
1. dir: `00_Environment/03_Production` workspace: `production`

### 1. dir: `00_Environment/01_Dev` workspace: `dev`
**Plan Error**
```
running "/usr/bin/terraform workspace new dev" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/99/dev/00_Environment/01_Dev": exit status 1: Failed to get configured named states: workspaces not supported


```

---
### 2. dir: `00_Environment/02_Staging` workspace: `staging`
**Plan Error**
```
running "/usr/bin/terraform workspace new staging" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/99/staging/00_Environment/02_Staging": exit status 1: Failed to get configured named states: workspaces not supported


```

---
### 3. dir: `00_Environment/03_Production` workspace: `production`
**Plan Error**
```
running "/usr/bin/terraform workspace new production" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/99/production/00_Environment/03_Production": exit status 1: Failed to get configured named states: workspaces not supported


```

---

**Comment by AyameNakiri** [comment]
Ran Plan for 3 projects:

1. dir: `00_Environment/01_Dev` workspace: `infrastructure-as-code`
1. dir: `00_Environment/02_Staging` workspace: `infrastructure-as-code`
1. dir: `00_Environment/03_Production` workspace: `infrastructure-as-code`

### 1. dir: `00_Environment/01_Dev` workspace: `infrastructure-as-code`
**Plan Error**
```
running "/usr/bin/terraform workspace new infrastructure-as-code" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/99/infrastructure-as-code/00_Environment/01_Dev": exit status 1: Failed to get configured named states: workspaces not supported


```

---
### 2. dir: `00_Environment/02_Staging` workspace: `infrastructure-as-code`
**Plan Error**
```
running "/usr/bin/terraform workspace new infrastructure-as-code" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/99/infrastructure-as-code/00_Environment/02_Staging": exit status 1: Failed to get configured named states: workspaces not supported


```

---
### 3. dir: `00_Environment/03_Production` workspace: `infrastructure-as-code`
**Plan Error**
```
running "/usr/bin/terraform workspace new infrastructure-as-code" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/99/infrastructure-as-code/00_Environment/03_Production": exit status 1: Failed to get configured named states: workspaces not supported


```

---

**Comment by AyameNakiri** [comment]
Ran Plan for 3 projects:

1. dir: `00_Environment/01_Dev` workspace: `dev`
1. dir: `00_Environment/02_Staging` workspace: `staging`
1. dir: `00_Environment/03_Production` workspace: `production`

### 1. dir: `00_Environment/01_Dev` workspace: `dev`
**Plan Error**
```
running "/usr/bin/terraform workspace new dev" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/99/dev/00_Environment/01_Dev": exit status 1: Failed to get configured named states: workspaces not supported


```

---
### 2. dir: `00_Environment/02_Staging` workspace: `staging`
**Plan Error**
```
running "/usr/bin/terraform workspace new staging" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/99/staging/00_Environment/02_Staging": exit status 1: Failed to get configured named states: workspaces not supported


```

---
### 3. dir: `00_Environment/03_Production` workspace: `production`
**Plan Error**
```
running "/usr/bin/terraform workspace new production" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/99/production/00_Environment/03_Production": exit status 1: Failed to get configured named states: workspaces not supported


```

---

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `00_Environment/03_Production` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.atlantis-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "atlantis.rhea-so.com"
      + records         = [
          + "52.78.144.248",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

  # module.google-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "google.rhea-so.com"
      + records         = [
          + "172.217.31.174",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

  # module.rhea-so.aws_route53_zone.domain will be created
+ resource "aws_route53_zone" "domain" {
      + arn           = (known after apply)
      + comment       = "Managed by Terraform"
      + force_destroy = true
      + id            = (known after apply)
      + name          = "rhea-so.com"
      + name_servers  = (known after apply)
      + tags_all      = (known after apply)
      + zone_id       = (known after apply)
    }

  # module.test-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "test.rhea-so.com"
      + records         = [
          + "172.217.31.174",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

Plan: 4 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d 00_Environment/03_Production`
</details>
Plan: 4 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `00_Environment/03_Production` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d 00_Environment/03_Production`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `00_Environment/03_Production` workspace: `default`

<details><summary>Show Output</summary>

```diff
module.rhea-so.aws_route53_zone.domain: Creating...
module.rhea-so.aws_route53_zone.domain: Still creating... [10s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [20s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [30s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [40s elapsed]
module.rhea-so.aws_route53_zone.domain: Creation complete after 44s [id=Z06478983O0RII8NFVLK5]
module.atlantis-rhea-so.aws_route53_record.domain: Creating...
module.google-rhea-so.aws_route53_record.domain: Creating...
module.test-rhea-so.aws_route53_record.domain: Creating...
module.atlantis-rhea-so.aws_route53_record.domain: Still creating... [10s elapsed]
module.google-rhea-so.aws_route53_record.domain: Still creating... [10s elapsed]
module.test-rhea-so.aws_route53_record.domain: Still creating... [10s elapsed]
module.atlantis-rhea-so.aws_route53_record.domain: Still creating... [20s elapsed]
module.google-rhea-so.aws_route53_record.domain: Still creating... [20s elapsed]
module.test-rhea-so.aws_route53_record.domain: Still creating... [20s elapsed]
module.atlantis-rhea-so.aws_route53_record.domain: Creation complete after 29s [id=Z06478983O0RII8NFVLK5_atlantis.rhea-so.com_A]
module.google-rhea-so.aws_route53_record.domain: Still creating... [30s elapsed]
module.test-rhea-so.aws_route53_record.domain: Still creating... [30s elapsed]
module.google-rhea-so.aws_route53_record.domain: Creation complete after 33s [id=Z06478983O0RII8NFVLK5_google.rhea-so.com_A]
module.test-rhea-so.aws_route53_record.domain: Still creating... [40s elapsed]
module.test-rhea-so.aws_route53_record.domain: Creation complete after 42s [id=Z06478983O0RII8NFVLK5_test.rhea-so.com_A]

Apply complete! Resources: 4 added, 0 changed, 0 destroyed.


```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `00_Environment/03_Production` workspace: `default`

**Pull request merged**
