### PR TITLE
add: enable subnet dns settings

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # aws_subnet.iac-subnet-20220223 will be updated in-place
~ resource "aws_subnet" "iac-subnet-20220223" {
      ~ enable_dns64                                   = false -> true
      ~ enable_resource_name_dns_aaaa_record_on_launch = false -> true
        id                                             = "subnet-0f934a92067b0f67e"
        tags                                           = {
            "Name" = "iac-subnet-20220223"
        }
        # (13 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
Releasing state lock. This may take a few moments...

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 0 to add, 1 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

**Apply Error**
```
running "/usr/bin/terraform apply -input=false \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/27/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/27/default": exit status 1
aws_subnet.iac-subnet-20220223: Modifying... [id=subnet-0f934a92067b0f67e]
╷
│ Error: error setting EC2 Subnet (subnet-0f934a92067b0f67e) EnableDns64: InvalidParameterValue: Invalid value 'true' for enable-dns64. Cannot set enable-dns64 to true unless the subnet (subnet-0f934a92067b0f67e) has an IPv6 CIDR block associated with it.
│ 	status code: 400, request id: b9fe576b-c971-42ce-b4bc-4afa00bb3e98
│ 
│   with aws_subnet.iac-subnet-20220223,
│   on infra.tf line 20, in resource "aws_subnet" "iac-subnet-20220223":
│   20: resource "aws_subnet" "iac-subnet-20220223" {
│ 
╵

```

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_subnet.iac-subnet-20220223 has changed
~ resource "aws_subnet" "iac-subnet-20220223" {
      ~ enable_dns64                                   = true -> false
      ~ enable_resource_name_dns_aaaa_record_on_launch = true -> false
        id                                             = "subnet-0f934a92067b0f67e"
        tags                                           = {
            "Name" = "iac-subnet-20220223"
        }
        # (13 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # aws_subnet.iac-subnet-20220223 will be updated in-place
~ resource "aws_subnet" "iac-subnet-20220223" {
      ~ enable_resource_name_dns_aaaa_record_on_launch = false -> true
        id                                             = "subnet-0f934a92067b0f67e"
        tags                                           = {
            "Name" = "iac-subnet-20220223"
        }
        # (14 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 0 to add, 1 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

**Apply Error**
```
running "/usr/bin/terraform apply -input=false \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/27/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/27/default": exit status 1
Acquiring state lock. This may take a few moments...
aws_subnet.iac-subnet-20220223: Modifying... [id=subnet-0f934a92067b0f67e]
╷
│ Error: error setting EC2 Subnet (subnet-0f934a92067b0f67e) EnableResourceNameDnsAAAARecordOnLaunch: InvalidParameterValue: Invalid value 'true' for enable-resource-name-dns-aaaa-record-on-launch. Cannot set enable-resource-name-dns-aaaa-record-on-launch to true unless the subnet (subnet-0f934a92067b0f67e) has an IPv6 CIDR block associated with it.
│ 	status code: 400, request id: 865f33a1-428f-48f4-9621-8e03a1d40885
│ 
│   with aws_subnet.iac-subnet-20220223,
│   on infra.tf line 20, in resource "aws_subnet" "iac-subnet-20220223":
│   20: resource "aws_subnet" "iac-subnet-20220223" {
│ 
╵

```

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_subnet.iac-subnet-20220223 has changed
~ resource "aws_subnet" "iac-subnet-20220223" {
      ~ enable_resource_name_dns_aaaa_record_on_launch = true -> false
        id                                             = "subnet-0f934a92067b0f67e"
        tags                                           = {
            "Name" = "iac-subnet-20220223"
        }
        # (14 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
~ update in-place
- destroy
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # aws_route53_record.iac-route53-20220223 must be replaced
-/+ resource "aws_route53_record" "iac-route53-20220223" {
      + allow_overwrite = (known after apply)
      ~ fqdn            = "iac.rhea-so.com" -> (known after apply)
      ~ id              = "Z0991838PJM65M902BCW_iac.rhea-so.com_A" -> (known after apply)
      ~ name            = "iac.rhea-so.com" -> "rhea-so.com" # forces replacement
      ~ zone_id         = "Z0991838PJM65M902BCW" -> (known after apply) # forces replacement
        # (3 unchanged attributes hidden)
    }

  # aws_route53_zone.primary will be destroyed
  # (because aws_route53_zone.primary is not in configuration)
- resource "aws_route53_zone" "primary" {
      - arn           = "arn:aws:route53:::hostedzone/Z0991838PJM65M902BCW" -> null
      - comment       = "Managed by Terraform" -> null
      - force_destroy = false -> null
      - id            = "Z0991838PJM65M902BCW" -> null
      - name          = "rhea-so.com" -> null
      - name_servers  = [
          - "ns-1509.awsdns-60.org",
          - "ns-1684.awsdns-18.co.uk",
          - "ns-492.awsdns-61.com",
          - "ns-746.awsdns-29.net",
        ] -> null
      - tags          = {} -> null
      - tags_all      = {} -> null
      - zone_id       = "Z0991838PJM65M902BCW" -> null
    }

  # aws_route53_zone.rhea-so will be created
+ resource "aws_route53_zone" "rhea-so" {
      + arn           = (known after apply)
      + comment       = "Managed by Terraform"
      + force_destroy = false
      + id            = (known after apply)
      + name          = "rhea-so.com"
      + name_servers  = (known after apply)
      + tags_all      = (known after apply)
      + zone_id       = (known after apply)
    }

  # aws_subnet.iac-subnet-20220223 will be updated in-place
~ resource "aws_subnet" "iac-subnet-20220223" {
      ~ enable_resource_name_dns_a_record_on_launch    = true -> false
        id                                             = "subnet-0f934a92067b0f67e"
        tags                                           = {
            "Name" = "iac-subnet-20220223"
        }
        # (14 unchanged attributes hidden)
    }

Plan: 2 to add, 1 to change, 2 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 2 to add, 1 to change, 2 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
aws_route53_record.iac-route53-20220223: Destroying... [id=Z0991838PJM65M902BCW_iac.rhea-so.com_A]
aws_route53_record.iac-route53-20220223: Still destroying... [id=Z0991838PJM65M902BCW_iac.rhea-so.com_A, 10s elapsed]
aws_route53_record.iac-route53-20220223: Still destroying... [id=Z0991838PJM65M902BCW_iac.rhea-so.com_A, 20s elapsed]
aws_route53_record.iac-route53-20220223: Destruction complete after 24s
aws_route53_zone.primary: Destroying... [id=Z0991838PJM65M902BCW]
aws_route53_zone.rhea-so: Creating...
aws_subnet.iac-subnet-20220223: Modifying... [id=subnet-0f934a92067b0f67e]
aws_route53_zone.primary: Destruction complete after 1s
aws_route53_zone.rhea-so: Still creating... [10s elapsed]
aws_subnet.iac-subnet-20220223: Still modifying... [id=subnet-0f934a92067b0f67e, 10s elapsed]
aws_subnet.iac-subnet-20220223: Modifications complete after 10s [id=subnet-0f934a92067b0f67e]
aws_route53_zone.rhea-so: Still creating... [20s elapsed]
aws_route53_zone.rhea-so: Creation complete after 29s [id=Z00481431FE9EJXZFCWSO]
aws_route53_record.iac-route53-20220223: Creating...
aws_route53_record.iac-route53-20220223: Still creating... [10s elapsed]
aws_route53_record.iac-route53-20220223: Still creating... [20s elapsed]
aws_route53_record.iac-route53-20220223: Still creating... [30s elapsed]
aws_route53_record.iac-route53-20220223: Creation complete after 40s [id=Z00481431FE9EJXZFCWSO_rhea-so.com_A]

Apply complete! Resources: 2 added, 1 changed, 2 destroyed.


```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
