### PR TITLE
add: Google Routing

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `Example` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_apigatewayv2_api.iac-api-gateway-http will be created
+ resource "aws_apigatewayv2_api" "iac-api-gateway-http" {
      + api_endpoint                 = (known after apply)
      + api_key_selection_expression = "$request.header.x-api-key"
      + arn                          = (known after apply)
      + execution_arn                = (known after apply)
      + id                           = (known after apply)
      + name                         = "iac-api-gateway-http"
      + protocol_type                = "HTTP"
      + route_selection_expression   = "$request.method $request.path"
      + tags_all                     = (known after apply)
    }

  # aws_apigatewayv2_integration.iac-api-gateway-http-integration will be created
+ resource "aws_apigatewayv2_integration" "iac-api-gateway-http-integration" {
      + api_id                                    = (known after apply)
      + connection_type                           = "INTERNET"
      + id                                        = (known after apply)
      + integration_method                        = "GET"
      + integration_response_selection_expression = (known after apply)
      + integration_type                          = "HTTP_PROXY"
      + integration_uri                           = "https://google.com"
      + payload_format_version                    = "1.0"
      + timeout_milliseconds                      = (known after apply)
    }

  # aws_apigatewayv2_route.iac-api-gateway-http-route will be created
+ resource "aws_apigatewayv2_route" "iac-api-gateway-http-route" {
      + api_id             = (known after apply)
      + api_key_required   = false
      + authorization_type = "NONE"
      + id                 = (known after apply)
      + route_key          = "GET /{proxy+}"
      + target             = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Changes to Outputs:
+ iac-api-gateway-http-endpoint = (known after apply)

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d Example`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252FExample%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d Example`
</details>
Plan: 3 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `Example` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d Example`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252FExample%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d Example`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `Example` workspace: `default`

```diff
aws_apigatewayv2_api.iac-api-gateway-http: Creating...
aws_apigatewayv2_api.iac-api-gateway-http: Creation complete after 0s [id=qcmtgi8l2m]
aws_apigatewayv2_integration.iac-api-gateway-http-integration: Creating...
aws_apigatewayv2_integration.iac-api-gateway-http-integration: Creation complete after 1s [id=wtyt1b8]
aws_apigatewayv2_route.iac-api-gateway-http-route: Creating...
aws_apigatewayv2_route.iac-api-gateway-http-route: Creation complete after 0s [id=wrengs3]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Outputs:

iac-api-gateway-http-endpoint = "https://qcmtgi8l2m.execute-api.ap-northeast-2.amazonaws.com"

```

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `Example` workspace: `default`

**Pull request merged**
