### PR TITLE
fix: target group arn

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_ecs_service.memo-ecs-service has changed
~ resource "aws_ecs_service" "memo-ecs-service" {
        id                                 = "arn:aws:ecs:ap-northeast-2:264842458097:service/memo-ecs-cluster/memo-ecs-service"
        name                               = "memo-ecs-service"
      + tags                               = {}
        # (15 unchanged attributes hidden)




        # (4 unchanged blocks hidden)
    }

  # aws_ecs_task_definition.memo-ecs-task-definition has changed
~ resource "aws_ecs_task_definition" "memo-ecs-task-definition" {
        id                       = "memo-ecs-task-definition"
      + tags                     = {}
        # (11 unchanged attributes hidden)
    }

  # aws_lb_target_group.memo-alb-target-group-1 has changed
~ resource "aws_lb_target_group" "memo-alb-target-group-1" {
        id                                 = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group-1/4dfadbcb821d0427"
        name                               = "memo-alb-target-group-1"
      + tags                               = {}
        # (14 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
~ update in-place
- destroy
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # aws_ecs_service.memo-ecs-service must be replaced
-/+ resource "aws_ecs_service" "memo-ecs-service" {
      - health_check_grace_period_seconds  = 0 -> null
      ~ iam_role                           = "aws-service-role" -> (known after apply)
      ~ id                                 = "arn:aws:ecs:ap-northeast-2:264842458097:service/memo-ecs-cluster/memo-ecs-service" -> (known after apply)
        name                               = "memo-ecs-service"
      ~ platform_version                   = "LATEST" -> (known after apply)
      - propagate_tags                     = "NONE" -> null
      - tags                               = {} -> null
      ~ tags_all                           = {} -> (known after apply)
        # (10 unchanged attributes hidden)

      - deployment_circuit_breaker {
          - enable   = false -> null
          - rollback = false -> null
        }

      - deployment_controller {
          - type = "ECS" -> null
        }

      - load_balancer { # forces replacement
          - container_name   = "memo-ecs-container" -> null
          - container_port   = 8080 -> null
          - target_group_arn = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group-1/4dfadbcb821d0427" -> null
        }
      + load_balancer { # forces replacement
          + container_name   = "memo-ecs-container"
          + container_port   = 8080
          + target_group_arn = (known after apply)
        }

        # (1 unchanged block hidden)
    }

  # aws_lb_listener.memo-alb-listener will be updated in-place
~ resource "aws_lb_listener" "memo-alb-listener" {
        id                = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:listener/app/memo-alb/99c5d5623fa5aa5f/6d34e868e2d2e54e"
        tags              = {}
        # (5 unchanged attributes hidden)

      ~ default_action {
          ~ target_group_arn = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group-1/4dfadbcb821d0427" -> (known after apply)
            # (2 unchanged attributes hidden)
        }
    }

  # aws_lb_target_group.memo-alb-target-group will be created
+ resource "aws_lb_target_group" "memo-alb-target-group" {
      + arn                                = (known after apply)
      + arn_suffix                         = (known after apply)
      + connection_termination             = false
      + deregistration_delay               = "300"
      + id                                 = (known after apply)
      + lambda_multi_value_headers_enabled = false
      + load_balancing_algorithm_type      = (known after apply)
      + name                               = "memo-alb-target-group"
      + port                               = 8080
      + preserve_client_ip                 = (known after apply)
      + protocol                           = "HTTP"
      + protocol_version                   = (known after apply)
      + proxy_protocol_v2                  = false
      + slow_start                         = 0
      + tags_all                           = (known after apply)
      + target_type                        = "ip"
      + vpc_id                             = "vpc-0119ba5078755447e"

      + health_check {
          + enabled             = true
          + healthy_threshold   = 5
          + interval            = 10
          + matcher             = "200"
          + path                = "/"
          + port                = "traffic-port"
          + protocol            = "HTTP"
          + timeout             = 2
          + unhealthy_threshold = 5
        }

      + stickiness {
          + cookie_duration = (known after apply)
          + cookie_name     = (known after apply)
          + enabled         = (known after apply)
          + type            = (known after apply)
        }
    }

  # aws_lb_target_group.memo-alb-target-group-1 will be destroyed
  # (because aws_lb_target_group.memo-alb-target-group-1 is not in configuration)
- resource "aws_lb_target_group" "memo-alb-target-group-1" {
      - arn                                = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group-1/4dfadbcb821d0427" -> null
      - arn_suffix                         = "targetgroup/memo-alb-target-group-1/4dfadbcb821d0427" -> null
      - connection_termination             = false -> null
      - deregistration_delay               = "300" -> null
      - id                                 = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group-1/4dfadbcb821d0427" -> null
      - lambda_multi_value_headers_enabled = false -> null
      - load_balancing_algorithm_type      = "round_robin" -> null
      - name                               = "memo-alb-target-group-1" -> null
      - port                               = 8080 -> null
      - protocol                           = "HTTP" -> null
      - protocol_version                   = "HTTP1" -> null
      - proxy_protocol_v2                  = false -> null
      - slow_start                         = 0 -> null
      - tags                               = {} -> null
      - tags_all                           = {} -> null
      - target_type                        = "ip" -> null
      - vpc_id                             = "vpc-0119ba5078755447e" -> null

      - health_check {
          - enabled             = true -> null
          - healthy_threshold   = 5 -> null
          - interval            = 10 -> null
          - matcher             = "200" -> null
          - path                = "/" -> null
          - port                = "traffic-port" -> null
          - protocol            = "HTTP" -> null
          - timeout             = 2 -> null
          - unhealthy_threshold = 5 -> null
        }

      - stickiness {
          - cookie_duration = 86400 -> null
          - enabled         = false -> null
          - type            = "lb_cookie" -> null
        }
    }

Plan: 2 to add, 1 to change, 2 to destroy.
Releasing state lock. This may take a few moments...

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 2 to add, 1 to change, 2 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
aws_ecs_service.memo-ecs-service: Destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097:service/memo-ecs-cluster/memo-ecs-service]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 10s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 20s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 30s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 40s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 50s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 1m0s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 1m10s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 1m20s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 1m30s elapsed]
aws_ecs_service.memo-ecs-service: Destruction complete after 1m31s
aws_lb_target_group.memo-alb-target-group: Creating...
aws_lb_target_group.memo-alb-target-group: Creation complete after 0s [id=arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/b1282354ddf594fb]
aws_ecs_service.memo-ecs-service: Creating...
aws_lb_listener.memo-alb-listener: Modifying... [id=arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:listener/app/memo-alb/99c5d5623fa5aa5f/6d34e868e2d2e54e]
aws_lb_listener.memo-alb-listener: Modifications complete after 1s [id=arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:listener/app/memo-alb/99c5d5623fa5aa5f/6d34e868e2d2e54e]
aws_ecs_service.memo-ecs-service: Creation complete after 1s [id=arn:aws:ecs:ap-northeast-2:264842458097:service/memo-ecs-cluster/memo-ecs-service]
aws_lb_target_group.memo-alb-target-group-1: Destroying... [id=arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group-1/4dfadbcb821d0427]
aws_lb_target_group.memo-alb-target-group-1: Destruction complete after 0s

Apply complete! Resources: 2 added, 1 changed, 2 destroyed.


```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
