### PR TITLE
fix: port

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
-/+ destroy and then create replacement
+/- create replacement and then destroy

Terraform will perform the following actions:

  # aws_ecs_service.memo-ecs-service must be replaced
-/+ resource "aws_ecs_service" "memo-ecs-service" {
      - health_check_grace_period_seconds  = 0 -> null
      ~ iam_role                           = "aws-service-role" -> (known after apply)
      ~ id                                 = "arn:aws:ecs:ap-northeast-2:264842458097:service/memo-ecs-cluster/memo-ecs-service" -> (known after apply)
        name                               = "memo-ecs-service"
      ~ platform_version                   = "LATEST" -> (known after apply)
      - propagate_tags                     = "NONE" -> null
      - tags                               = {} -> null
      ~ tags_all                           = {} -> (known after apply)
      ~ task_definition                    = "arn:aws:ecs:ap-northeast-2:264842458097:task-definition/memo-ecs-task-definition:9" -> (known after apply)
        # (9 unchanged attributes hidden)

      - deployment_circuit_breaker {
          - enable   = false -> null
          - rollback = false -> null
        }

      - deployment_controller {
          - type = "ECS" -> null
        }

      - load_balancer { # forces replacement
          - container_name   = "memo-ecs-container" -> null
          - container_port   = 8080 -> null
          - target_group_arn = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/b7b417f7555897a6" -> null
        }
      + load_balancer { # forces replacement
          + container_name   = "memo-ecs-container"
          + container_port   = 8080
          + target_group_arn = (known after apply)
        }

        # (1 unchanged block hidden)
    }

  # aws_ecs_task_definition.memo-ecs-task-definition must be replaced
-/+ resource "aws_ecs_task_definition" "memo-ecs-task-definition" {
      ~ arn                      = "arn:aws:ecs:ap-northeast-2:264842458097:task-definition/memo-ecs-task-definition:9" -> (known after apply)
      ~ container_definitions    = jsonencode(
          ~ [ # forces replacement
              ~ {
                  - environment  = [] -> null
                  - mountPoints  = [] -> null
                  ~ portMappings = [
                      ~ {
                          ~ hostPort      = 8080 -> 80
                          - protocol      = "tcp" -> null
                            # (1 unchanged element hidden)
                        },
                    ]
                  - volumesFrom  = [] -> null
                    # (5 unchanged elements hidden)
                } # forces replacement,
            ]
        )
      ~ id                       = "memo-ecs-task-definition" -> (known after apply)
      ~ revision                 = 9 -> (known after apply)
      - tags                     = {} -> null
      ~ tags_all                 = {} -> (known after apply)
        # (7 unchanged attributes hidden)
    }

  # aws_lb_listener.memo-alb-listener will be updated in-place
~ resource "aws_lb_listener" "memo-alb-listener" {
        id                = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:listener/app/memo-alb/99c5d5623fa5aa5f/6d34e868e2d2e54e"
        tags              = {}
        # (5 unchanged attributes hidden)

      ~ default_action {
          ~ target_group_arn = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/b7b417f7555897a6" -> (known after apply)
            # (2 unchanged attributes hidden)
        }
    }

  # aws_lb_target_group.memo-alb-target-group must be replaced
+/- resource "aws_lb_target_group" "memo-alb-target-group" {
      ~ arn                                = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/b7b417f7555897a6" -> (known after apply)
      ~ arn_suffix                         = "targetgroup/memo-alb-target-group/b7b417f7555897a6" -> (known after apply)
      ~ id                                 = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/b7b417f7555897a6" -> (known after apply)
      ~ load_balancing_algorithm_type      = "round_robin" -> (known after apply)
        name                               = "memo-alb-target-group"
      ~ port                               = 8080 -> 80 # forces replacement
      + preserve_client_ip                 = (known after apply)
      ~ protocol_version                   = "HTTP1" -> (known after apply)
      - tags                               = {} -> null
      ~ tags_all                           = {} -> (known after apply)
        # (8 unchanged attributes hidden)


      ~ stickiness {
          ~ cookie_duration = 86400 -> (known after apply)
          + cookie_name     = (known after apply)
          ~ enabled         = false -> (known after apply)
          ~ type            = "lb_cookie" -> (known after apply)
        }
        # (1 unchanged block hidden)
    }

Plan: 3 to add, 1 to change, 3 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 3 to add, 1 to change, 3 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform apply -input=false \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/43/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/43/default": exit status 1
aws_ecs_service.memo-ecs-service: Destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097:service/memo-ecs-cluster/memo-ecs-service]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 10s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 20s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 30s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 40s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 50s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 1m0s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 1m10s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 1m20s elapsed]
aws_ecs_service.memo-ecs-service: Still destroying... [id=arn:aws:ecs:ap-northeast-2:264842458097...vice/memo-ecs-cluster/memo-ecs-service, 1m30s elapsed]
aws_ecs_service.memo-ecs-service: Destruction complete after 1m30s
aws_ecs_task_definition.memo-ecs-task-definition: Destroying... [id=memo-ecs-task-definition]
aws_lb_target_group.memo-alb-target-group: Creating...
aws_ecs_task_definition.memo-ecs-task-definition: Destruction complete after 0s
aws_ecs_task_definition.memo-ecs-task-definition: Creating...
╷
│ Error: error creating LB Target Group: DuplicateTargetGroupName: A target group with the same name 'memo-alb-target-group' exists, but with different settings
│ 	status code: 400, request id: 55c9569f-c85e-40c1-8dc8-383ee632f857
│ 
│   with aws_lb_target_group.memo-alb-target-group,
│   on memo.tf line 112, in resource "aws_lb_target_group" "memo-alb-target-group":
│  112: resource "aws_lb_target_group" "memo-alb-target-group" {
│ 
╵
╷
│ Error: failed creating ECS Task Definition (memo-ecs-task-definition): ClientException: When networkMode=awsvpc, the host ports and container ports in port mappings must match.
│ 
│   with aws_ecs_task_definition.memo-ecs-task-definition,
│   on memo.tf line 174, in resource "aws_ecs_task_definition" "memo-ecs-task-definition":
│  174: resource "aws_ecs_task_definition" "memo-ecs-task-definition" {
│ 
╵

```
</details>

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
~ update in-place
- destroy

Terraform will perform the following actions:

  # aws_ecs_service.memo-ecs-service will be created
+ resource "aws_ecs_service" "memo-ecs-service" {
      + cluster                            = "arn:aws:ecs:ap-northeast-2:264842458097:cluster/memo-ecs-cluster"
      + deployment_maximum_percent         = 200
      + deployment_minimum_healthy_percent = 100
      + desired_count                      = 1
      + enable_ecs_managed_tags            = false
      + enable_execute_command             = false
      + iam_role                           = (known after apply)
      + id                                 = (known after apply)
      + launch_type                        = "FARGATE"
      + name                               = "memo-ecs-service"
      + platform_version                   = (known after apply)
      + scheduling_strategy                = "REPLICA"
      + tags_all                           = (known after apply)
      + task_definition                    = (known after apply)
      + wait_for_steady_state              = false

      + load_balancer {
          + container_name   = "memo-ecs-container"
          + container_port   = 8080
          + target_group_arn = (known after apply)
        }

      + network_configuration {
          + assign_public_ip = true
          + security_groups  = [
              + "sg-06f64f1a2a42dfc63",
            ]
          + subnets          = [
              + "subnet-0b8de44bcd332b5ac",
              + "subnet-0bb6102ac68f7e016",
            ]
        }
    }

  # aws_ecs_task_definition.memo-ecs-task-definition will be created
+ resource "aws_ecs_task_definition" "memo-ecs-task-definition" {
      + arn                      = (known after apply)
      + container_definitions    = jsonencode(
            [
              + {
                  + cpu          = 256
                  + essential    = true
                  + image        = "264842458097.dkr.ecr.ap-northeast-2.amazonaws.com/memo-ecr:60ff002d7bd529810624885e733a9682303f8270"
                  + memory       = 512
                  + name         = "memo-ecs-container"
                  + portMappings = [
                      + {
                          + containerPort = 8080
                          + hostPort      = 80
                        },
                    ]
                },
            ]
        )
      + cpu                      = "256"
      + execution_role_arn       = "arn:aws:iam::264842458097:role/ecs-staging-execution-role"
      + family                   = "memo-ecs-task-definition"
      + id                       = (known after apply)
      + memory                   = "512"
      + network_mode             = "awsvpc"
      + requires_compatibilities = [
          + "FARGATE",
        ]
      + revision                 = (known after apply)
      + skip_destroy             = false
      + tags_all                 = (known after apply)
    }

  # aws_lb_listener.memo-alb-listener will be updated in-place
~ resource "aws_lb_listener" "memo-alb-listener" {
        id                = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:listener/app/memo-alb/99c5d5623fa5aa5f/6d34e868e2d2e54e"
        tags              = {}
        # (5 unchanged attributes hidden)

      ~ default_action {
          ~ target_group_arn = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/b7b417f7555897a6" -> (known after apply)
            # (2 unchanged attributes hidden)
        }
    }

  # aws_lb_target_group.memo-alb-target-group will be destroyed
  # (because aws_lb_target_group.memo-alb-target-group is not in configuration)
- resource "aws_lb_target_group" "memo-alb-target-group" {
      - arn                                = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/b7b417f7555897a6" -> null
      - arn_suffix                         = "targetgroup/memo-alb-target-group/b7b417f7555897a6" -> null
      - connection_termination             = false -> null
      - deregistration_delay               = "300" -> null
      - id                                 = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/b7b417f7555897a6" -> null
      - lambda_multi_value_headers_enabled = false -> null
      - load_balancing_algorithm_type      = "round_robin" -> null
      - name                               = "memo-alb-target-group" -> null
      - port                               = 8080 -> null
      - protocol                           = "HTTP" -> null
      - protocol_version                   = "HTTP1" -> null
      - proxy_protocol_v2                  = false -> null
      - slow_start                         = 0 -> null
      - tags                               = {} -> null
      - tags_all                           = {} -> null
      - target_type                        = "ip" -> null
      - vpc_id                             = "vpc-0119ba5078755447e" -> null

      - health_check {
          - enabled             = true -> null
          - healthy_threshold   = 5 -> null
          - interval            = 10 -> null
          - matcher             = "200" -> null
          - path                = "/" -> null
          - port                = "traffic-port" -> null
          - protocol            = "HTTP" -> null
          - timeout             = 2 -> null
          - unhealthy_threshold = 5 -> null
        }

      - stickiness {
          - cookie_duration = 86400 -> null
          - enabled         = false -> null
          - type            = "lb_cookie" -> null
        }
    }

  # aws_lb_target_group.memo-alb-target-group-1 will be created
+ resource "aws_lb_target_group" "memo-alb-target-group-1" {
      + arn                                = (known after apply)
      + arn_suffix                         = (known after apply)
      + connection_termination             = false
      + deregistration_delay               = "300"
      + id                                 = (known after apply)
      + lambda_multi_value_headers_enabled = false
      + load_balancing_algorithm_type      = (known after apply)
      + name                               = "memo-alb-target-group-1"
      + port                               = 80
      + preserve_client_ip                 = (known after apply)
      + protocol                           = "HTTP"
      + protocol_version                   = (known after apply)
      + proxy_protocol_v2                  = false
      + slow_start                         = 0
      + tags_all                           = (known after apply)
      + target_type                        = "ip"
      + vpc_id                             = "vpc-0119ba5078755447e"

      + health_check {
          + enabled             = true
          + healthy_threshold   = 5
          + interval            = 10
          + matcher             = "200"
          + path                = "/"
          + port                = "traffic-port"
          + protocol            = "HTTP"
          + timeout             = 2
          + unhealthy_threshold = 5
        }

      + stickiness {
          + cookie_duration = (known after apply)
          + cookie_name     = (known after apply)
          + enabled         = (known after apply)
          + type            = (known after apply)
        }
    }

Plan: 3 to add, 1 to change, 1 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 3 to add, 1 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
~ update in-place
- destroy

Terraform will perform the following actions:

  # aws_ecs_service.memo-ecs-service will be created
+ resource "aws_ecs_service" "memo-ecs-service" {
      + cluster                            = "arn:aws:ecs:ap-northeast-2:264842458097:cluster/memo-ecs-cluster"
      + deployment_maximum_percent         = 200
      + deployment_minimum_healthy_percent = 100
      + desired_count                      = 1
      + enable_ecs_managed_tags            = false
      + enable_execute_command             = false
      + iam_role                           = (known after apply)
      + id                                 = (known after apply)
      + launch_type                        = "FARGATE"
      + name                               = "memo-ecs-service"
      + platform_version                   = (known after apply)
      + scheduling_strategy                = "REPLICA"
      + tags_all                           = (known after apply)
      + task_definition                    = (known after apply)
      + wait_for_steady_state              = false

      + load_balancer {
          + container_name   = "memo-ecs-container"
          + container_port   = 8080
          + target_group_arn = (known after apply)
        }

      + network_configuration {
          + assign_public_ip = true
          + security_groups  = [
              + "sg-06f64f1a2a42dfc63",
            ]
          + subnets          = [
              + "subnet-0b8de44bcd332b5ac",
              + "subnet-0bb6102ac68f7e016",
            ]
        }
    }

  # aws_ecs_task_definition.memo-ecs-task-definition will be created
+ resource "aws_ecs_task_definition" "memo-ecs-task-definition" {
      + arn                      = (known after apply)
      + container_definitions    = jsonencode(
            [
              + {
                  + cpu          = 256
                  + essential    = true
                  + image        = "264842458097.dkr.ecr.ap-northeast-2.amazonaws.com/memo-ecr:60ff002d7bd529810624885e733a9682303f8270"
                  + memory       = 512
                  + name         = "memo-ecs-container"
                  + portMappings = [
                      + {
                          + containerPort = 8080
                          + hostPort      = 8080
                        },
                    ]
                },
            ]
        )
      + cpu                      = "256"
      + execution_role_arn       = "arn:aws:iam::264842458097:role/ecs-staging-execution-role"
      + family                   = "memo-ecs-task-definition"
      + id                       = (known after apply)
      + memory                   = "512"
      + network_mode             = "awsvpc"
      + requires_compatibilities = [
          + "FARGATE",
        ]
      + revision                 = (known after apply)
      + skip_destroy             = false
      + tags_all                 = (known after apply)
    }

  # aws_lb_listener.memo-alb-listener will be updated in-place
~ resource "aws_lb_listener" "memo-alb-listener" {
        id                = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:listener/app/memo-alb/99c5d5623fa5aa5f/6d34e868e2d2e54e"
        tags              = {}
        # (5 unchanged attributes hidden)

      ~ default_action {
          ~ target_group_arn = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/b7b417f7555897a6" -> (known after apply)
            # (2 unchanged attributes hidden)
        }
    }

  # aws_lb_target_group.memo-alb-target-group will be destroyed
  # (because aws_lb_target_group.memo-alb-target-group is not in configuration)
- resource "aws_lb_target_group" "memo-alb-target-group" {
      - arn                                = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/b7b417f7555897a6" -> null
      - arn_suffix                         = "targetgroup/memo-alb-target-group/b7b417f7555897a6" -> null
      - connection_termination             = false -> null
      - deregistration_delay               = "300" -> null
      - id                                 = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/b7b417f7555897a6" -> null
      - lambda_multi_value_headers_enabled = false -> null
      - load_balancing_algorithm_type      = "round_robin" -> null
      - name                               = "memo-alb-target-group" -> null
      - port                               = 8080 -> null
      - protocol                           = "HTTP" -> null
      - protocol_version                   = "HTTP1" -> null
      - proxy_protocol_v2                  = false -> null
      - slow_start                         = 0 -> null
      - tags                               = {} -> null
      - tags_all                           = {} -> null
      - target_type                        = "ip" -> null
      - vpc_id                             = "vpc-0119ba5078755447e" -> null

      - health_check {
          - enabled             = true -> null
          - healthy_threshold   = 5 -> null
          - interval            = 10 -> null
          - matcher             = "200" -> null
          - path                = "/" -> null
          - port                = "traffic-port" -> null
          - protocol            = "HTTP" -> null
          - timeout             = 2 -> null
          - unhealthy_threshold = 5 -> null
        }

      - stickiness {
          - cookie_duration = 86400 -> null
          - enabled         = false -> null
          - type            = "lb_cookie" -> null
        }
    }

  # aws_lb_target_group.memo-alb-target-group-1 will be created
+ resource "aws_lb_target_group" "memo-alb-target-group-1" {
      + arn                                = (known after apply)
      + arn_suffix                         = (known after apply)
      + connection_termination             = false
      + deregistration_delay               = "300"
      + id                                 = (known after apply)
      + lambda_multi_value_headers_enabled = false
      + load_balancing_algorithm_type      = (known after apply)
      + name                               = "memo-alb-target-group-1"
      + port                               = 8080
      + preserve_client_ip                 = (known after apply)
      + protocol                           = "HTTP"
      + protocol_version                   = (known after apply)
      + proxy_protocol_v2                  = false
      + slow_start                         = 0
      + tags_all                           = (known after apply)
      + target_type                        = "ip"
      + vpc_id                             = "vpc-0119ba5078755447e"

      + health_check {
          + enabled             = true
          + healthy_threshold   = 5
          + interval            = 10
          + matcher             = "200"
          + path                = "/"
          + port                = "traffic-port"
          + protocol            = "HTTP"
          + timeout             = 2
          + unhealthy_threshold = 5
        }

      + stickiness {
          + cookie_duration = (known after apply)
          + cookie_name     = (known after apply)
          + enabled         = (known after apply)
          + type            = (known after apply)
        }
    }

  # aws_security_group.memo-security-group will be updated in-place
~ resource "aws_security_group" "memo-security-group" {
        id                     = "sg-06f64f1a2a42dfc63"
      ~ ingress                = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/32",
                ]
              + description      = "HTTP"
              + from_port        = 8080
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 8080
            },
            # (1 unchanged element hidden)
        ]
        name                   = "memo-security-group"
        tags                   = {
            "Name" = "memo-security-group"
        }
        # (7 unchanged attributes hidden)
    }

Plan: 3 to add, 2 to change, 1 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 3 to add, 2 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
Acquiring state lock. This may take a few moments...
aws_ecs_task_definition.memo-ecs-task-definition: Creating...
aws_lb_target_group.memo-alb-target-group-1: Creating...
aws_security_group.memo-security-group: Modifying... [id=sg-06f64f1a2a42dfc63]
aws_ecs_task_definition.memo-ecs-task-definition: Creation complete after 0s [id=memo-ecs-task-definition]
aws_lb_target_group.memo-alb-target-group-1: Creation complete after 0s [id=arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group-1/4dfadbcb821d0427]
aws_lb_listener.memo-alb-listener: Modifying... [id=arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:listener/app/memo-alb/99c5d5623fa5aa5f/6d34e868e2d2e54e]
aws_lb_listener.memo-alb-listener: Modifications complete after 0s [id=arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:listener/app/memo-alb/99c5d5623fa5aa5f/6d34e868e2d2e54e]
aws_lb_target_group.memo-alb-target-group: Destroying... [id=arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/b7b417f7555897a6]
aws_lb_target_group.memo-alb-target-group: Destruction complete after 0s
aws_security_group.memo-security-group: Modifications complete after 0s [id=sg-06f64f1a2a42dfc63]
aws_ecs_service.memo-ecs-service: Creating...
aws_ecs_service.memo-ecs-service: Creation complete after 1s [id=arn:aws:ecs:ap-northeast-2:264842458097:service/memo-ecs-cluster/memo-ecs-service]
Releasing state lock. This may take a few moments...

Apply complete! Resources: 3 added, 2 changed, 1 destroyed.


```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
