### PR TITLE
fix: infra 통합 및 처음부터 다시 만들기

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
~ update in-place
- destroy

Terraform will perform the following actions:

  # aws_eip.stage_server will be updated in-place
~ resource "aws_eip" "stage_server" {
        id                   = "eipalloc-0b75e301a5b3e6534"
      ~ instance             = "i-0abdca8a9d70c1957" -> (known after apply)
        tags                 = {}
        # (12 unchanged attributes hidden)
    }

  # aws_instance.iac-ec2-20220223 will be created
+ resource "aws_instance" "iac-ec2-20220223" {
      + ami                                  = "ami-0454bb2fefc7de534"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = (known after apply)
      + availability_zone                    = (known after apply)
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "t3.nano"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = "Home"
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + subnet_id                            = (known after apply)
      + tags                                 = {
          + "Name" = "iac-ec2-20220223"
        }
      + tags_all                             = {
          + "Name" = "iac-ec2-20220223"
        }
      + tenancy                              = (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
      + vpc_security_group_ids               = (known after apply)

      + capacity_reservation_specification {
          + capacity_reservation_preference = (known after apply)

          + capacity_reservation_target {
              + capacity_reservation_id = (known after apply)
            }
        }

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + enclave_options {
          + enabled = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
          + instance_metadata_tags      = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      + root_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }
    }

  # aws_instance.stage_server will be destroyed
  # (because aws_instance.stage_server is not in configuration)
- resource "aws_instance" "stage_server" {
      - ami                                  = "ami-0454bb2fefc7de534" -> null
      - arn                                  = "arn:aws:ec2:ap-northeast-2:264842458097:instance/i-0abdca8a9d70c1957" -> null
      - associate_public_ip_address          = true -> null
      - availability_zone                    = "ap-northeast-2d" -> null
      - cpu_core_count                       = 1 -> null
      - cpu_threads_per_core                 = 2 -> null
      - disable_api_termination              = false -> null
      - ebs_optimized                        = false -> null
      - get_password_data                    = false -> null
      - hibernation                          = false -> null
      - id                                   = "i-0abdca8a9d70c1957" -> null
      - instance_initiated_shutdown_behavior = "stop" -> null
      - instance_state                       = "running" -> null
      - instance_type                        = "t3.nano" -> null
      - ipv6_address_count                   = 0 -> null
      - ipv6_addresses                       = [] -> null
      - key_name                             = "Home" -> null
      - monitoring                           = false -> null
      - primary_network_interface_id         = "eni-0e11e0afc5db48e40" -> null
      - private_dns                          = "ip-10-0-1-153.ap-northeast-2.compute.internal" -> null
      - private_ip                           = "10.0.1.153" -> null
      - public_ip                            = "3.35.1.46" -> null
      - secondary_private_ips                = [] -> null
      - security_groups                      = [] -> null
      - source_dest_check                    = true -> null
      - subnet_id                            = "subnet-0be5f104144d52efc" -> null
      - tags                                 = {
          - "Name" = "stage_server"
        } -> null
      - tags_all                             = {
          - "Name" = "stage_server"
        } -> null
      - tenancy                              = "default" -> null
      - vpc_security_group_ids               = [
          - "sg-07edfb9d72aa83b69",
        ] -> null

      - capacity_reservation_specification {
          - capacity_reservation_preference = "open" -> null
        }

      - credit_specification {
          - cpu_credits = "unlimited" -> null
        }

      - enclave_options {
          - enabled = false -> null
        }

      - metadata_options {
          - http_endpoint               = "enabled" -> null
          - http_put_response_hop_limit = 1 -> null
          - http_tokens                 = "optional" -> null
          - instance_metadata_tags      = "disabled" -> null
        }

      - root_block_device {
          - delete_on_termination = true -> null
          - device_name           = "/dev/sda1" -> null
          - encrypted             = false -> null
          - iops                  = 100 -> null
          - tags                  = {} -> null
          - throughput            = 0 -> null
          - volume_id             = "vol-0be58df5448d15781" -> null
          - volume_size           = 8 -> null
          - volume_type           = "gp2" -> null
        }
    }

  # aws_internet_gateway.iac-igw will be destroyed
  # (because aws_internet_gateway.iac-igw is not in configuration)
- resource "aws_internet_gateway" "iac-igw" {
      - arn      = "arn:aws:ec2:ap-northeast-2:264842458097:internet-gateway/igw-0e1bd0e0ac954279d" -> null
      - id       = "igw-0e1bd0e0ac954279d" -> null
      - owner_id = "264842458097" -> null
      - tags     = {
          - "Name" = "iac-igw"
        } -> null
      - tags_all = {
          - "Name" = "iac-igw"
        } -> null
      - vpc_id   = "vpc-08dcb17c8de524b67" -> null
    }

  # aws_internet_gateway.iac-igw-20220223 will be created
+ resource "aws_internet_gateway" "iac-igw-20220223" {
      + arn      = (known after apply)
      + id       = (known after apply)
      + owner_id = (known after apply)
      + tags     = {
          + "Name" = "iac-igw-20220223"
        }
      + tags_all = {
          + "Name" = "iac-igw-20220223"
        }
      + vpc_id   = (known after apply)
    }

  # aws_route_table.iac-route-table will be destroyed
  # (because aws_route_table.iac-route-table is not in configuration)
- resource "aws_route_table" "iac-route-table" {
      - arn              = "arn:aws:ec2:ap-northeast-2:264842458097:route-table/rtb-0efdc44c6bfa956da" -> null
      - id               = "rtb-0efdc44c6bfa956da" -> null
      - owner_id         = "264842458097" -> null
      - propagating_vgws = [] -> null
      - route            = [
          - {
              - carrier_gateway_id         = ""
              - cidr_block                 = "0.0.0.0/0"
              - destination_prefix_list_id = ""
              - egress_only_gateway_id     = ""
              - gateway_id                 = "igw-0e1bd0e0ac954279d"
              - instance_id                = ""
              - ipv6_cidr_block            = ""
              - local_gateway_id           = ""
              - nat_gateway_id             = ""
              - network_interface_id       = ""
              - transit_gateway_id         = ""
              - vpc_endpoint_id            = ""
              - vpc_peering_connection_id  = ""
            },
        ] -> null
      - tags             = {
          - "Name" = "iac-route-table"
        } -> null
      - tags_all         = {
          - "Name" = "iac-route-table"
        } -> null
      - vpc_id           = "vpc-08dcb17c8de524b67" -> null
    }

  # aws_route_table.iac-routing-table-20220223 will be created
+ resource "aws_route_table" "iac-routing-table-20220223" {
      + arn              = (known after apply)
      + id               = (known after apply)
      + owner_id         = (known after apply)
      + propagating_vgws = (known after apply)
      + route            = [
          + {
              + carrier_gateway_id         = ""
              + cidr_block                 = "0.0.0.0/0"
              + destination_prefix_list_id = ""
              + egress_only_gateway_id     = ""
              + gateway_id                 = (known after apply)
              + instance_id                = ""
              + ipv6_cidr_block            = ""
              + local_gateway_id           = ""
              + nat_gateway_id             = ""
              + network_interface_id       = ""
              + transit_gateway_id         = ""
              + vpc_endpoint_id            = ""
              + vpc_peering_connection_id  = ""
            },
        ]
      + tags             = {
          + "Name" = "iac-routing-table-20220223"
        }
      + tags_all         = {
          + "Name" = "iac-routing-table-20220223"
        }
      + vpc_id           = (known after apply)
    }

  # aws_security_group.allow_coffee_tree will be destroyed
  # (because aws_security_group.allow_coffee_tree is not in configuration)
- resource "aws_security_group" "allow_coffee_tree" {
      - arn                    = "arn:aws:ec2:ap-northeast-2:264842458097:security-group/sg-07edfb9d72aa83b69" -> null
      - description            = "Allow CoffeeTree inbound traffic" -> null
      - egress                 = [
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = ""
              - from_port        = 0
              - ipv6_cidr_blocks = [
                  - "::/0",
                ]
              - prefix_list_ids  = []
              - protocol         = "-1"
              - security_groups  = []
              - self             = false
              - to_port          = 0
            },
        ] -> null
      - id                     = "sg-07edfb9d72aa83b69" -> null
      - ingress                = [
          - {
              - cidr_blocks      = [
                  - "39.7.28.205/32",
                ]
              - description      = "SSH"
              - from_port        = 22
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 22
            },
        ] -> null
      - name                   = "allow_coffee_tree" -> null
      - owner_id               = "264842458097" -> null
      - revoke_rules_on_delete = false -> null
      - tags                   = {
          - "Name" = "allow_coffee_tree"
        } -> null
      - tags_all               = {
          - "Name" = "allow_coffee_tree"
        } -> null
      - vpc_id                 = "vpc-08dcb17c8de524b67" -> null
    }

  # aws_security_group.iac-security-group-20220223 will be created
+ resource "aws_security_group" "iac-security-group-20220223" {
      + arn                    = (known after apply)
      + description            = "Allow CoffeeTree inbound traffic"
      + egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "-1"
              + security_groups  = []
              + self             = false
              + to_port          = 0
            },
        ]
      + id                     = (known after apply)
      + ingress                = [
          + {
              + cidr_blocks      = [
                  + "39.7.28.205/32",
                ]
              + description      = "SSH"
              + from_port        = 22
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 22
            },
        ]
      + name                   = "iac-security-group-20220223"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "Name" = "iac-security-group-20220223"
        }
      + tags_all               = {
          + "Name" = "iac-security-group-20220223"
        }
      + vpc_id                 = (known after apply)
    }

  # aws_subnet.iac-subnet will be destroyed
  # (because aws_subnet.iac-subnet is not in configuration)
- resource "aws_subnet" "iac-subnet" {
      - arn                                            = "arn:aws:ec2:ap-northeast-2:264842458097:subnet/subnet-0be5f104144d52efc" -> null
      - assign_ipv6_address_on_creation                = false -> null
      - availability_zone                              = "ap-northeast-2d" -> null
      - availability_zone_id                           = "apne2-az4" -> null
      - cidr_block                                     = "10.0.1.0/24" -> null
      - enable_dns64                                   = false -> null
      - enable_resource_name_dns_a_record_on_launch    = false -> null
      - enable_resource_name_dns_aaaa_record_on_launch = false -> null
      - id                                             = "subnet-0be5f104144d52efc" -> null
      - ipv6_native                                    = false -> null
      - map_customer_owned_ip_on_launch                = false -> null
      - map_public_ip_on_launch                        = false -> null
      - owner_id                                       = "264842458097" -> null
      - private_dns_hostname_type_on_launch            = "ip-name" -> null
      - tags                                           = {} -> null
      - tags_all                                       = {} -> null
      - vpc_id                                         = "vpc-08dcb17c8de524b67" -> null
    }

  # aws_subnet.iac-subnet-20220223 will be created
+ resource "aws_subnet" "iac-subnet-20220223" {
      + arn                                            = (known after apply)
      + assign_ipv6_address_on_creation                = false
      + availability_zone                              = (known after apply)
      + availability_zone_id                           = (known after apply)
      + cidr_block                                     = "10.0.1.0/24"
      + enable_dns64                                   = false
      + enable_resource_name_dns_a_record_on_launch    = false
      + enable_resource_name_dns_aaaa_record_on_launch = false
      + id                                             = (known after apply)
      + ipv6_cidr_block_association_id                 = (known after apply)
      + ipv6_native                                    = false
      + map_public_ip_on_launch                        = false
      + owner_id                                       = (known after apply)
      + private_dns_hostname_type_on_launch            = (known after apply)
      + tags_all                                       = (known after apply)
      + vpc_id                                         = (known after apply)
    }

  # aws_vpc.iac-vpc will be destroyed
  # (because aws_vpc.iac-vpc is not in configuration)
- resource "aws_vpc" "iac-vpc" {
      - arn                              = "arn:aws:ec2:ap-northeast-2:264842458097:vpc/vpc-08dcb17c8de524b67" -> null
      - assign_generated_ipv6_cidr_block = false -> null
      - cidr_block                       = "10.0.0.0/16" -> null
      - default_network_acl_id           = "acl-0081249c4e1719283" -> null
      - default_route_table_id           = "rtb-00e47f88b396e343d" -> null
      - default_security_group_id        = "sg-0a586123bbdd9dea0" -> null
      - dhcp_options_id                  = "dopt-0439dc969e8731205" -> null
      - enable_classiclink               = false -> null
      - enable_classiclink_dns_support   = false -> null
      - enable_dns_hostnames             = false -> null
      - enable_dns_support               = true -> null
      - id                               = "vpc-08dcb17c8de524b67" -> null
      - instance_tenancy                 = "default" -> null
      - ipv6_netmask_length              = 0 -> null
      - main_route_table_id              = "rtb-00e47f88b396e343d" -> null
      - owner_id                         = "264842458097" -> null
      - tags                             = {} -> null
      - tags_all                         = {} -> null
    }

  # aws_vpc.iac-vpc-20220223 will be created
+ resource "aws_vpc" "iac-vpc-20220223" {
      + arn                                  = (known after apply)
      + cidr_block                           = "10.0.0.0/16"
      + default_network_acl_id               = (known after apply)
      + default_route_table_id               = (known after apply)
      + default_security_group_id            = (known after apply)
      + dhcp_options_id                      = (known after apply)
      + enable_classiclink                   = (known after apply)
      + enable_classiclink_dns_support       = (known after apply)
      + enable_dns_hostnames                 = (known after apply)
      + enable_dns_support                   = true
      + id                                   = (known after apply)
      + instance_tenancy                     = "default"
      + ipv6_association_id                  = (known after apply)
      + ipv6_cidr_block                      = (known after apply)
      + ipv6_cidr_block_network_border_group = (known after apply)
      + main_route_table_id                  = (known after apply)
      + owner_id                             = (known after apply)
      + tags                                 = {
          + "Name" = "iac-vpc-20220223"
        }
      + tags_all                             = {
          + "Name" = "iac-vpc-20220223"
        }
    }

Plan: 6 to add, 1 to change, 6 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 6 to add, 1 to change, 6 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by rhea-so** [comment]
제발!

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
aws_route_table.iac-route-table: Destroying... [id=rtb-0efdc44c6bfa956da]
aws_instance.stage_server: Destroying... [id=i-0abdca8a9d70c1957]
aws_vpc.iac-vpc-20220223: Creating...
aws_route_table.iac-route-table: Destruction complete after 0s
aws_internet_gateway.iac-igw: Destroying... [id=igw-0e1bd0e0ac954279d]
aws_vpc.iac-vpc-20220223: Creation complete after 1s [id=vpc-0ef1a2cf24ec0eeda]
aws_internet_gateway.iac-igw-20220223: Creating...
aws_security_group.iac-security-group-20220223: Creating...
aws_subnet.iac-subnet-20220223: Creating...
aws_internet_gateway.iac-igw-20220223: Creation complete after 0s [id=igw-0d7fc83f1a73f0cfd]
aws_route_table.iac-routing-table-20220223: Creating...
aws_subnet.iac-subnet-20220223: Creation complete after 0s [id=subnet-0f934a92067b0f67e]
aws_route_table.iac-routing-table-20220223: Creation complete after 0s [id=rtb-0a1e2908f34d32eb9]
aws_security_group.iac-security-group-20220223: Creation complete after 2s [id=sg-0d141357be85e3913]
aws_instance.iac-ec2-20220223: Creating...
aws_instance.stage_server: Still destroying... [id=i-0abdca8a9d70c1957, 10s elapsed]
aws_internet_gateway.iac-igw: Still destroying... [id=igw-0e1bd0e0ac954279d, 10s elapsed]
aws_instance.iac-ec2-20220223: Still creating... [10s elapsed]
aws_instance.iac-ec2-20220223: Creation complete after 12s [id=i-030bd725830bab8e0]
aws_instance.stage_server: Still destroying... [id=i-0abdca8a9d70c1957, 20s elapsed]
aws_internet_gateway.iac-igw: Still destroying... [id=igw-0e1bd0e0ac954279d, 20s elapsed]
aws_internet_gateway.iac-igw: Destruction complete after 27s
aws_instance.stage_server: Destruction complete after 30s
aws_subnet.iac-subnet: Destroying... [id=subnet-0be5f104144d52efc]
aws_security_group.allow_coffee_tree: Destroying... [id=sg-07edfb9d72aa83b69]
aws_security_group.allow_coffee_tree: Destruction complete after 0s
aws_subnet.iac-subnet: Destruction complete after 0s
aws_vpc.iac-vpc: Destroying... [id=vpc-08dcb17c8de524b67]
aws_vpc.iac-vpc: Destruction complete after 0s
aws_eip.stage_server: Modifying... [id=eipalloc-0b75e301a5b3e6534]
aws_eip.stage_server: Modifications complete after 1s [id=eipalloc-0b75e301a5b3e6534]

Apply complete! Resources: 6 added, 1 changed, 6 destroyed.


```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
