### PR TITLE
Atlantis Test

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/bin/terraform init -input=false -upgrade" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/11/default": exit status 1

Initializing the backend...
╷
│ Error: Required token could not be found
│ 
│ Run the following command to generate a token for app.terraform.io:
│     terraform login
╵


```

**Comment by rhea-so** [comment]
atlantis plan

**Comment by rhea-so** [comment]
atlantis plan

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform init -input=false -upgrade" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/11/default": exit status 1

Initializing the backend...
╷
│ Error: Failed to read organization "rhea-so-lab" at host app.terraform.io
│ 
│   on ec2.tf line 10, in terraform:
│   10:     organization = "rhea-so-lab"
│ 
│ The "remote" backend encountered an unexpected error while reading the
│ organization settings: organization "rhea-so-lab" at host app.terraform.io
│ not found.
│ 
│ Please ensure that the organization and hostname are correct and that your
│ API token for app.terraform.io is valid.
╵


```
</details>

**Comment by rhea-so** [comment]
atlantis plan

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/bin/terraform plan -input=false -refresh -out \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/11/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/11/default": exit status 1
╷
│ Error: Saving a generated plan is currently not supported
│ 
│ The "remote" backend does not support saving the generated execution plan
│ locally at this time.
╵

```

**Comment by rhea-so** [comment]
atlantis plan

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.


```

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
