### PR TITLE
fix: backup

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_lb.memo-alb has been deleted
- resource "aws_lb" "memo-alb" {
      - arn                        = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:loadbalancer/app/memo-alb/99c5d5623fa5aa5f" -> null
      - arn_suffix                 = "app/memo-alb/99c5d5623fa5aa5f" -> null
      - desync_mitigation_mode     = "defensive" -> null
      - dns_name                   = "memo-alb-1655237520.ap-northeast-2.elb.amazonaws.com" -> null
      - drop_invalid_header_fields = false -> null
      - enable_deletion_protection = true -> null
      - enable_http2               = true -> null
      - enable_waf_fail_open       = false -> null
      - id                         = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:loadbalancer/app/memo-alb/99c5d5623fa5aa5f" -> null
      - idle_timeout               = 60 -> null
      - internal                   = false -> null
      - ip_address_type            = "ipv4" -> null
      - load_balancer_type         = "application" -> null
      - name                       = "memo-alb" -> null
      - security_groups            = [
          - "sg-06f64f1a2a42dfc63",
        ] -> null
      - subnets                    = [
          - "subnet-0b8de44bcd332b5ac",
          - "subnet-0bb6102ac68f7e016",
        ] -> null
      - tags                       = {
          - "Name" = "memo-alb"
        } -> null
      - tags_all                   = {
          - "Name" = "memo-alb"
        } -> null
      - vpc_id                     = "vpc-0119ba5078755447e" -> null
      - zone_id                    = "ZWKZPGTI48KDX" -> null

      - access_logs {
          - enabled = false -> null
        }

      - subnet_mapping {
          - subnet_id = "subnet-0b8de44bcd332b5ac" -> null
        }
      - subnet_mapping {
          - subnet_id = "subnet-0bb6102ac68f7e016" -> null
        }
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # aws_security_group.memo-security-group will be destroyed
  # (because aws_security_group.memo-security-group is not in configuration)
- resource "aws_security_group" "memo-security-group" {
      - arn                    = "arn:aws:ec2:ap-northeast-2:264842458097:security-group/sg-06f64f1a2a42dfc63" -> null
      - description            = "Memo Service Security Group" -> null
      - egress                 = [
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = ""
              - from_port        = 0
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "-1"
              - security_groups  = []
              - self             = false
              - to_port          = 0
            },
        ] -> null
      - id                     = "sg-06f64f1a2a42dfc63" -> null
      - ingress                = [
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = "HTTP"
              - from_port        = 443
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 443
            },
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = "HTTP"
              - from_port        = 8080
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 8080
            },
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = "HTTP"
              - from_port        = 80
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 80
            },
        ] -> null
      - name                   = "memo-security-group" -> null
      - owner_id               = "264842458097" -> null
      - revoke_rules_on_delete = false -> null
      - tags                   = {
          - "Name" = "memo-security-group"
        } -> null
      - tags_all               = {
          - "Name" = "memo-security-group"
        } -> null
      - vpc_id                 = "vpc-0119ba5078755447e" -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 0 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
aws_security_group.memo-security-group: Destroying... [id=sg-06f64f1a2a42dfc63]
aws_security_group.memo-security-group: Destruction complete after 0s

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.


```

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
