### PR TITLE
fix: task definition

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_ecs_service.memo-ecs-service has changed
~ resource "aws_ecs_service" "memo-ecs-service" {
        id                                 = "arn:aws:ecs:ap-northeast-2:264842458097:service/memo-ecs-cluster/memo-ecs-service"
        name                               = "memo-ecs-service"
      + tags                               = {}
        # (15 unchanged attributes hidden)




        # (4 unchanged blocks hidden)
    }

  # aws_ecs_task_definition.memo-ecs-task-definition has changed
~ resource "aws_ecs_task_definition" "memo-ecs-task-definition" {
        id                       = "memo-ecs-task-definition"
      + tags                     = {}
        # (11 unchanged attributes hidden)
    }

  # aws_lb_target_group.memo-alb-target-group has changed
~ resource "aws_lb_target_group" "memo-alb-target-group" {
        id                                 = "arn:aws:elasticloadbalancing:ap-northeast-2:264842458097:targetgroup/memo-alb-target-group/b7b417f7555897a6"
        name                               = "memo-alb-target-group"
      + tags                               = {}
        # (14 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # aws_ecs_service.memo-ecs-service will be updated in-place
~ resource "aws_ecs_service" "memo-ecs-service" {
        id                                 = "arn:aws:ecs:ap-northeast-2:264842458097:service/memo-ecs-cluster/memo-ecs-service"
        name                               = "memo-ecs-service"
        tags                               = {}
      ~ task_definition                    = "arn:aws:ecs:ap-northeast-2:264842458097:task-definition/memo-ecs-task-definition:8" -> (known after apply)
        # (14 unchanged attributes hidden)




        # (4 unchanged blocks hidden)
    }

  # aws_ecs_task_definition.memo-ecs-task-definition must be replaced
-/+ resource "aws_ecs_task_definition" "memo-ecs-task-definition" {
      ~ arn                      = "arn:aws:ecs:ap-northeast-2:264842458097:task-definition/memo-ecs-task-definition:8" -> (known after apply)
      ~ container_definitions    = jsonencode(
          ~ [ # forces replacement
              ~ {
                  - environment  = [] -> null
                  ~ image        = "264842458097.dkr.ecr.ap-northeast-2.amazonaws.com/60ff002d7bd529810624885e733a9682303f8270" -> "264842458097.dkr.ecr.ap-northeast-2.amazonaws.com/memo-ecr:60ff002d7bd529810624885e733a9682303f8270"
                  - mountPoints  = [] -> null
                  ~ portMappings = [
                      ~ {
                          - protocol      = "tcp" -> null
                            # (2 unchanged elements hidden)
                        },
                    ]
                  - volumesFrom  = [] -> null
                    # (4 unchanged elements hidden)
                } # forces replacement,
            ]
        )
      ~ id                       = "memo-ecs-task-definition" -> (known after apply)
      ~ revision                 = 8 -> (known after apply)
      - tags                     = {} -> null
      ~ tags_all                 = {} -> (known after apply)
        # (7 unchanged attributes hidden)
    }

Plan: 1 to add, 1 to change, 1 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 1 to add, 1 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Pull request merged**
