### PR TITLE
test: route53

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for 3 projects:

1. dir: `00_Environment/03_Production` workspace: `default`
1. dir: `01_Common/01_Route53/01_Zone` workspace: `default`
1. dir: `01_Common/01_Route53/02_Record` workspace: `default`

### 1. dir: `00_Environment/03_Production` workspace: `default`
**Plan Error**
```
running "/usr/bin/terraform plan -input=false -refresh -out \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/101/default/00_Environment/03_Production/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/101/default/00_Environment/03_Production": exit status 1
╷
│ Error: Unsupported argument
│ 
│   on ../../01_Common/01_Route53/01_Zone/main.tf line 3, in resource "aws_route53_zone" "domain":
│    3:   allow_overwrite = true
│ 
│ An argument named "allow_overwrite" is not expected here.
╵

```

---
### 2. dir: `01_Common/01_Route53/01_Zone` workspace: `default`
**Plan Error**
```
running "/usr/bin/terraform plan -input=false -refresh -out \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/101/default/01_Common/01_Route53/01_Zone/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/101/default/01_Common/01_Route53/01_Zone": exit status 1
╷
│ Error: No value for required variable
│ 
│   on variables.tf line 1:
│    1: variable "name" {
│ 
│ The root module input variable "name" is not set, and has no default value.
│ Use a -var or -var-file command line argument to provide a value for this
│ variable.
╵

```

---
### 3. dir: `01_Common/01_Route53/02_Record` workspace: `default`
**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform plan -input=false -refresh -out \"/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/101/default/01_Common/01_Route53/02_Record/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/rhea-so-lab/Infrastructure-as-Code/101/default/01_Common/01_Route53/02_Record": exit status 1
╷
│ Error: No value for required variable
│ 
│   on variables.tf line 1:
│    1: variable "zone_id" {
│ 
│ The root module input variable "zone_id" is not set, and has no default
│ value. Use a -var or -var-file command line argument to provide a value for
│ this variable.
╵
╷
│ Error: No value for required variable
│ 
│   on variables.tf line 5:
│    5: variable "name" {
│ 
│ The root module input variable "name" is not set, and has no default value.
│ Use a -var or -var-file command line argument to provide a value for this
│ variable.
╵
╷
│ Error: No value for required variable
│ 
│   on variables.tf line 19:
│   19: variable "target" {
│ 
│ The root module input variable "target" is not set, and has no default
│ value. Use a -var or -var-file command line argument to provide a value for
│ this variable.
╵

```
</details>

---

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `00_Environment/03_Production` workspace: `production`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.atlantis-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = true
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "atlantis.rhea-so.com"
      + records         = [
          + "52.78.144.248",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

  # module.google-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = true
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "google.rhea-so.com"
      + records         = [
          + "172.217.31.174",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

  # module.rhea-so.aws_route53_zone.domain will be created
+ resource "aws_route53_zone" "domain" {
      + arn           = (known after apply)
      + comment       = "Managed by Terraform"
      + force_destroy = false
      + id            = (known after apply)
      + name          = "rhea-so.com"
      + name_servers  = (known after apply)
      + tags_all      = (known after apply)
      + zone_id       = (known after apply)
    }

  # module.test-rhea-so.aws_route53_record.domain will be created
+ resource "aws_route53_record" "domain" {
      + allow_overwrite = true
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "test.rhea-so.com"
      + records         = [
          + "172.217.31.174",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = (known after apply)
    }

Plan: 4 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production -w production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fproduction)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d 00_Environment/03_Production -w production`
</details>
Plan: 4 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `00_Environment/03_Production` workspace: `production`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d 00_Environment/03_Production -w production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F00_Environment%252F03_Production%252Fproduction)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d 00_Environment/03_Production -w production`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `00_Environment/03_Production` workspace: `production`

<details><summary>Show Output</summary>

```diff
module.rhea-so.aws_route53_zone.domain: Creating...
module.rhea-so.aws_route53_zone.domain: Still creating... [10s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [20s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [30s elapsed]
module.rhea-so.aws_route53_zone.domain: Still creating... [40s elapsed]
module.rhea-so.aws_route53_zone.domain: Creation complete after 49s [id=Z06537322A2IALBF7YMDK]
module.test-rhea-so.aws_route53_record.domain: Creating...
module.google-rhea-so.aws_route53_record.domain: Creating...
module.atlantis-rhea-so.aws_route53_record.domain: Creating...
module.test-rhea-so.aws_route53_record.domain: Still creating... [10s elapsed]
module.google-rhea-so.aws_route53_record.domain: Still creating... [11s elapsed]
module.atlantis-rhea-so.aws_route53_record.domain: Still creating... [11s elapsed]
module.test-rhea-so.aws_route53_record.domain: Still creating... [21s elapsed]
module.atlantis-rhea-so.aws_route53_record.domain: Still creating... [21s elapsed]
module.google-rhea-so.aws_route53_record.domain: Still creating... [21s elapsed]
module.test-rhea-so.aws_route53_record.domain: Still creating... [31s elapsed]
module.google-rhea-so.aws_route53_record.domain: Still creating... [31s elapsed]
module.atlantis-rhea-so.aws_route53_record.domain: Still creating... [31s elapsed]
module.test-rhea-so.aws_route53_record.domain: Still creating... [41s elapsed]
module.atlantis-rhea-so.aws_route53_record.domain: Still creating... [41s elapsed]
module.google-rhea-so.aws_route53_record.domain: Still creating... [41s elapsed]
module.google-rhea-so.aws_route53_record.domain: Creation complete after 43s [id=Z06537322A2IALBF7YMDK_google.rhea-so.com_A]
module.atlantis-rhea-so.aws_route53_record.domain: Creation complete after 46s [id=Z06537322A2IALBF7YMDK_atlantis.rhea-so.com_A]
module.test-rhea-so.aws_route53_record.domain: Creation complete after 48s [id=Z06537322A2IALBF7YMDK_test.rhea-so.com_A]

Apply complete! Resources: 4 added, 0 changed, 0 destroyed.


```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `00_Environment/03_Production` workspace: `production`

**Pull request merged**
