### PR TITLE
add: subnet enable_resource_name_dns_a_record_on_launch

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_instance.iac-ec2-20220223 has changed
~ resource "aws_instance" "iac-ec2-20220223" {
        id                                   = "i-030bd725830bab8e0"
      ~ public_ip                            = "3.35.1.46" -> "3.39.31.8"
        tags                                 = {
            "Name" = "iac-ec2-20220223"
        }
        # (27 unchanged attributes hidden)





        # (5 unchanged blocks hidden)
    }

  # aws_route53_record.iac-route53-20220223 has changed
~ resource "aws_route53_record" "iac-route53-20220223" {
        id      = "Z0991838PJM65M902BCW_iac.rhea-so.com_A"
        name    = "iac.rhea-so.com"
        # (5 unchanged attributes hidden)
    }

  # aws_route53_zone.primary has changed
~ resource "aws_route53_zone" "primary" {
        id            = "Z0991838PJM65M902BCW"
        name          = "rhea-so.com"
      + tags          = {}
        # (6 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # aws_subnet.iac-subnet-20220223 will be updated in-place
~ resource "aws_subnet" "iac-subnet-20220223" {
      ~ enable_resource_name_dns_a_record_on_launch    = false -> true
        id                                             = "subnet-0f934a92067b0f67e"
      ~ tags                                           = {
          + "Name" = "iac-subnet-20220223"
        }
      ~ tags_all                                       = {
          + "Name" = "iac-subnet-20220223"
        }
        # (13 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 0 to add, 1 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
aws_subnet.iac-subnet-20220223: Modifying... [id=subnet-0f934a92067b0f67e]
aws_subnet.iac-subnet-20220223: Still modifying... [id=subnet-0f934a92067b0f67e, 10s elapsed]
aws_subnet.iac-subnet-20220223: Modifications complete after 11s [id=subnet-0f934a92067b0f67e]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.


```

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
