### PR TITLE
delete: test ec2

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_instance.iac-ec2 has changed
~ resource "aws_instance" "iac-ec2" {
      ~ associate_public_ip_address          = false -> true
        id                                   = "i-022a567ede4d5b2f1"
      + public_ip                            = "3.34.237.221"
        tags                                 = {
            "Name" = "iac-ec2"
        }
        # (26 unchanged attributes hidden)





        # (5 unchanged blocks hidden)
    }

  # aws_route53_record.iac-route53 has changed
~ resource "aws_route53_record" "iac-route53" {
        id      = "Z02629952Z1ESWD7VTUX1_ec2.rhea-so.com_A"
        name    = "ec2.rhea-so.com"
        # (5 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # aws_eip.iac-eip will be destroyed
  # (because aws_eip.iac-eip is not in configuration)
- resource "aws_eip" "iac-eip" {
      - allocation_id        = "eipalloc-047c669b957d3aaed" -> null
      - association_id       = "eipassoc-0dc711336a4c25a69" -> null
      - domain               = "vpc" -> null
      - id                   = "eipalloc-047c669b957d3aaed" -> null
      - instance             = "i-022a567ede4d5b2f1" -> null
      - network_border_group = "ap-northeast-2" -> null
      - network_interface    = "eni-05e60e713fd7b292b" -> null
      - private_dns          = "ip-10-0-3-124.ap-northeast-2.compute.internal" -> null
      - private_ip           = "10.0.3.124" -> null
      - public_dns           = "ec2-3-34-237-221.ap-northeast-2.compute.amazonaws.com" -> null
      - public_ip            = "3.34.237.221" -> null
      - public_ipv4_pool     = "amazon" -> null
      - tags                 = {
          - "Name" = "iac-eip"
        } -> null
      - tags_all             = {
          - "Name" = "iac-eip"
        } -> null
      - vpc                  = true -> null
    }

  # aws_instance.iac-ec2 will be destroyed
  # (because aws_instance.iac-ec2 is not in configuration)
- resource "aws_instance" "iac-ec2" {
      - ami                                  = "ami-0454bb2fefc7de534" -> null
      - arn                                  = "arn:aws:ec2:ap-northeast-2:264842458097:instance/i-022a567ede4d5b2f1" -> null
      - associate_public_ip_address          = true -> null
      - availability_zone                    = "ap-northeast-2a" -> null
      - cpu_core_count                       = 1 -> null
      - cpu_threads_per_core                 = 2 -> null
      - disable_api_termination              = false -> null
      - ebs_optimized                        = false -> null
      - get_password_data                    = false -> null
      - hibernation                          = false -> null
      - id                                   = "i-022a567ede4d5b2f1" -> null
      - instance_initiated_shutdown_behavior = "stop" -> null
      - instance_state                       = "running" -> null
      - instance_type                        = "t3.nano" -> null
      - ipv6_address_count                   = 0 -> null
      - ipv6_addresses                       = [] -> null
      - key_name                             = "Home" -> null
      - monitoring                           = false -> null
      - primary_network_interface_id         = "eni-05e60e713fd7b292b" -> null
      - private_dns                          = "ip-10-0-3-124.ap-northeast-2.compute.internal" -> null
      - private_ip                           = "10.0.3.124" -> null
      - public_ip                            = "3.34.237.221" -> null
      - secondary_private_ips                = [] -> null
      - security_groups                      = [] -> null
      - source_dest_check                    = true -> null
      - subnet_id                            = "subnet-0bb6102ac68f7e016" -> null
      - tags                                 = {
          - "Name" = "iac-ec2"
        } -> null
      - tags_all                             = {
          - "Name" = "iac-ec2"
        } -> null
      - tenancy                              = "default" -> null
      - vpc_security_group_ids               = [
          - "sg-05d239f4d436a496f",
        ] -> null

      - capacity_reservation_specification {
          - capacity_reservation_preference = "open" -> null
        }

      - credit_specification {
          - cpu_credits = "unlimited" -> null
        }

      - enclave_options {
          - enabled = false -> null
        }

      - metadata_options {
          - http_endpoint               = "enabled" -> null
          - http_put_response_hop_limit = 1 -> null
          - http_tokens                 = "optional" -> null
          - instance_metadata_tags      = "disabled" -> null
        }

      - root_block_device {
          - delete_on_termination = true -> null
          - device_name           = "/dev/sda1" -> null
          - encrypted             = false -> null
          - iops                  = 100 -> null
          - tags                  = {} -> null
          - throughput            = 0 -> null
          - volume_id             = "vol-0574f77ed919f5439" -> null
          - volume_size           = 8 -> null
          - volume_type           = "gp2" -> null
        }
    }

  # aws_route53_record.iac-route53 will be destroyed
  # (because aws_route53_record.iac-route53 is not in configuration)
- resource "aws_route53_record" "iac-route53" {
      - fqdn    = "ec2.rhea-so.com" -> null
      - id      = "Z02629952Z1ESWD7VTUX1_ec2.rhea-so.com_A" -> null
      - name    = "ec2.rhea-so.com" -> null
      - records = [
          - "3.34.237.221",
        ] -> null
      - ttl     = 300 -> null
      - type    = "A" -> null
      - zone_id = "Z02629952Z1ESWD7VTUX1" -> null
    }

  # aws_security_group.iac-security-group will be destroyed
  # (because aws_security_group.iac-security-group is not in configuration)
- resource "aws_security_group" "iac-security-group" {
      - arn                    = "arn:aws:ec2:ap-northeast-2:264842458097:security-group/sg-05d239f4d436a496f" -> null
      - description            = "Allow CoffeeTree inbound traffic" -> null
      - egress                 = [
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = ""
              - from_port        = 0
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "-1"
              - security_groups  = []
              - self             = false
              - to_port          = 0
            },
        ] -> null
      - id                     = "sg-05d239f4d436a496f" -> null
      - ingress                = [
          - {
              - cidr_blocks      = [
                  - "39.7.24.115/32",
                ]
              - description      = "SSH"
              - from_port        = 22
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 22
            },
        ] -> null
      - name                   = "iac-security-group" -> null
      - owner_id               = "264842458097" -> null
      - revoke_rules_on_delete = false -> null
      - tags                   = {
          - "Name" = "iac-security-group"
        } -> null
      - tags_all               = {
          - "Name" = "iac-security-group"
        } -> null
      - vpc_id                 = "vpc-0119ba5078755447e" -> null
    }

Plan: 0 to add, 0 to change, 4 to destroy.

Changes to Outputs:
- iac-eip = "3.34.237.221" -> null

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 0 to add, 0 to change, 4 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
