### PR TITLE
add: CloudWatch

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_cloudwatch_metric_alarm.iac-cloudwatch-ec2-cpu-usage has changed
~ resource "aws_cloudwatch_metric_alarm" "iac-cloudwatch-ec2-cpu-usage" {
        id                        = "iac-cloudwatch-ec2-cpu-usage"
      + insufficient_data_actions = []
      + tags                      = {}
        # (17 unchanged attributes hidden)
    }

  # aws_sns_topic_subscription.iac-sns-topic-subscription has changed
~ resource "aws_sns_topic_subscription" "iac-sns-topic-subscription" {
        id                              = "arn:aws:sns:ap-northeast-2:264842458097:iac-sns-topic:1dd44a4d-32b0-4aa6-93c9-6ca1a417dfa4"
      ~ pending_confirmation            = true -> false
        # (9 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # aws_cloudwatch_metric_alarm.iac-cloudwatch-ec2-cpu-usage will be destroyed
  # (because aws_cloudwatch_metric_alarm.iac-cloudwatch-ec2-cpu-usage is not in configuration)
- resource "aws_cloudwatch_metric_alarm" "iac-cloudwatch-ec2-cpu-usage" {
      - actions_enabled           = true -> null
      - alarm_actions             = [
          - "arn:aws:sns:ap-northeast-2:264842458097:iac-sns-topic",
        ] -> null
      - alarm_description         = "This metric monitors ec2 cpu utilization" -> null
      - alarm_name                = "iac-cloudwatch-ec2-cpu-usage" -> null
      - arn                       = "arn:aws:cloudwatch:ap-northeast-2:264842458097:alarm:iac-cloudwatch-ec2-cpu-usage" -> null
      - comparison_operator       = "GreaterThanOrEqualToThreshold" -> null
      - datapoints_to_alarm       = 0 -> null
      - dimensions                = {
          - "InstanceId" = "i-08151ffcf77bdbdf3"
        } -> null
      - evaluation_periods        = 2 -> null
      - id                        = "iac-cloudwatch-ec2-cpu-usage" -> null
      - insufficient_data_actions = [] -> null
      - metric_name               = "CPUUtilization" -> null
      - namespace                 = "AWS/EC2" -> null
      - ok_actions                = [
          - "arn:aws:sns:ap-northeast-2:264842458097:iac-sns-topic",
        ] -> null
      - period                    = 120 -> null
      - statistic                 = "Average" -> null
      - tags                      = {} -> null
      - tags_all                  = {} -> null
      - threshold                 = 0 -> null
      - treat_missing_data        = "missing" -> null
    }

  # aws_eip.iac-eip will be destroyed
  # (because aws_eip.iac-eip is not in configuration)
- resource "aws_eip" "iac-eip" {
      - allocation_id        = "eipalloc-0290c2d379d6bbcb4" -> null
      - association_id       = "eipassoc-053b033e11b9c5548" -> null
      - domain               = "vpc" -> null
      - id                   = "eipalloc-0290c2d379d6bbcb4" -> null
      - instance             = "i-08151ffcf77bdbdf3" -> null
      - network_border_group = "ap-northeast-2" -> null
      - network_interface    = "eni-09991e7616ee8243d" -> null
      - private_dns          = "ip-10-0-3-234.ap-northeast-2.compute.internal" -> null
      - private_ip           = "10.0.3.234" -> null
      - public_dns           = "ec2-3-39-58-131.ap-northeast-2.compute.amazonaws.com" -> null
      - public_ip            = "3.39.58.131" -> null
      - public_ipv4_pool     = "amazon" -> null
      - tags                 = {
          - "Name" = "iac-eip"
        } -> null
      - tags_all             = {
          - "Name" = "iac-eip"
        } -> null
      - vpc                  = true -> null
    }

  # aws_instance.iac-ec2 will be destroyed
  # (because aws_instance.iac-ec2 is not in configuration)
- resource "aws_instance" "iac-ec2" {
      - ami                                  = "ami-0454bb2fefc7de534" -> null
      - arn                                  = "arn:aws:ec2:ap-northeast-2:264842458097:instance/i-08151ffcf77bdbdf3" -> null
      - associate_public_ip_address          = true -> null
      - availability_zone                    = "ap-northeast-2a" -> null
      - cpu_core_count                       = 1 -> null
      - cpu_threads_per_core                 = 2 -> null
      - disable_api_termination              = false -> null
      - ebs_optimized                        = false -> null
      - get_password_data                    = false -> null
      - hibernation                          = false -> null
      - id                                   = "i-08151ffcf77bdbdf3" -> null
      - instance_initiated_shutdown_behavior = "stop" -> null
      - instance_state                       = "running" -> null
      - instance_type                        = "t3.nano" -> null
      - ipv6_address_count                   = 0 -> null
      - ipv6_addresses                       = [] -> null
      - key_name                             = "Home" -> null
      - monitoring                           = false -> null
      - primary_network_interface_id         = "eni-09991e7616ee8243d" -> null
      - private_dns                          = "ip-10-0-3-234.ap-northeast-2.compute.internal" -> null
      - private_ip                           = "10.0.3.234" -> null
      - public_ip                            = "3.39.58.131" -> null
      - secondary_private_ips                = [] -> null
      - security_groups                      = [] -> null
      - source_dest_check                    = true -> null
      - subnet_id                            = "subnet-0bb6102ac68f7e016" -> null
      - tags                                 = {
          - "Name" = "iac-ec2"
        } -> null
      - tags_all                             = {
          - "Name" = "iac-ec2"
        } -> null
      - tenancy                              = "default" -> null
      - vpc_security_group_ids               = [
          - "sg-0616a9d215c727d7e",
        ] -> null

      - capacity_reservation_specification {
          - capacity_reservation_preference = "open" -> null
        }

      - credit_specification {
          - cpu_credits = "unlimited" -> null
        }

      - enclave_options {
          - enabled = false -> null
        }

      - metadata_options {
          - http_endpoint               = "enabled" -> null
          - http_put_response_hop_limit = 1 -> null
          - http_tokens                 = "optional" -> null
          - instance_metadata_tags      = "disabled" -> null
        }

      - root_block_device {
          - delete_on_termination = true -> null
          - device_name           = "/dev/sda1" -> null
          - encrypted             = false -> null
          - iops                  = 100 -> null
          - tags                  = {} -> null
          - throughput            = 0 -> null
          - volume_id             = "vol-0097cad9d39682112" -> null
          - volume_size           = 8 -> null
          - volume_type           = "gp2" -> null
        }
    }

  # aws_route53_record.iac-route53 will be destroyed
  # (because aws_route53_record.iac-route53 is not in configuration)
- resource "aws_route53_record" "iac-route53" {
      - fqdn    = "ec2.rhea-so.com" -> null
      - id      = "Z02629952Z1ESWD7VTUX1_ec2.rhea-so.com_A" -> null
      - name    = "ec2.rhea-so.com" -> null
      - records = [
          - "3.39.58.131",
        ] -> null
      - ttl     = 300 -> null
      - type    = "A" -> null
      - zone_id = "Z02629952Z1ESWD7VTUX1" -> null
    }

  # aws_security_group.iac-security-group will be destroyed
  # (because aws_security_group.iac-security-group is not in configuration)
- resource "aws_security_group" "iac-security-group" {
      - arn                    = "arn:aws:ec2:ap-northeast-2:264842458097:security-group/sg-0616a9d215c727d7e" -> null
      - description            = "Allow CoffeeTree inbound traffic" -> null
      - egress                 = [
          - {
              - cidr_blocks      = [
                  - "0.0.0.0/0",
                ]
              - description      = ""
              - from_port        = 0
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "-1"
              - security_groups  = []
              - self             = false
              - to_port          = 0
            },
        ] -> null
      - id                     = "sg-0616a9d215c727d7e" -> null
      - ingress                = [
          - {
              - cidr_blocks      = [
                  - "39.7.24.115/32",
                ]
              - description      = "SSH"
              - from_port        = 22
              - ipv6_cidr_blocks = []
              - prefix_list_ids  = []
              - protocol         = "tcp"
              - security_groups  = []
              - self             = false
              - to_port          = 22
            },
        ] -> null
      - name                   = "iac-security-group" -> null
      - owner_id               = "264842458097" -> null
      - revoke_rules_on_delete = false -> null
      - tags                   = {
          - "Name" = "iac-security-group"
        } -> null
      - tags_all               = {
          - "Name" = "iac-security-group"
        } -> null
      - vpc_id                 = "vpc-0119ba5078755447e" -> null
    }

  # aws_sns_topic.iac-sns-topic will be destroyed
  # (because aws_sns_topic.iac-sns-topic is not in configuration)
- resource "aws_sns_topic" "iac-sns-topic" {
      - application_success_feedback_sample_rate = 0 -> null
      - arn                                      = "arn:aws:sns:ap-northeast-2:264842458097:iac-sns-topic" -> null
      - content_based_deduplication              = false -> null
      - fifo_topic                               = false -> null
      - firehose_success_feedback_sample_rate    = 0 -> null
      - http_success_feedback_sample_rate        = 0 -> null
      - id                                       = "arn:aws:sns:ap-northeast-2:264842458097:iac-sns-topic" -> null
      - lambda_success_feedback_sample_rate      = 0 -> null
      - name                                     = "iac-sns-topic" -> null
      - owner                                    = "264842458097" -> null
      - policy                                   = jsonencode(
            {
              - Id        = "__default_policy_ID"
              - Statement = [
                  - {
                      - Action    = [
                          - "SNS:GetTopicAttributes",
                          - "SNS:SetTopicAttributes",
                          - "SNS:AddPermission",
                          - "SNS:RemovePermission",
                          - "SNS:DeleteTopic",
                          - "SNS:Subscribe",
                          - "SNS:ListSubscriptionsByTopic",
                          - "SNS:Publish",
                        ]
                      - Condition = {
                          - StringEquals = {
                              - AWS:SourceOwner = "264842458097"
                            }
                        }
                      - Effect    = "Allow"
                      - Principal = {
                          - AWS = "*"
                        }
                      - Resource  = "arn:aws:sns:ap-northeast-2:264842458097:iac-sns-topic"
                      - Sid       = "__default_statement_ID"
                    },
                ]
              - Version   = "2008-10-17"
            }
        ) -> null
      - sqs_success_feedback_sample_rate         = 0 -> null
      - tags                                     = {} -> null
      - tags_all                                 = {} -> null
    }

  # aws_sns_topic_subscription.iac-sns-topic-subscription will be destroyed
  # (because aws_sns_topic_subscription.iac-sns-topic-subscription is not in configuration)
- resource "aws_sns_topic_subscription" "iac-sns-topic-subscription" {
      - arn                             = "arn:aws:sns:ap-northeast-2:264842458097:iac-sns-topic:1dd44a4d-32b0-4aa6-93c9-6ca1a417dfa4" -> null
      - confirmation_timeout_in_minutes = 1 -> null
      - confirmation_was_authenticated  = false -> null
      - endpoint                        = "jeonghyeon.rhea@gmail.com" -> null
      - endpoint_auto_confirms          = false -> null
      - id                              = "arn:aws:sns:ap-northeast-2:264842458097:iac-sns-topic:1dd44a4d-32b0-4aa6-93c9-6ca1a417dfa4" -> null
      - owner_id                        = "264842458097" -> null
      - pending_confirmation            = false -> null
      - protocol                        = "email" -> null
      - raw_message_delivery            = false -> null
      - topic_arn                       = "arn:aws:sns:ap-northeast-2:264842458097:iac-sns-topic" -> null
    }

Plan: 0 to add, 0 to change, 7 to destroy.

Changes to Outputs:
- iac-eip = "3.39.58.131" -> null

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 0 to add, 0 to change, 7 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
Acquiring state lock. This may take a few moments...
aws_cloudwatch_metric_alarm.iac-cloudwatch-ec2-cpu-usage: Destroying... [id=iac-cloudwatch-ec2-cpu-usage]
aws_route53_record.iac-route53: Destroying... [id=Z02629952Z1ESWD7VTUX1_ec2.rhea-so.com_A]
aws_sns_topic_subscription.iac-sns-topic-subscription: Destroying... [id=arn:aws:sns:ap-northeast-2:264842458097:iac-sns-topic:1dd44a4d-32b0-4aa6-93c9-6ca1a417dfa4]
aws_cloudwatch_metric_alarm.iac-cloudwatch-ec2-cpu-usage: Destruction complete after 0s
aws_route53_record.iac-route53: Still destroying... [id=Z02629952Z1ESWD7VTUX1_ec2.rhea-so.com_A, 10s elapsed]
aws_sns_topic_subscription.iac-sns-topic-subscription: Still destroying... [id=arn:aws:sns:ap-northeast-2:264842458097...c:1dd44a4d-32b0-4aa6-93c9-6ca1a417dfa4, 10s elapsed]
aws_route53_record.iac-route53: Still destroying... [id=Z02629952Z1ESWD7VTUX1_ec2.rhea-so.com_A, 20s elapsed]
aws_sns_topic_subscription.iac-sns-topic-subscription: Still destroying... [id=arn:aws:sns:ap-northeast-2:264842458097...c:1dd44a4d-32b0-4aa6-93c9-6ca1a417dfa4, 20s elapsed]
aws_route53_record.iac-route53: Still destroying... [id=Z02629952Z1ESWD7VTUX1_ec2.rhea-so.com_A, 30s elapsed]
aws_sns_topic_subscription.iac-sns-topic-subscription: Still destroying... [id=arn:aws:sns:ap-northeast-2:264842458097...c:1dd44a4d-32b0-4aa6-93c9-6ca1a417dfa4, 30s elapsed]
aws_sns_topic_subscription.iac-sns-topic-subscription: Destruction complete after 33s
aws_sns_topic.iac-sns-topic: Destroying... [id=arn:aws:sns:ap-northeast-2:264842458097:iac-sns-topic]
aws_sns_topic.iac-sns-topic: Destruction complete after 0s
aws_route53_record.iac-route53: Still destroying... [id=Z02629952Z1ESWD7VTUX1_ec2.rhea-so.com_A, 40s elapsed]
aws_route53_record.iac-route53: Destruction complete after 44s
aws_eip.iac-eip: Destroying... [id=eipalloc-0290c2d379d6bbcb4]
aws_eip.iac-eip: Destruction complete after 2s
aws_instance.iac-ec2: Destroying... [id=i-08151ffcf77bdbdf3]
aws_instance.iac-ec2: Still destroying... [id=i-08151ffcf77bdbdf3, 10s elapsed]
aws_instance.iac-ec2: Still destroying... [id=i-08151ffcf77bdbdf3, 20s elapsed]
aws_instance.iac-ec2: Still destroying... [id=i-08151ffcf77bdbdf3, 30s elapsed]
aws_instance.iac-ec2: Still destroying... [id=i-08151ffcf77bdbdf3, 40s elapsed]
aws_instance.iac-ec2: Destruction complete after 50s
aws_security_group.iac-security-group: Destroying... [id=sg-0616a9d215c727d7e]
aws_security_group.iac-security-group: Destruction complete after 0s

Apply complete! Resources: 0 added, 0 changed, 7 destroyed.


```
</details>

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
