### PR TITLE
fix: cpu

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_ecs_task_definition.memo-ecs-task-definition has changed
~ resource "aws_ecs_task_definition" "memo-ecs-task-definition" {
        id                       = "memo-ecs-task-definition"
      + requires_compatibilities = []
      + tags                     = {}
        # (6 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # aws_ecs_task_definition.memo-ecs-task-definition must be replaced
-/+ resource "aws_ecs_task_definition" "memo-ecs-task-definition" {
      ~ arn                      = "arn:aws:ecs:ap-northeast-2:264842458097:task-definition/memo-ecs-task-definition:3" -> (known after apply)
      ~ container_definitions    = jsonencode(
          ~ [ # forces replacement
              ~ {
                  ~ cpu          = 128 -> 256
                  - environment  = [] -> null
                  ~ memory       = 256 -> 512
                  - mountPoints  = [] -> null
                  ~ portMappings = [
                      ~ {
                          - protocol      = "tcp" -> null
                            # (2 unchanged elements hidden)
                        },
                    ]
                  - volumesFrom  = [] -> null
                    # (3 unchanged elements hidden)
                } # forces replacement,
            ]
        )
      ~ id                       = "memo-ecs-task-definition" -> (known after apply)
      + network_mode             = (known after apply)
      - requires_compatibilities = [] -> null
      ~ revision                 = 3 -> (known after apply)
      - tags                     = {} -> null
      ~ tags_all                 = {} -> (known after apply)
        # (2 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 1 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
aws_ecs_task_definition.memo-ecs-task-definition: Destroying... [id=memo-ecs-task-definition]
aws_ecs_task_definition.memo-ecs-task-definition: Destruction complete after 0s
aws_ecs_task_definition.memo-ecs-task-definition: Creating...
aws_ecs_task_definition.memo-ecs-task-definition: Creation complete after 1s [id=memo-ecs-task-definition]
Releasing state lock. This may take a few moments...

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.


```

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
