### PR TITLE
Delete ec2.tf

### PR DESCRIPTION
**Pull request by rhea-so**

### CODE REVIEW

**Comment by AyameNakiri** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
aws_instance.backstage_server: Refreshing state... [id=i-0014ec1f83b44b129]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # aws_instance.backstage_server will be destroyed
  # (because aws_instance.backstage_server is not in configuration)
- resource "aws_instance" "backstage_server" {
      - ami                                  = "ami-0454bb2fefc7de534" -> null
      - arn                                  = "arn:aws:ec2:ap-northeast-2:264842458097:instance/i-0014ec1f83b44b129" -> null
      - associate_public_ip_address          = true -> null
      - availability_zone                    = "ap-northeast-2b" -> null
      - cpu_core_count                       = 1 -> null
      - cpu_threads_per_core                 = 2 -> null
      - disable_api_termination              = false -> null
      - ebs_optimized                        = false -> null
      - get_password_data                    = false -> null
      - hibernation                          = false -> null
      - id                                   = "i-0014ec1f83b44b129" -> null
      - instance_initiated_shutdown_behavior = "stop" -> null
      - instance_state                       = "running" -> null
      - instance_type                        = "t3.nano" -> null
      - ipv6_address_count                   = 0 -> null
      - ipv6_addresses                       = [] -> null
      - key_name                             = "Home" -> null
      - monitoring                           = false -> null
      - primary_network_interface_id         = "eni-06751cb6281b04554" -> null
      - private_dns                          = "ip-172-31-26-118.ap-northeast-2.compute.internal" -> null
      - private_ip                           = "172.31.26.118" -> null
      - public_dns                           = "ec2-3-38-205-218.ap-northeast-2.compute.amazonaws.com" -> null
      - public_ip                            = "3.38.205.218" -> null
      - secondary_private_ips                = [] -> null
      - security_groups                      = [
          - "default",
        ] -> null
      - source_dest_check                    = true -> null
      - subnet_id                            = "subnet-0e1859483d2a76bb9" -> null
      - tags                                 = {
          - "Name" = "RheaSoBackstageEC2"
        } -> null
      - tags_all                             = {
          - "Name" = "RheaSoBackstageEC2"
        } -> null
      - tenancy                              = "default" -> null
      - vpc_security_group_ids               = [
          - "sg-02e06e9cc8f6a53e3",
        ] -> null

      - capacity_reservation_specification {
          - capacity_reservation_preference = "open" -> null
        }

      - credit_specification {
          - cpu_credits = "unlimited" -> null
        }

      - enclave_options {
          - enabled = false -> null
        }

      - metadata_options {
          - http_endpoint               = "enabled" -> null
          - http_put_response_hop_limit = 1 -> null
          - http_tokens                 = "optional" -> null
          - instance_metadata_tags      = "disabled" -> null
        }

      - root_block_device {
          - delete_on_termination = true -> null
          - device_name           = "/dev/sda1" -> null
          - encrypted             = false -> null
          - iops                  = 100 -> null
          - tags                  = {} -> null
          - throughput            = 0 -> null
          - volume_id             = "vol-0c9c99664efb84115" -> null
          - volume_size           = 8 -> null
          - volume_type           = "gp2" -> null
        }
    }

Plan: 0 to add, 0 to change, 1 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 0 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by AyameNakiri** [comment]
Ran Policy Check for dir: `.` workspace: `default`

```diff
Checking plan against the following policies: 
  null_resource_warning

1 test, 1 passed, 0 warnings, 0 failures, 0 exceptions

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://52.78.144.248/lock?id=rhea-so-lab%252FInfrastructure-as-Code%252F.%252Fdefault)
* :repeat: To re-run policies **plan** this project again by commenting:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by rhea-so** [comment]
atlantis apply

**Comment by AyameNakiri** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
aws_instance.backstage_server: Destroying... [id=i-0014ec1f83b44b129]
aws_instance.backstage_server: Still destroying... [id=i-0014ec1f83b44b129, 10s elapsed]
aws_instance.backstage_server: Still destroying... [id=i-0014ec1f83b44b129, 20s elapsed]
aws_instance.backstage_server: Still destroying... [id=i-0014ec1f83b44b129, 30s elapsed]
aws_instance.backstage_server: Still destroying... [id=i-0014ec1f83b44b129, 40s elapsed]
aws_instance.backstage_server: Still destroying... [id=i-0014ec1f83b44b129, 50s elapsed]
aws_instance.backstage_server: Destruction complete after 1m0s

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.


```

**Comment by AyameNakiri** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by AyameNakiri** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Comment by rhea-so** [comment]
atlantis plan

**Comment by AyameNakiri** [comment]
Atlantis commands can't be run on closed pull requests

**Comment by rhea-so** [comment]
atlantis help

**Comment by AyameNakiri** [comment]
```cmake
atlantis
Terraform Pull Request Automation

Usage:
  atlantis <command> [options] -- [terraform options]

Examples:
  # run plan in the root directory passing the -target flag to terraform
  atlantis plan -d . -- -target=resource

  # apply all unapplied plans from this pull request
  atlantis apply

  # apply the plan for the root directory and staging workspace
  atlantis apply -d . -w staging

Commands:
  plan     Runs 'terraform plan' for the changes in this pull request.
           To plan a specific project, use the -d, -w and -p flags.
  apply    Runs 'terraform apply' on all unapplied plans from this pull request.
           To only apply a specific plan, use the -d, -w and -p flags.
  unlock   Removes all atlantis locks and discards all plans for this PR.
           To unlock a specific plan you can use the Atlantis UI.
  approve_policies
           Approves all current policy checking failures for the PR.
  version  Print the output of 'terraform version'
  help     View help.

Flags:
  -h, --help   help for atlantis

Use "atlantis [command] --help" for more information about a command.
```

**Pull request merged**
